/**
 * ABHI-only HR Performance fixtures — real employee ids from hr_employees.
 */
import {
  blankCompetencyScores,
  blankQuestionResponses,
  type HrPerformanceObjective,
  type HrPerformanceReview,
} from "@/lib/hr-performance-data";

function isoDaysFromNow(offset: number) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

const PETER = {
  id: "abhi-emp-peter-ellingworth",
  name: "Peter Ellingworth",
  role: "Chief Executive Officer",
  department: "Leadership",
};
const JANE = {
  id: "abhi-emp-jane-lewis",
  name: "Jane Lewis",
  role: "Chief Operating Officer and Chief Financial Officer",
  department: "Leadership",
};
const JUDITH = {
  id: "abhi-emp-judith-mellis",
  name: "Judith Mellis",
  role: "Senior Manager, UK Market Affairs",
  department: "UK Market Affairs",
};
const MICHELLE = {
  id: "abhi-emp-michelle-michelucci",
  name: "Michelle Michelucci",
  role: "Head of International Events",
  department: "International Events",
};
const REBECCA = {
  id: "abhi-emp-rebecca-parkin",
  name: "Rebecca Parkin",
  role: "Associate Director, Digital Health",
  department: "Digital Health",
};
const SOPHIE = {
  id: "abhi-emp-sophie-green",
  name: "Sophie Green",
  role: "International Accelerator Manager",
  department: "International",
};
const OWAIN = {
  id: "abhi-emp-owain-prescott",
  name: "Owain Prescott",
  role: "Market Access Executive",
  department: "Market Access",
};
const PHIL = {
  id: "abhi-emp-phil-brown",
  name: "Phil Brown",
  role: "Director, Regulatory & Compliance",
  department: "Regulatory",
};
const ANDREW = {
  id: "abhi-emp-andrew-davies",
  name: "Andrew Davies",
  role: "Executive Director, Digital Health",
  department: "Digital Health",
};
const CHARLOTTE = {
  id: "abhi-emp-charlotte-hart",
  name: "Charlotte Hart",
  role: "Communications and Events Executive",
  department: "Communications",
};

function ratedResponses(scores: number[]) {
  return blankQuestionResponses().map((item, index) => ({
    ...item,
    rating: (scores[index] ?? 4) as 1 | 2 | 3 | 4 | 5,
    managerComments: index % 6 === 0 ? "Consistently strong contribution." : "",
    employeeComments: index % 8 === 0 ? "Agreed — focus area for next cycle." : "",
  }));
}

function competencies(scores: number[], prefix: string) {
  return blankCompetencyScores().map((item, index) => ({
    ...item,
    id: `${prefix}-${index}`,
    score: (scores[index] ?? 4) as 1 | 2 | 3 | 4 | 5,
    notes: index === 0 ? "Key strength for ABHI members" : "",
  }));
}

export function buildAbhiPerformanceReviews(): HrPerformanceReview[] {
  return [
    {
      id: "abhi-rev-jane",
      employeeId: JANE.id,
      employeeName: JANE.name,
      department: JANE.department,
      role: JANE.role,
      managerName: PETER.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 5,
      strengths: "Operational grip across membership, finance, and events delivery.",
      areasForImprovement: "Protect strategic focus during peak WHX planning windows.",
      trainingRecommendations: "Board-level financial storytelling workshop",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals: "Deliver membership growth to 379 and hold cash discipline through Q4 events.",
      nextReviewDate: isoDaysFromNow(110),
      summary: "Outstanding half — membership ops and cash control ahead of plan.",
      responses: ratedResponses([5, 5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5]),
      objectives: [
        {
          id: "abhi-obj-jane-1",
          title: "Membership ops run-rate",
          description: "Keep renewals and onboarding SLAs green through peak summer.",
          progressPercent: 92,
          dueDate: isoDaysFromNow(25),
          status: "on_track",
          weight: 40,
          owner: JANE.name,
          scope: "employee",
          employeeId: JANE.id,
          employeeName: JANE.name,
          department: JANE.department,
        },
        {
          id: "abhi-obj-jane-2",
          title: "Events budget control",
          description: "Hold WHX pavilion costs within board envelope.",
          progressPercent: 78,
          dueDate: isoDaysFromNow(40),
          status: "on_track",
          weight: 35,
          owner: JANE.name,
          scope: "employee",
          employeeId: JANE.id,
          employeeName: JANE.name,
          department: JANE.department,
        },
      ],
      competencies: competencies([5, 5, 4, 5, 5, 4, 4, 5, 5, 5], "abhi-comp-jane"),
      developmentPlan: [
        {
          id: "abhi-dev-jane-1",
          focus: "Board reporting",
          action: "Lead Q3 board pack with clearer membership cohort narrative",
          owner: JANE.name,
          targetDate: isoDaysFromNow(55),
          status: "in_progress",
          kind: "stretch",
          budget: "£1,200",
          nextReviewDate: isoDaysFromNow(20),
        },
      ],
      createdAt: isoDaysFromNow(-35),
      updatedAt: isoDaysFromNow(-2),
      submittedAt: isoDaysFromNow(-2),
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(4),
      challenges: "Concurrent WHX Johannesburg and GHE Riyadh planning.",
      achievements: "Cash retained at £4.24m; membership at 379 companies.",
      employeeSelfAssessment: "Proud of membership growth — need sharper board storytelling.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: true,
      careerAspirations: "Continue as COO/CFO with stronger international P&L ownership.",
      managerCareerComments: "Clear succession candidate for executive leadership continuity.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "abhi-rev-judith",
      employeeId: JUDITH.id,
      employeeName: JUDITH.name,
      department: JUDITH.department,
      role: JUDITH.role,
      managerName: PETER.name,
      reviewPeriod: "Q3 2026",
      status: "draft",
      overallRating: null,
      strengths: "",
      areasForImprovement: "",
      trainingRecommendations: "NHS commercial pathways masterclass",
      promotionRecommendation: null,
      salaryReviewRecommendation: null,
      managerRecommendation: "develop",
      employeeGoals: "",
      nextReviewDate: isoDaysFromNow(12),
      summary: "",
      responses: blankQuestionResponses(),
      objectives: [
        {
          id: "abhi-obj-judith-1",
          title: "UK Market Affairs working group cadence",
          description: "Deliver monthly member group meetings with ≥80% attendance.",
          progressPercent: 58,
          dueDate: isoDaysFromNow(18),
          status: "at_risk",
          weight: 45,
          owner: JUDITH.name,
          scope: "employee",
          employeeId: JUDITH.id,
          employeeName: JUDITH.name,
          department: JUDITH.department,
        },
      ],
      competencies: competencies([3, 4, 4, 3, 4, 4, 3, 4, 3, 4], "abhi-comp-judith"),
      developmentPlan: [
        {
          id: "abhi-dev-judith-1",
          focus: "Stakeholder facilitation",
          action: "Shadow Luella on Value & Access member briefings",
          owner: "Luella Trickett",
          targetDate: isoDaysFromNow(40),
          status: "planned",
          kind: "mentoring",
          budget: "£0",
          nextReviewDate: isoDaysFromNow(14),
        },
      ],
      createdAt: isoDaysFromNow(-8),
      updatedAt: isoDaysFromNow(-1),
      submittedAt: null,
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(6),
      challenges: "Member diary conflicts for September group meetings.",
      achievements: "",
      employeeSelfAssessment: "",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Associate Director, UK Market Affairs.",
      managerCareerComments: "Needs coaching through working-group attendance recovery.",
      signedOffManager: false,
      signedOffEmployee: false,
    },
    {
      id: "abhi-rev-michelle",
      employeeId: MICHELLE.id,
      employeeName: MICHELLE.name,
      department: MICHELLE.department,
      role: MICHELLE.role,
      managerName: "Paul Benton",
      reviewPeriod: "H1 2026",
      status: "approved",
      overallRating: 5,
      strengths: "Exceptional pavilion delivery and exhibitor relationship management.",
      areasForImprovement: "Earlier supplier lock-in for international freight.",
      trainingRecommendations: "International exhibition logistics certification",
      promotionRecommendation: "yes",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals: "Secure WHX Dubai 2027 UK pavilion bookings and exhibitor pipeline.",
      nextReviewDate: isoDaysFromNow(95),
      summary: "Standout events leadership — promotion-ready.",
      responses: ratedResponses([5, 5, 4, 5, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5, 5, 4, 5]),
      objectives: [
        {
          id: "abhi-obj-michelle-1",
          title: "WHX Johannesburg pavilion ready",
          description: "Shell scheme, lighting, and exhibitor packs locked for Oct 2026.",
          progressPercent: 86,
          dueDate: isoDaysFromNow(35),
          status: "on_track",
          weight: 50,
          owner: MICHELLE.name,
          scope: "employee",
          employeeId: MICHELLE.id,
          employeeName: MICHELLE.name,
          department: MICHELLE.department,
        },
      ],
      competencies: competencies([5, 5, 4, 5, 5, 5, 4, 5, 4, 4], "abhi-comp-michelle"),
      developmentPlan: [
        {
          id: "abhi-dev-michelle-1",
          focus: "Logistics",
          action: "Complete international exhibition logistics certification",
          owner: MICHELLE.name,
          targetDate: isoDaysFromNow(80),
          status: "planned",
          kind: "certification",
          budget: "£1,800",
          nextReviewDate: isoDaysFromNow(30),
        },
      ],
      createdAt: isoDaysFromNow(-45),
      updatedAt: isoDaysFromNow(-5),
      submittedAt: isoDaysFromNow(-12),
      approvedAt: isoDaysFromNow(-5),
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(2),
      challenges: "Freight lead times into Africa and MENA.",
      achievements: "Hospitalar and WHX Tech exhibitor interest ahead of last cycle.",
      employeeSelfAssessment: "Ready for broader international events remit.",
      careerPotential: "high",
      promotionReady: "now",
      successionCandidate: true,
      careerAspirations: "Director of International Events.",
      managerCareerComments: "Promotion candidate — retain with stretch ownership of Dubai 2027.",
      signedOffManager: true,
      signedOffEmployee: false,
    },
    {
      id: "abhi-rev-rebecca",
      employeeId: REBECCA.id,
      employeeName: REBECCA.name,
      department: REBECCA.department,
      role: REBECCA.role,
      managerName: ANDREW.name,
      reviewPeriod: "H1 2026",
      status: "completed",
      overallRating: 4,
      strengths: "Clear digital health policy insight and member engagement.",
      areasForImprovement: "Delegate more working-group preparation.",
      trainingRecommendations: "AI in HealthTech regulation briefing series",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "retain",
      employeeGoals: "Grow Digital Health Group participation and publish two policy notes.",
      nextReviewDate: isoDaysFromNow(160),
      summary: "Strong half — reliable digital health lead.",
      responses: ratedResponses([4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4]),
      objectives: [
        {
          id: "abhi-obj-rebecca-1",
          title: "Digital Health Group engagement",
          description: "Average 40+ members per meeting through Q3.",
          progressPercent: 100,
          dueDate: isoDaysFromNow(-10),
          status: "completed",
          weight: 40,
          owner: REBECCA.name,
          scope: "employee",
          employeeId: REBECCA.id,
          employeeName: REBECCA.name,
          department: REBECCA.department,
        },
      ],
      competencies: competencies([4, 5, 4, 4, 4, 4, 5, 4, 4, 4], "abhi-comp-rebecca"),
      developmentPlan: [
        {
          id: "abhi-dev-rebecca-1",
          focus: "AI regulation",
          action: "Complete AI in HealthTech regulation briefing series",
          owner: REBECCA.name,
          targetDate: isoDaysFromNow(70),
          status: "in_progress",
          kind: "training",
          budget: "£900",
          nextReviewDate: isoDaysFromNow(25),
        },
      ],
      createdAt: isoDaysFromNow(-120),
      updatedAt: isoDaysFromNow(-15),
      submittedAt: isoDaysFromNow(-40),
      approvedAt: isoDaysFromNow(-30),
      completedAt: isoDaysFromNow(-15),
      reviewType: "quarterly",
      priority: "medium",
      dueDate: isoDaysFromNow(-15),
      challenges: "Balancing policy depth with event calendar load.",
      achievements: "Two digital health policy notes published and well received.",
      employeeSelfAssessment: "Want more stretch on AI regulation workstreams.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: true,
      careerAspirations: "Director-level digital health leadership.",
      managerCareerComments: "Strong succession option behind Andrew.",
      signedOffManager: true,
      signedOffEmployee: true,
    },
    {
      id: "abhi-rev-sophie",
      employeeId: SOPHIE.id,
      employeeName: SOPHIE.name,
      department: SOPHIE.department,
      role: SOPHIE.role,
      managerName: "Paul Benton",
      reviewPeriod: "Q3 2026",
      status: "submitted",
      overallRating: 4,
      strengths: "US Accelerator cohort energy and member conversion.",
      areasForImprovement: "Earlier risk flags on mission logistics.",
      trainingRecommendations: "Trade mission programme management",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "develop",
      employeeGoals: "Deliver US Accelerator East Coast Mission with 12 member companies.",
      nextReviewDate: isoDaysFromNow(70),
      summary: "Solid accelerator delivery — coaching on logistics risk.",
      responses: ratedResponses([4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4]),
      objectives: [
        {
          id: "abhi-obj-sophie-1",
          title: "US Accelerator East Coast Mission",
          description: "Confirm 12 member companies and itinerary for late September.",
          progressPercent: 61,
          dueDate: isoDaysFromNow(22),
          status: "at_risk",
          weight: 50,
          owner: SOPHIE.name,
          scope: "employee",
          employeeId: SOPHIE.id,
          employeeName: SOPHIE.name,
          department: SOPHIE.department,
        },
      ],
      competencies: competencies([4, 4, 3, 4, 4, 4, 4, 3, 4, 3], "abhi-comp-sophie"),
      developmentPlan: [
        {
          id: "abhi-dev-sophie-1",
          focus: "Programme management",
          action: "Trade mission programme management course",
          owner: SOPHIE.name,
          targetDate: isoDaysFromNow(60),
          status: "planned",
          kind: "training",
          budget: "£1,400",
          nextReviewDate: isoDaysFromNow(20),
        },
      ],
      createdAt: isoDaysFromNow(-18),
      updatedAt: isoDaysFromNow(-3),
      submittedAt: isoDaysFromNow(-3),
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(3),
      challenges: "Visa and venue holds for East Coast itinerary.",
      achievements: "Strong member interest for US Accelerator cohort.",
      employeeSelfAssessment: "Need earlier logistics checkpoints.",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Head of Accelerators.",
      managerCareerComments: "Good coaching candidate — logistics discipline is the gap.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "abhi-rev-owain",
      employeeId: OWAIN.id,
      employeeName: OWAIN.name,
      department: OWAIN.department,
      role: OWAIN.role,
      managerName: "Luella Trickett",
      reviewPeriod: "Q3 2026",
      status: "draft",
      overallRating: null,
      strengths: "",
      areasForImprovement: "",
      trainingRecommendations: "NICE / procurement pathways clinic",
      promotionRecommendation: null,
      salaryReviewRecommendation: null,
      managerRecommendation: "develop",
      employeeGoals: "",
      nextReviewDate: isoDaysFromNow(20),
      summary: "",
      responses: blankQuestionResponses(),
      objectives: [
        {
          id: "abhi-obj-owain-1",
          title: "Market access member briefings",
          description: "Deliver three member briefings on NHS commercial routes.",
          progressPercent: 40,
          dueDate: isoDaysFromNow(28),
          status: "at_risk",
          weight: 40,
          owner: OWAIN.name,
          scope: "employee",
          employeeId: OWAIN.id,
          employeeName: OWAIN.name,
          department: OWAIN.department,
        },
      ],
      competencies: competencies([3, 3, 3, 4, 3, 4, 3, 3, 3, 3], "abhi-comp-owain"),
      developmentPlan: [
        {
          id: "abhi-dev-owain-1",
          focus: "Market access",
          action: "NICE / procurement pathways clinic",
          owner: OWAIN.name,
          targetDate: isoDaysFromNow(50),
          status: "planned",
          kind: "training",
          budget: "£750",
          nextReviewDate: isoDaysFromNow(15),
        },
      ],
      createdAt: isoDaysFromNow(-5),
      updatedAt: isoDaysFromNow(0),
      submittedAt: null,
      approvedAt: null,
      completedAt: null,
      reviewType: "probation",
      priority: "medium",
      dueDate: isoDaysFromNow(9),
      challenges: "Still ramping after sick leave.",
      achievements: "",
      employeeSelfAssessment: "",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Senior Market Access Manager.",
      managerCareerComments: "Needs structured coaching through probation close-out.",
      signedOffManager: false,
      signedOffEmployee: false,
    },
    {
      id: "abhi-rev-phil",
      employeeId: PHIL.id,
      employeeName: PHIL.name,
      department: PHIL.department,
      role: PHIL.role,
      managerName: PETER.name,
      reviewPeriod: "FY 2025/26",
      status: "completed",
      overallRating: 5,
      strengths: "Authoritative regulatory leadership across MD and IVD groups.",
      areasForImprovement: "Broader delegation to group chairs.",
      trainingRecommendations: "MDSAP readiness leadership forum",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals: "Lead MDSAP membership briefing series for UK HealthTech.",
      nextReviewDate: isoDaysFromNow(180),
      summary: "Outstanding regulatory year for ABHI members.",
      responses: ratedResponses([5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 5, 5, 5, 4]),
      objectives: [
        {
          id: "abhi-obj-phil-1",
          title: "MD Regulatory Group delivery",
          description: "Full annual calendar of member-only regulatory sessions.",
          progressPercent: 100,
          dueDate: isoDaysFromNow(-20),
          status: "completed",
          weight: 45,
          owner: PHIL.name,
          scope: "employee",
          employeeId: PHIL.id,
          employeeName: PHIL.name,
          department: PHIL.department,
        },
      ],
      competencies: competencies([5, 5, 5, 5, 4, 4, 4, 5, 4, 5], "abhi-comp-phil"),
      developmentPlan: [
        {
          id: "abhi-dev-phil-1",
          focus: "MDSAP",
          action: "Lead MDSAP membership meaning briefings",
          owner: PHIL.name,
          targetDate: isoDaysFromNow(45),
          status: "in_progress",
          kind: "stretch",
          budget: "£600",
          nextReviewDate: isoDaysFromNow(20),
        },
      ],
      createdAt: isoDaysFromNow(-200),
      updatedAt: isoDaysFromNow(-40),
      submittedAt: isoDaysFromNow(-60),
      approvedAt: isoDaysFromNow(-50),
      completedAt: isoDaysFromNow(-40),
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(-40),
      challenges: "High member demand for MHRA / UKCA clarity.",
      achievements: "MDSAP briefing series launched; Legal Issues Group well attended.",
      employeeSelfAssessment: "Want more capacity via group-chair delegation.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: true,
      careerAspirations: "Continue as regulatory lead with broader Europe remit.",
      managerCareerComments: "High performer — key succession for regulatory leadership.",
      signedOffManager: true,
      signedOffEmployee: true,
    },
    {
      id: "abhi-rev-charlotte",
      employeeId: CHARLOTTE.id,
      employeeName: CHARLOTTE.name,
      department: CHARLOTTE.department,
      role: CHARLOTTE.role,
      managerName: "Jonathan Evans",
      reviewPeriod: "Q3 2026",
      status: "submitted",
      overallRating: 3,
      strengths: "Reliable event support and member communications turnaround.",
      areasForImprovement: "Proactive planning for multi-event weeks.",
      trainingRecommendations: "Project planning for events; copywriting clinic",
      promotionRecommendation: "no",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "performance_plan",
      employeeGoals: "Own communications pack for two international events end-to-end.",
      nextReviewDate: isoDaysFromNow(45),
      summary: "Needs structured performance plan through autumn events.",
      responses: ratedResponses([3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
      objectives: [
        {
          id: "abhi-obj-charlotte-1",
          title: "Event communications packs",
          description: "Deliver on-time packs for WHX Johannesburg and GHE Riyadh.",
          progressPercent: 35,
          dueDate: isoDaysFromNow(30),
          status: "at_risk",
          weight: 50,
          owner: CHARLOTTE.name,
          scope: "employee",
          employeeId: CHARLOTTE.id,
          employeeName: CHARLOTTE.name,
          department: CHARLOTTE.department,
        },
      ],
      competencies: competencies([3, 3, 3, 3, 4, 3, 3, 3, 3, 3], "abhi-comp-charlotte"),
      developmentPlan: [
        {
          id: "abhi-dev-charlotte-1",
          focus: "Planning",
          action: "Weekly coaching with Jonathan on event comms critical path",
          owner: "Jonathan Evans",
          targetDate: isoDaysFromNow(35),
          status: "in_progress",
          kind: "coaching",
          budget: "£0",
          nextReviewDate: isoDaysFromNow(7),
        },
        {
          id: "abhi-dev-charlotte-2",
          focus: "Copywriting",
          action: "Copywriting clinic for member communications",
          owner: CHARLOTTE.name,
          targetDate: isoDaysFromNow(55),
          status: "planned",
          kind: "training",
          budget: "£450",
          nextReviewDate: isoDaysFromNow(20),
        },
      ],
      createdAt: isoDaysFromNow(-10),
      updatedAt: isoDaysFromNow(-1),
      submittedAt: isoDaysFromNow(-1),
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(5),
      challenges: "Overloaded across concurrent event weeks.",
      achievements: "Supported Sustainability Conference assets on time.",
      employeeSelfAssessment: "Need clearer prioritisation help.",
      careerPotential: "low",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Senior Communications Executive.",
      managerCareerComments: "On a short performance plan — coaching weekly.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
  ];
}

export function buildAbhiPerformanceGoals(): HrPerformanceObjective[] {
  return [
    {
      id: "abhi-goal-org-1",
      title: "Grow membership to 400 companies",
      description: "Net new HealthTech members through UK & international channels.",
      progressPercent: 82,
      dueDate: isoDaysFromNow(120),
      status: "on_track",
      weight: 30,
      owner: "Leadership",
      scope: "organisation",
      department: "Organisation",
      employeeId: null,
    },
    {
      id: "abhi-goal-org-2",
      title: "International events surplus",
      description: "Deliver positive contribution from WHX / Hospitalar pavilion programme.",
      progressPercent: 54,
      dueDate: isoDaysFromNow(150),
      status: "at_risk",
      weight: 25,
      owner: "International Events",
      scope: "organisation",
      department: "Organisation",
      employeeId: null,
    },
    {
      id: "abhi-goal-dept-1",
      title: "Regulatory group attendance ≥ 80%",
      description: "Member-only MD / IVD / Legal group average attendance.",
      progressPercent: 71,
      dueDate: isoDaysFromNow(60),
      status: "on_track",
      weight: 25,
      owner: PHIL.name,
      scope: "department",
      department: "Regulatory",
      employeeId: null,
    },
    {
      id: "abhi-goal-dept-2",
      title: "Digital Health policy notes",
      description: "Publish four member-facing digital health policy notes in 2026.",
      progressPercent: 50,
      dueDate: isoDaysFromNow(90),
      status: "on_track",
      weight: 20,
      owner: ANDREW.name,
      scope: "department",
      department: "Digital Health",
      employeeId: null,
    },
    {
      id: "abhi-goal-dept-3",
      title: "US & ME Accelerator cohorts",
      description: "Fill East Coast and Middle East accelerator cohorts.",
      progressPercent: 48,
      dueDate: isoDaysFromNow(50),
      status: "at_risk",
      weight: 25,
      owner: "Paul Benton",
      scope: "department",
      department: "International",
      employeeId: null,
    },
  ];
}
