/**
 * CorpCentre-only HR Performance fixtures — current AU employees only.
 */
import {
  blankCompetencyScores,
  blankQuestionResponses,
  type HrPerformanceObjective,
  type HrPerformanceReview,
} from "@/lib/hr-performance-data";

function isoDaysFromNow(offset: number) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

const PETER = {
  id: "cc-emp-peter-durning",
  name: "Peter Durning",
  role: "Managing Director",
  department: "Leadership",
};
const DANIEL = {
  id: "cc-emp-daniel-sazdanoff",
  name: "Daniel Sazdanoff",
  role: "Operations Director",
  department: "Leadership",
};
const JOHN = {
  id: "cc-emp-john-amoroso",
  name: "John Amoroso",
  role: "IT Technician",
  department: "IT",
};
const ELIAS = {
  id: "cc-emp-elias-bahbah",
  name: "Elias Bahbah",
  role: "IT Technician",
  department: "IT",
};
const MICK = {
  id: "cc-emp-mick-lenton",
  name: "Mick Lenton",
  role: "IT Technician",
  department: "IT",
};

export function buildCorpCentrePerformanceReviews(): HrPerformanceReview[] {
  return [
    {
      id: "cc-rev-daniel",
      employeeId: DANIEL.id,
      employeeName: DANIEL.name,
      department: DANIEL.department,
      role: DANIEL.role,
      managerName: PETER.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 5,
      strengths: "Delivery ownership across managed IT programmes and client escalations.",
      areasForImprovement: "Protect focus time during concurrent programme peaks.",
      trainingRecommendations: "Advanced consulting leadership programme",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals:
        "Lead two cross-functional delivery programmes and mentor technicians to independent ownership.",
      nextReviewDate: isoDaysFromNow(120),
      summary: "Strong half — AU client delivery targets exceeded.",
      responses: blankQuestionResponses().map((item, index) => ({
        ...item,
        rating: ([5, 4, 5, 4, 5, 4, 4, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 4, 5, 4][index] ??
          4) as 1 | 2 | 3 | 4 | 5,
        managerComments: index % 5 === 0 ? "Consistently strong." : "",
        employeeComments: index % 7 === 0 ? "Agree — focusing here next quarter." : "",
      })),
      objectives: [
        {
          id: "cc-obj-d1",
          title: "Stabilise client SLA ≥ 98%",
          description: "Hold on-time managed service readiness for AU clients.",
          progressPercent: 94,
          dueDate: isoDaysFromNow(20),
          status: "on_track",
          weight: 40,
          owner: DANIEL.name,
          scope: "employee",
          employeeId: DANIEL.id,
          employeeName: DANIEL.name,
          department: DANIEL.department,
        },
        {
          id: "cc-obj-d2",
          title: "Mentor John & Elias",
          description: "Documented mentoring plan and monthly check-ins.",
          progressPercent: 72,
          dueDate: isoDaysFromNow(45),
          status: "on_track",
          weight: 30,
          owner: DANIEL.name,
          scope: "employee",
          employeeId: DANIEL.id,
          employeeName: DANIEL.name,
          department: DANIEL.department,
        },
      ],
      competencies: blankCompetencyScores().map((item, index) => ({
        ...item,
        id: `cc-comp-d-${index}`,
        score: ([5, 4, 5, 5, 4, 4, 4, 5, 4, 4][index] ?? 4) as 1 | 2 | 3 | 4 | 5,
        notes: index === 0 ? "Trusted by the leadership team" : "",
      })),
      developmentPlan: [
        {
          id: "cc-dev-d1",
          focus: "Delegation & leadership",
          action: "Shadow Peter on weekly priority triage",
          owner: DANIEL.name,
          targetDate: isoDaysFromNow(60),
          status: "in_progress",
          kind: "coaching",
          budget: "AU$1,200",
          nextReviewDate: isoDaysFromNow(30),
        },
        {
          id: "cc-dev-d2",
          focus: "People leadership",
          action: "Complete advanced consulting leadership programme",
          owner: "HR L&D",
          targetDate: isoDaysFromNow(90),
          status: "planned",
          kind: "training",
          budget: "AU$2,400",
          nextReviewDate: isoDaysFromNow(45),
        },
      ],
      createdAt: isoDaysFromNow(-40),
      updatedAt: isoDaysFromNow(-3),
      submittedAt: isoDaysFromNow(-3),
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(5),
      challenges: "Capacity pressure during peak client onboardings.",
      achievements: "Recovered SLA from 91% to 98% in eight weeks.",
      employeeSelfAssessment:
        "Proud of the SLA recovery. Need more structured delegation.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: true,
      careerAspirations: "COO track within 18–24 months.",
      managerCareerComments: "Strong succession candidate for operations leadership.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "cc-rev-john",
      employeeId: JOHN.id,
      employeeName: JOHN.name,
      department: JOHN.department,
      role: JOHN.role,
      managerName: DANIEL.name,
      reviewPeriod: "Q3 2026",
      status: "draft",
      overallRating: null,
      strengths: "",
      areasForImprovement: "",
      trainingRecommendations: "Cisco / Fortinet advanced routing; change-management clinic",
      promotionRecommendation: null,
      salaryReviewRecommendation: null,
      managerRecommendation: "develop",
      employeeGoals: "",
      nextReviewDate: isoDaysFromNow(14),
      summary: "",
      responses: blankQuestionResponses(),
      objectives: [
        {
          id: "cc-obj-j1",
          title: "Complete Sydney LAN refresh cutover",
          description: "Finish core switch and Wi-Fi validation weekends.",
          progressPercent: 55,
          dueDate: isoDaysFromNow(10),
          status: "at_risk",
          weight: 50,
          owner: JOHN.name,
          scope: "employee",
          employeeId: JOHN.id,
          employeeName: JOHN.name,
          department: JOHN.department,
        },
      ],
      competencies: blankCompetencyScores().map((item, index) => ({
        ...item,
        id: `cc-comp-j-${index}`,
        score: ([3, 4, 4, 3, 4, 3, 3, 4, 3, 3][index] ?? 3) as 1 | 2 | 3 | 4 | 5,
      })),
      developmentPlan: [
        {
          id: "cc-dev-j1",
          focus: "Network architecture",
          action: "Pair with Daniel on PoP expansion design reviews",
          owner: DANIEL.name,
          targetDate: isoDaysFromNow(45),
          status: "in_progress",
          kind: "mentoring",
          budget: "AU$0",
          nextReviewDate: isoDaysFromNow(14),
        },
      ],
      createdAt: isoDaysFromNow(-7),
      updatedAt: isoDaysFromNow(-1),
      submittedAt: null,
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "high",
      dueDate: isoDaysFromNow(7),
      challenges: "Behind on LAN cutover windows.",
      achievements: "",
      employeeSelfAssessment: "",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Senior network engineer track.",
      managerCareerComments: "Needs coaching through cutover milestones.",
      signedOffManager: false,
      signedOffEmployee: false,
    },
    {
      id: "cc-rev-elias",
      employeeId: ELIAS.id,
      employeeName: ELIAS.name,
      department: ELIAS.department,
      role: ELIAS.role,
      managerName: DANIEL.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 4,
      strengths: "Reliable endpoint support and client-facing calm under pressure.",
      areasForImprovement: "Document runbooks for recurring incidents.",
      trainingRecommendations: "ITIL foundation; Azure admin fundamentals",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "develop",
      employeeGoals: "Own the Sydney helpdesk queue SLAs and publish three runbooks.",
      nextReviewDate: isoDaysFromNow(90),
      summary: "Solid contributor — ready for more ownership.",
      responses: blankQuestionResponses().map((item, index) => ({
        ...item,
        rating: ([4, 4, 4, 3, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 4, 3][index] ??
          4) as 1 | 2 | 3 | 4 | 5,
      })),
      objectives: [
        {
          id: "cc-obj-e1",
          title: "Helpdesk first-response ≤ 15m",
          description: "Hold median first response under 15 minutes for P2 tickets.",
          progressPercent: 81,
          dueDate: isoDaysFromNow(25),
          status: "on_track",
          weight: 40,
          owner: ELIAS.name,
          scope: "employee",
          employeeId: ELIAS.id,
          employeeName: ELIAS.name,
          department: ELIAS.department,
        },
      ],
      competencies: blankCompetencyScores().map((item, index) => ({
        ...item,
        id: `cc-comp-e-${index}`,
        score: ([4, 4, 3, 4, 4, 4, 3, 4, 4, 3][index] ?? 4) as 1 | 2 | 3 | 4 | 5,
      })),
      developmentPlan: [
        {
          id: "cc-dev-e1",
          focus: "Service management",
          action: "Complete ITIL Foundation",
          owner: ELIAS.name,
          targetDate: isoDaysFromNow(70),
          status: "planned",
          kind: "certification",
          budget: "AU$1,100",
          nextReviewDate: isoDaysFromNow(35),
        },
      ],
      createdAt: isoDaysFromNow(-20),
      updatedAt: isoDaysFromNow(-2),
      submittedAt: isoDaysFromNow(-2),
      approvedAt: null,
      completedAt: null,
      reviewType: "quarterly",
      priority: "medium",
      dueDate: isoDaysFromNow(4),
      challenges: "Ticket spikes during client onboardings.",
      achievements: "Cleared backlog of 40 aged tickets in June.",
      employeeSelfAssessment: "Want more ownership of runbooks and onboarding kits.",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Service desk lead.",
      managerCareerComments: "Good coaching candidate for lead technician path.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "cc-rev-mick",
      employeeId: MICK.id,
      employeeName: MICK.name,
      department: MICK.department,
      role: MICK.role,
      managerName: DANIEL.name,
      reviewPeriod: "FY 2025",
      status: "completed",
      overallRating: 4,
      strengths: "Security hygiene and pragmatic field delivery.",
      areasForImprovement: "Written handover quality after site visits.",
      trainingRecommendations: "Zero-trust fundamentals; report writing workshop",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals: "Lead endpoint hardening rollout and lift field visit close-out quality.",
      nextReviewDate: isoDaysFromNow(180),
      summary: "Reliable year — key contributor to hardening programme.",
      responses: blankQuestionResponses().map((item) => ({
        ...item,
        rating: 4 as const,
        managerComments: "",
        employeeComments: "",
      })),
      objectives: [
        {
          id: "cc-obj-m1",
          title: "Endpoint compliance ≥ 95%",
          description: "Device compliance across CorpCentre fleet.",
          progressPercent: 100,
          dueDate: isoDaysFromNow(-30),
          status: "completed",
          weight: 40,
          owner: MICK.name,
          scope: "employee",
          employeeId: MICK.id,
          employeeName: MICK.name,
          department: MICK.department,
        },
      ],
      competencies: blankCompetencyScores().map((item, index) => ({
        ...item,
        id: `cc-comp-m-${index}`,
        score: ([4, 4, 4, 5, 4, 4, 3, 4, 4, 4][index] ?? 4) as 1 | 2 | 3 | 4 | 5,
      })),
      developmentPlan: [
        {
          id: "cc-dev-m1",
          focus: "Security",
          action: "Complete zero-trust fundamentals course",
          owner: MICK.name,
          targetDate: isoDaysFromNow(60),
          status: "planned",
          kind: "training",
          budget: "AU$900",
          nextReviewDate: isoDaysFromNow(90),
        },
      ],
      createdAt: isoDaysFromNow(-200),
      updatedAt: isoDaysFromNow(-150),
      submittedAt: isoDaysFromNow(-160),
      approvedAt: isoDaysFromNow(-155),
      completedAt: isoDaysFromNow(-150),
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(-150),
      challenges: "Field visit schedule conflicts with hardening windows.",
      achievements: "Fleet compliance lifted from 78% to 96%.",
      employeeSelfAssessment: "Ready for more security ownership.",
      careerPotential: "medium",
      promotionReady: "12_months",
      successionCandidate: false,
      careerAspirations: "Security / compliance technician.",
      managerCareerComments: "Strong retain; consider security stretch next cycle.",
      signedOffManager: true,
      signedOffEmployee: true,
    },
    {
      id: "cc-rev-peter",
      employeeId: PETER.id,
      employeeName: PETER.name,
      department: PETER.department,
      role: PETER.role,
      managerName: "Board",
      reviewPeriod: "FY 2025",
      status: "completed",
      overallRating: 5,
      strengths: "Commercial clarity and decisive leadership for AU growth.",
      areasForImprovement: "Protect calendar for deeper coaching of directors.",
      trainingRecommendations: "Board reporting automation workshop",
      promotionRecommendation: "yes",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals: "Scale CorpCentre managed services and keep cash / margin discipline.",
      nextReviewDate: isoDaysFromNow(180),
      summary: "Outstanding leadership year for CorpCentre.",
      responses: blankQuestionResponses().map((item) => ({
        ...item,
        rating: 5 as const,
      })),
      objectives: [
        {
          id: "cc-obj-p1",
          title: "Grow AU managed revenue",
          description: "Deliver AU$2M professional services revenue run-rate.",
          progressPercent: 100,
          dueDate: isoDaysFromNow(-20),
          status: "completed",
          weight: 50,
          owner: PETER.name,
          scope: "employee",
          employeeId: PETER.id,
          employeeName: PETER.name,
          department: PETER.department,
        },
      ],
      competencies: blankCompetencyScores().map((item, index) => ({
        ...item,
        id: `cc-comp-p-${index}`,
        score: 5 as const,
      })),
      developmentPlan: [
        {
          id: "cc-dev-p1",
          focus: "Board reporting",
          action: "Automate monthly AUD board pack",
          owner: PETER.name,
          targetDate: isoDaysFromNow(75),
          status: "in_progress",
          kind: "stretch",
          budget: "AU$1,500",
          nextReviewDate: isoDaysFromNow(30),
        },
      ],
      createdAt: isoDaysFromNow(-220),
      updatedAt: isoDaysFromNow(-180),
      submittedAt: isoDaysFromNow(-190),
      approvedAt: isoDaysFromNow(-185),
      completedAt: isoDaysFromNow(-180),
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(-180),
      challenges: "Balancing growth with delivery capacity.",
      achievements: "Cash AU$2M retained; leadership team stabilised.",
      employeeSelfAssessment: "Focused on scaling with quality.",
      careerPotential: "high",
      promotionReady: "now",
      successionCandidate: true,
      careerAspirations: "Continue as MD; deepen board operating rhythm.",
      managerCareerComments: "Retain and support with sharper board tooling.",
      signedOffManager: true,
      signedOffEmployee: true,
    },
  ];
}

export function buildCorpCentrePerformanceGoals(): HrPerformanceObjective[] {
  return [
    {
      id: "cc-goal-org-1",
      title: "Client NPS ≥ 60",
      description: "Lift CorpCentre NPS through managed service reliability.",
      progressPercent: 74,
      dueDate: isoDaysFromNow(90),
      status: "on_track",
      weight: 25,
      owner: "Leadership",
      scope: "organisation",
      department: "Organisation",
      employeeId: null,
    },
    {
      id: "cc-goal-org-2",
      title: "Gross margin improvement",
      description: "Improve contribution margin by 3pts vs prior year (AUD).",
      progressPercent: 48,
      dueDate: isoDaysFromNow(120),
      status: "at_risk",
      weight: 25,
      owner: "Finance",
      scope: "organisation",
      department: "Organisation",
      employeeId: null,
    },
    {
      id: "cc-goal-dept-1",
      title: "Operations readiness ≥ 98%",
      description: "Department SLA for managed service readiness.",
      progressPercent: 96,
      dueDate: isoDaysFromNow(30),
      status: "on_track",
      weight: 30,
      owner: DANIEL.name,
      scope: "department",
      department: "Leadership",
      employeeId: null,
    },
    {
      id: "cc-goal-dept-2",
      title: "IT change success ≥ 97%",
      description: "Reduce failed change windows on client networks.",
      progressPercent: 63,
      dueDate: isoDaysFromNow(45),
      status: "at_risk",
      weight: 30,
      owner: JOHN.name,
      scope: "department",
      department: "IT",
      employeeId: null,
    },
    {
      id: "cc-goal-emp-1",
      title: "Endpoint compliance ≥ 95%",
      description: "Device compliance across CorpCentre fleet.",
      progressPercent: 88,
      dueDate: isoDaysFromNow(40),
      status: "on_track",
      weight: 20,
      owner: MICK.name,
      scope: "employee",
      department: "IT",
      employeeId: MICK.id,
      employeeName: MICK.name,
    },
  ];
}
