import type { PortfolioProject } from "@/lib/project-portfolios";

function project(
  partial: Omit<PortfolioProject, "createdAt" | "updatedAt"> & {
    createdAt?: string;
    updatedAt?: string;
  },
): PortfolioProject {
  return {
    createdAt: partial.createdAt ?? "2026-01-15T09:00:00.000Z",
    updatedAt: partial.updatedAt ?? "2026-07-20T14:30:00.000Z",
    ...partial,
  };
}

/**
 * CorpCentre-only Internal Projects portfolio — AU locations, AUD budgets.
 * Shown on projects-internal for corpcentre.unit311central.com.
 */
export const CORPCENTRE_INTERNAL_PROJECT_PORTFOLIO: PortfolioProject[] = [
  project({
    id: "cc-int-crm-refresh",
    kind: "internal",
    name: "CRM & Pipeline Refresh",
    clientId: null,
    clientName: "Business Central",
    department: "Business Central",
    site: "Sydney HQ · Commercial Systems",
    region: "NSW · Group Commercial",
    operator: "Daniel Sazdanoff",
    projectManager: "Daniel Sazdanoff",
    phase: "live",
    startDate: "2026-02-10",
    endDate: "2026-10-31",
    progressPct: 62,
    budgetLabel: "AU$185,000",
    stakeholders: ["Peter", "Sales Ops", "IT Security"],
    notes: "Unify pipeline, discovery and client onboarding for CorpCentre AU.",
    milestones: [
      { id: "m1", name: "Discovery complete", dueDate: "2026-03-15", status: "done" },
      { id: "m2", name: "Sandbox cutover", dueDate: "2026-06-01", status: "done" },
      { id: "m3", name: "Production migration", dueDate: "2026-09-15", status: "upcoming" },
      { id: "m4", name: "Hypercare close", dueDate: "2026-10-31", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Legacy lead field mapping gaps",
        severity: "medium",
        owner: "Daniel Sazdanoff",
      },
    ],
  }),
  project({
    id: "cc-int-hris-rollout",
    kind: "internal",
    name: "HRIS Payroll Rollout",
    clientId: null,
    clientName: "Human Resources",
    department: "Human Resources",
    site: "People Systems · Cloud",
    region: "NSW · People Ops",
    operator: "Elias CorpCentre",
    projectManager: "Elias CorpCentre",
    phase: "live",
    startDate: "2026-01-20",
    endDate: "2026-08-30",
    progressPct: 71,
    budgetLabel: "AU$142,000",
    stakeholders: ["Peter", "Payroll", "Finance"],
    notes: "AUD payroll, leave and benefits self-service for CorpCentre staff.",
    milestones: [
      { id: "m1", name: "Chart of pay codes", dueDate: "2026-02-28", status: "done" },
      { id: "m2", name: "Pilot payroll run", dueDate: "2026-05-15", status: "done" },
      { id: "m3", name: "Full cutover", dueDate: "2026-08-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Superannuation file format changes",
        severity: "low",
        owner: "Elias CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-finance-close",
    kind: "internal",
    name: "Month-End Close Automation",
    clientId: null,
    clientName: "Financials",
    department: "Financials",
    site: "Finance Ops · Sydney",
    region: "NSW · Finance",
    operator: "Peter",
    projectManager: "Peter",
    phase: "live",
    startDate: "2026-03-01",
    endDate: "2026-11-30",
    progressPct: 48,
    budgetLabel: "AU$96,000",
    stakeholders: ["Peter", "CFO advisory", "External accountant"],
    notes: "Automate AUD month-end journals, bank recs and management pack.",
    milestones: [
      { id: "m1", name: "Bank feed mapping", dueDate: "2026-04-30", status: "done" },
      { id: "m2", name: "Close checklist live", dueDate: "2026-07-31", status: "upcoming" },
      { id: "m3", name: "Board pack template", dueDate: "2026-11-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Multi-bank statement timing",
        severity: "medium",
        owner: "Peter",
      },
    ],
  }),
  project({
    id: "cc-int-office-lan",
    kind: "internal",
    name: "Sydney Office LAN Refresh",
    clientId: null,
    clientName: "IT Operations",
    department: "IT Operations",
    site: "Sydney HQ · Floor 12",
    region: "NSW · Infrastructure",
    operator: "John Amoroso",
    projectManager: "John Amoroso",
    phase: "live",
    startDate: "2026-04-01",
    endDate: "2026-09-15",
    progressPct: 55,
    budgetLabel: "AU$210,000",
    stakeholders: ["John Amoroso", "Facilities", "Security"],
    notes: "Replace core switches, Wi-Fi 6E and segmented guest network.",
    milestones: [
      { id: "m1", name: "Hardware ordered", dueDate: "2026-04-20", status: "done" },
      { id: "m2", name: "Core cutover weekend", dueDate: "2026-07-12", status: "upcoming" },
      { id: "m3", name: "Wi-Fi validation", dueDate: "2026-08-30", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "After-hours change window conflict",
        severity: "high",
        owner: "John Amoroso",
      },
    ],
  }),
  project({
    id: "cc-int-iso27001",
    kind: "internal",
    name: "ISO 27001 Readiness",
    clientId: null,
    clientName: "Risk & Compliance",
    department: "Risk & Compliance",
    site: "Group ISMS programme",
    region: "AU · Compliance",
    operator: "Mick CorpCentre",
    projectManager: "Mick CorpCentre",
    phase: "live",
    startDate: "2026-01-08",
    endDate: "2026-12-15",
    progressPct: 41,
    budgetLabel: "AU$128,000",
    stakeholders: ["Peter", "Legal", "IT Security"],
    notes: "Controls mapping, evidence vault and Stage 1 audit for CorpCentre.",
    milestones: [
      { id: "m1", name: "Gap assessment", dueDate: "2026-03-01", status: "done" },
      { id: "m2", name: "Policy pack v1", dueDate: "2026-06-30", status: "done" },
      { id: "m3", name: "Stage 1 audit", dueDate: "2026-11-20", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Vendor SOC2 evidence delays",
        severity: "medium",
        owner: "Mick CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-ea-knowledge",
    kind: "internal",
    name: "Executive Assistant Knowledge Base",
    clientId: null,
    clientName: "Executive Office",
    department: "Executive Office",
    site: "AI Ops · Platform",
    region: "NSW · Leadership",
    operator: "Daniel Sazdanoff",
    projectManager: "Daniel Sazdanoff",
    phase: "live",
    startDate: "2026-02-15",
    endDate: "2026-09-30",
    progressPct: 67,
    budgetLabel: "AU$74,000",
    stakeholders: ["Peter", "EA programme", "IT"],
    notes: "CorpCentre playbooks, briefings and guided learning for the EA.",
    milestones: [
      { id: "m1", name: "Domain corpus", dueDate: "2026-04-01", status: "done" },
      { id: "m2", name: "Pilot with leadership", dueDate: "2026-07-01", status: "done" },
      { id: "m3", name: "GA release", dueDate: "2026-09-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Stale financial snapshot risk",
        severity: "low",
        owner: "Daniel Sazdanoff",
      },
    ],
  }),
  project({
    id: "cc-int-website-cms",
    kind: "internal",
    name: "CorpCentre Website Refresh",
    clientId: null,
    clientName: "Marketing",
    department: "Marketing",
    site: "Brand · Digital",
    region: "NSW · Marketing",
    operator: "Elias CorpCentre",
    projectManager: "Elias CorpCentre",
    phase: "live",
    startDate: "2026-03-10",
    endDate: "2026-10-01",
    progressPct: 39,
    budgetLabel: "AU$88,000",
    stakeholders: ["Peter", "Marketing", "Sales"],
    notes: "AU case studies, managed telco & IT positioning, lead forms.",
    milestones: [
      { id: "m1", name: "IA & copy", dueDate: "2026-05-01", status: "done" },
      { id: "m2", name: "Design system", dueDate: "2026-07-15", status: "upcoming" },
      { id: "m3", name: "Launch", dueDate: "2026-09-20", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Brand asset approval lag",
        severity: "low",
        owner: "Elias CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-onboarding",
    kind: "internal",
    name: "Client Onboarding Playbook",
    clientId: null,
    clientName: "Customer Success",
    department: "Customer Success",
    site: "Service Delivery · AU",
    region: "National · CS",
    operator: "Daniel Sazdanoff",
    projectManager: "Daniel Sazdanoff",
    phase: "live",
    startDate: "2026-02-01",
    endDate: "2026-08-15",
    progressPct: 78,
    budgetLabel: "AU$52,000",
    stakeholders: ["CS leads", "Project managers", "Sales"],
    notes: "Standardise kickoff, RACI and first-90-day health checks.",
    milestones: [
      { id: "m1", name: "Playbook draft", dueDate: "2026-03-20", status: "done" },
      { id: "m2", name: "Pilot 3 clients", dueDate: "2026-06-01", status: "done" },
      { id: "m3", name: "Org-wide rollout", dueDate: "2026-08-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "PM capacity during peak onboardings",
        severity: "medium",
        owner: "Daniel Sazdanoff",
      },
    ],
  }),
  project({
    id: "cc-int-data-warehouse",
    kind: "internal",
    name: "Operations Data Warehouse",
    clientId: null,
    clientName: "IT Operations",
    department: "IT Operations",
    site: "Analytics · Cloud AU",
    region: "NSW · Data",
    operator: "John Amoroso",
    projectManager: "John Amoroso",
    phase: "live",
    startDate: "2026-01-15",
    endDate: "2026-12-01",
    progressPct: 44,
    budgetLabel: "AU$165,000",
    stakeholders: ["Finance", "Ops", "Leadership"],
    notes: "Unified AUD revenue, utilisation and ticket marts for dashboards.",
    milestones: [
      { id: "m1", name: "Source inventory", dueDate: "2026-03-01", status: "done" },
      { id: "m2", name: "Finance mart", dueDate: "2026-07-01", status: "upcoming" },
      { id: "m3", name: "Ops mart", dueDate: "2026-11-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Invoice currency normalisation",
        severity: "medium",
        owner: "John Amoroso",
      },
    ],
  }),
  project({
    id: "cc-int-cyber-hardening",
    kind: "internal",
    name: "Endpoint & Identity Hardening",
    clientId: null,
    clientName: "IT Security",
    department: "IT Security",
    site: "Zero Trust · AU",
    region: "National · Security",
    operator: "Mick CorpCentre",
    projectManager: "Mick CorpCentre",
    phase: "live",
    startDate: "2026-03-01",
    endDate: "2026-09-30",
    progressPct: 53,
    budgetLabel: "AU$119,000",
    stakeholders: ["IT Ops", "Compliance", "Peter"],
    notes: "MFA enforcement, device compliance and privileged access review.",
    milestones: [
      { id: "m1", name: "MFA gap close", dueDate: "2026-04-15", status: "done" },
      { id: "m2", name: "Device compliance", dueDate: "2026-07-01", status: "upcoming" },
      { id: "m3", name: "PAM rollout", dueDate: "2026-09-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Field technician offline MFA friction",
        severity: "high",
        owner: "Mick CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-melbourne-noc",
    kind: "internal",
    name: "Melbourne NOC Fit-Out",
    clientId: null,
    clientName: "Service Delivery",
    department: "Service Delivery",
    site: "Melbourne · Docklands",
    region: "VIC · NOC",
    operator: "John Amoroso",
    projectManager: "John Amoroso",
    phase: "live",
    startDate: "2026-04-15",
    endDate: "2026-11-30",
    progressPct: 36,
    budgetLabel: "AU$320,000",
    stakeholders: ["Facilities", "Network Ops", "Peter"],
    notes: "Secondary monitoring floor for managed telco & IT clients.",
    milestones: [
      { id: "m1", name: "Lease fit-out design", dueDate: "2026-05-30", status: "done" },
      { id: "m2", name: "Circuit handovers", dueDate: "2026-08-15", status: "upcoming" },
      { id: "m3", name: "Go-live", dueDate: "2026-11-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Carrier lead times for dark fibre",
        severity: "high",
        owner: "John Amoroso",
      },
    ],
  }),
  project({
    id: "cc-int-service-catalogue",
    kind: "internal",
    name: "Managed Services Catalogue",
    clientId: null,
    clientName: "Commercial",
    department: "Commercial",
    site: "Product · Pricing",
    region: "National · Commercial",
    operator: "Daniel Sazdanoff",
    projectManager: "Daniel Sazdanoff",
    phase: "live",
    startDate: "2026-02-20",
    endDate: "2026-08-31",
    progressPct: 59,
    budgetLabel: "AU$61,000",
    stakeholders: ["Sales", "Delivery", "Finance"],
    notes: "SKU and AUD price book for managed IT, network and SOC packs.",
    milestones: [
      { id: "m1", name: "SKU taxonomy", dueDate: "2026-04-01", status: "done" },
      { id: "m2", name: "Price book v1", dueDate: "2026-06-15", status: "done" },
      { id: "m3", name: "CRM integration", dueDate: "2026-08-20", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Vendor cost volatility",
        severity: "medium",
        owner: "Daniel Sazdanoff",
      },
    ],
  }),
  project({
    id: "cc-int-qms-lite",
    kind: "internal",
    name: "Quality Management Lite",
    clientId: null,
    clientName: "Operations Excellence",
    department: "Operations Excellence",
    site: "QMS · Process",
    region: "National · Ops",
    operator: "Mick CorpCentre",
    projectManager: "Mick CorpCentre",
    phase: "live",
    startDate: "2026-03-15",
    endDate: "2026-10-15",
    progressPct: 33,
    budgetLabel: "AU$47,000",
    stakeholders: ["Delivery leads", "Compliance"],
    notes: "Lightweight change, incident and CAPA workflows for AU delivery.",
    milestones: [
      { id: "m1", name: "Process map", dueDate: "2026-05-01", status: "done" },
      { id: "m2", name: "Tooling pilot", dueDate: "2026-08-01", status: "upcoming" },
      { id: "m3", name: "Training complete", dueDate: "2026-10-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Adoption vs ticket volume peaks",
        severity: "low",
        owner: "Mick CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-brisbane-hub",
    kind: "internal",
    name: "Brisbane Field Hub Setup",
    clientId: null,
    clientName: "Field Operations",
    department: "Field Operations",
    site: "Brisbane · Fortitude Valley",
    region: "QLD · Field",
    operator: "John Amoroso",
    projectManager: "John Amoroso",
    phase: "live",
    startDate: "2026-05-01",
    endDate: "2026-12-15",
    progressPct: 28,
    budgetLabel: "AU$175,000",
    stakeholders: ["Field leads", "Facilities", "HR"],
    notes: "Regional staging, spare stock and technician hot-desk capacity.",
    milestones: [
      { id: "m1", name: "Site selected", dueDate: "2026-05-20", status: "done" },
      { id: "m2", name: "Fit-out complete", dueDate: "2026-09-30", status: "upcoming" },
      { id: "m3", name: "Stock go-live", dueDate: "2026-12-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Fit-out contractor availability",
        severity: "medium",
        owner: "John Amoroso",
      },
    ],
  }),
  project({
    id: "cc-int-perth-dr",
    kind: "internal",
    name: "Perth DR Warm Site",
    clientId: null,
    clientName: "IT Operations",
    department: "IT Operations",
    site: "Perth · DC pair",
    region: "WA · Resilience",
    operator: "Mick CorpCentre",
    projectManager: "Mick CorpCentre",
    phase: "upcoming",
    startDate: "2026-08-01",
    endDate: "2027-03-31",
    progressPct: 12,
    budgetLabel: "AU$240,000",
    stakeholders: ["IT Ops", "Security", "Finance"],
    notes: "Warm DR capacity for critical managed services east-coast outage.",
    milestones: [
      { id: "m1", name: "Capacity design", dueDate: "2026-09-15", status: "upcoming" },
      { id: "m2", name: "Circuit contracts", dueDate: "2026-11-30", status: "upcoming" },
      { id: "m3", name: "Failover drill", dueDate: "2027-02-28", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Cross-continent latency SLAs",
        severity: "high",
        owner: "Mick CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-learning-lms",
    kind: "internal",
    name: "Staff Learning LMS",
    clientId: null,
    clientName: "Human Resources",
    department: "Human Resources",
    site: "L&D · Cloud",
    region: "National · People",
    operator: "Elias CorpCentre",
    projectManager: "Elias CorpCentre",
    phase: "upcoming",
    startDate: "2026-07-15",
    endDate: "2027-01-31",
    progressPct: 8,
    budgetLabel: "AU$69,000",
    stakeholders: ["HR", "Delivery", "Security"],
    notes: "Mandatory AU compliance modules and role-based technical paths.",
    milestones: [
      { id: "m1", name: "Vendor selection", dueDate: "2026-08-30", status: "upcoming" },
      { id: "m2", name: "Content migration", dueDate: "2026-11-15", status: "upcoming" },
      { id: "m3", name: "Mandatory launch", dueDate: "2027-01-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Content licensing renewal costs",
        severity: "low",
        owner: "Elias CorpCentre",
      },
    ],
  }),
  project({
    id: "cc-int-procurement",
    kind: "internal",
    name: "Vendor Procurement Portal",
    clientId: null,
    clientName: "Procurement",
    department: "Procurement",
    site: "Supply · Finance",
    region: "NSW · Procurement",
    operator: "Peter",
    projectManager: "Peter",
    phase: "upcoming",
    startDate: "2026-09-01",
    endDate: "2027-02-28",
    progressPct: 5,
    budgetLabel: "AU$83,000",
    stakeholders: ["Finance", "IT Ops", "Legal"],
    notes: "AU vendor onboarding, PO workflow and preferred-supplier lists.",
    milestones: [
      { id: "m1", name: "Requirements", dueDate: "2026-10-01", status: "upcoming" },
      { id: "m2", name: "Pilot suppliers", dueDate: "2026-12-15", status: "upcoming" },
      { id: "m3", name: "Org rollout", dueDate: "2027-02-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Finance system integration scope",
        severity: "medium",
        owner: "Peter",
      },
    ],
  }),
  project({
    id: "cc-int-customer-nps",
    kind: "internal",
    name: "Customer NPS Programme",
    clientId: null,
    clientName: "Customer Success",
    department: "Customer Success",
    site: "Voice of Customer",
    region: "National · CS",
    operator: "Daniel Sazdanoff",
    projectManager: "Daniel Sazdanoff",
    phase: "upcoming",
    startDate: "2026-08-15",
    endDate: "2027-01-15",
    progressPct: 10,
    budgetLabel: "AU$38,000",
    stakeholders: ["CS", "Sales", "Delivery"],
    notes: "Quarterly NPS and closed-loop actions across managed clients.",
    milestones: [
      { id: "m1", name: "Survey design", dueDate: "2026-09-15", status: "upcoming" },
      { id: "m2", name: "First wave", dueDate: "2026-11-01", status: "upcoming" },
      { id: "m3", name: "Board scorecard", dueDate: "2027-01-10", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Survey fatigue on large accounts",
        severity: "low",
        owner: "Daniel Sazdanoff",
      },
    ],
  }),
  project({
    id: "cc-int-adelaide-pop",
    kind: "internal",
    name: "Adelaide PoP Expansion",
    clientId: null,
    clientName: "Network Ops",
    department: "Network Ops",
    site: "Adelaide · CBD PoP",
    region: "SA · Network",
    operator: "John Amoroso",
    projectManager: "John Amoroso",
    phase: "live",
    startDate: "2026-04-01",
    endDate: "2026-10-31",
    progressPct: 47,
    budgetLabel: "AU$198,000",
    stakeholders: ["Network", "Finance", "Sales"],
    notes: "Additional PoP capacity for SA managed network clients.",
    milestones: [
      { id: "m1", name: "Rack space secured", dueDate: "2026-05-01", status: "done" },
      { id: "m2", name: "Core routers live", dueDate: "2026-08-15", status: "upcoming" },
      { id: "m3", name: "Customer migration", dueDate: "2026-10-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Power density upgrade delay",
        severity: "medium",
        owner: "John Amoroso",
      },
    ],
  }),
  project({
    id: "cc-int-board-reporting",
    kind: "internal",
    name: "Board Reporting Pack Automation",
    clientId: null,
    clientName: "Executive Office",
    department: "Executive Office",
    site: "Leadership · Reporting",
    region: "NSW · Board",
    operator: "Peter",
    projectManager: "Peter",
    phase: "upcoming",
    startDate: "2026-09-15",
    endDate: "2027-02-15",
    progressPct: 6,
    budgetLabel: "AU$55,000",
    stakeholders: ["Peter", "Finance", "EA"],
    notes: "Automated AUD KPI pack for monthly CorpCentre board meetings.",
    milestones: [
      { id: "m1", name: "KPI dictionary", dueDate: "2026-10-15", status: "upcoming" },
      { id: "m2", name: "Template build", dueDate: "2026-12-01", status: "upcoming" },
      { id: "m3", name: "First automated pack", dueDate: "2027-02-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Source system refresh cadence",
        severity: "medium",
        owner: "Peter",
      },
    ],
  }),
];
