import type {
  ModelTestingEvidenceImage,
  WolfBenchmarkVideoRecord,
  WolfModelTestingRecord,
} from "@/lib/wolf/wolf-mission2-model-testing-arch-types";

/** Bump when Mission 2 seed model/video metadata changes. */
export const WOLF_MISSION2_MODEL_TESTING_ARCH_SEED_VERSION = 2;

function evidenceNote(repositoryPath: string, label: string): ModelTestingEvidenceImage {
  return {
    kind: "detector_output",
    label,
    url: null,
    repositoryPath,
  };
}

export const WOLF_MISSION2_MODEL_TESTING_ARCH_MODELS: WolfModelTestingRecord[] = [
  {
    id: "megadetector-v6",
    modelName: "MegaDetector V6",
    modelFunction: "Animal detection (Mission 2 pipeline)",
    version: "MDV6-yolov10-c",
    source: "https://github.com/microsoft/MegaDetector",
    checkpoint: "MDV6-yolov10-c",
    modelLicence: "MIT (MegaDetector / PyTorch-Wildlife source)",
    checkpointLicence: "Per-variant \u2014 see MegaDetector Model Zoo",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "TESTED",
    outcome: "ACCEPTED",
    confidenceSummary: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_frame_00000.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-megadetector-6636252feb42/evidence/mission2-elephant-standing-red-marker-day1_frame_00000.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_frame_00120.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-megadetector-6636252feb42/evidence/mission2-elephant-standing-red-marker-day1_frame_00120.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_frame_00239.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-megadetector-6636252feb42/evidence/mission2-elephant-standing-red-marker-day1_frame_00239.jpg",
    },
    ],
    comments: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-megadetector-6636252feb42",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-megadetector-6636252feb42",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-megadetector-6636252feb42",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-megadetector-6636252feb42",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-megadetector-6636252feb42",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-megadetector-6636252feb42",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "MegaDetector is shared Mission 1 infrastructure, not a welfare classifier.",
        evidence: [],
      }
    ],
  },
  {
    id: "bytetrack",
    modelName: "ByteTrack",
    modelFunction: "Animal tracking / identity association",
    version: "supervision ByteTrack",
    source: "https://github.com/roboflow/supervision",
    checkpoint: "supervision ByteTrack",
    modelLicence: "MIT (supervision)",
    checkpointLicence: "MIT (supervision)",
    commercialUseStatus: "ACCEPTED",
    testStatus: "TESTED",
    outcome: "ACCEPTED",
    confidenceSummary: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_bytetrack_00000.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-bytetrack-46dbeb85f3cd/evidence/mission2-elephant-standing-red-marker-day1_bytetrack_00000.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_bytetrack_00120.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-bytetrack-46dbeb85f3cd/evidence/mission2-elephant-standing-red-marker-day1_bytetrack_00120.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_bytetrack_00239.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-bytetrack-46dbeb85f3cd/evidence/mission2-elephant-standing-red-marker-day1_bytetrack_00239.jpg",
    },
    ],
    comments: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-bytetrack-46dbeb85f3cd",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-bytetrack-46dbeb85f3cd",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-bytetrack-46dbeb85f3cd",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-bytetrack-46dbeb85f3cd",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-bytetrack-46dbeb85f3cd",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-bytetrack-46dbeb85f3cd",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "ByteTrack is infrastructure for WOLF temporal logic, not an injury classifier.",
        evidence: [],
      }
    ],
  },
  {
    id: "ornimetrics-edge",
    modelName: "Ornimetrics Edge",
    modelFunction: "Visual welfare / anomaly screening (research)",
    version: "Ornimetrics/ornimetrics-edge",
    source: "https://huggingface.co/Ornimetrics/ornimetrics-edge",
    checkpoint: "Ornimetrics/ornimetrics-edge",
    modelLicence: "See Hugging Face model card (Ornimetrics/ornimetrics-edge)",
    checkpointLicence: "See Hugging Face model card",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "FAILED_TO_EXECUTE",
    outcome: "FAILED_TO_EXECUTE",
    confidenceSummary: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directo",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-red-marker-day2", "mission2-elephant-lying-day1", "mission2-elephant-lying-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "Ornimetrics Edge benchmark run",
      url: null,
      repositoryPath: "wolf-ai/artifacts/mission2/runs/mission2-ornimetrics-d154f6aed963/",
    },
    ],
    comments: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Ornimetrics/ornimetrics-edge' is the correct path to a directory containing a preprocessor_config.json file",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-ornimetrics-d154f6aed963",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directo",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-ornimetrics-d154f6aed963",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Ornimetrics/ornimetrics-edge' is the correct path to a directory containing a preprocessor_config.json file",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directo",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-ornimetrics-d154f6aed963",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Ornimetrics/ornimetrics-edge' is the correct path to a directory containing a preprocessor_config.json file",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directo",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-ornimetrics-d154f6aed963",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Ornimetrics/ornimetrics-edge' is the correct path to a directory containing a preprocessor_config.json file",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directo",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-ornimetrics-d154f6aed963",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Ornimetrics/ornimetrics-edge' is the correct path to a directory containing a preprocessor_config.json file",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directo",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-ornimetrics-d154f6aed963",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Screen MegaDetector animal crops for visual anomaly patterns. Error: Can't load image processor for 'Ornimetrics/ornimetrics-edge'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Ornimetrics/ornimetrics-edge' is the correct path to a directory containing a preprocessor_config.json file",
        evidence: [],
      }
    ],
  },
  {
    id: "openclip-anomaly",
    modelName: "OpenCLIP anomaly approach",
    modelFunction: "Visual embedding / anomaly screening (research)",
    version: "ViT-B-32/openai",
    source: "https://github.com/mlfoundations/open_clip",
    checkpoint: "ViT-B-32/openai",
    modelLicence: "OpenCLIP checkpoint licence varies by pretrained tag",
    checkpointLicence: "OpenCLIP checkpoint licence varies by pretrained tag",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "TESTED",
    outcome: "TESTED",
    confidenceSummary: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_openclip_crop.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-openclip-5e83a3e817fa/evidence/mission2-elephant-standing-red-marker-day1_openclip_crop.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-day1_openclip_crop.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-openclip-5e83a3e817fa/evidence/mission2-elephant-lying-day1_openclip_crop.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-red-marker-day1_openclip_crop.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-openclip-5e83a3e817fa/evidence/mission2-elephant-lying-red-marker-day1_openclip_crop.jpg",
    },
    ],
    comments: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-openclip-5e83a3e817fa",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-openclip-5e83a3e817fa",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-openclip-5e83a3e817fa",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-openclip-5e83a3e817fa",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-openclip-5e83a3e817fa",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-openclip-5e83a3e817fa",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Experimental anomaly-screening approach \u2014 not a dedicated blood detector.",
        evidence: [],
      }
    ],
  },
  {
    id: "superanimal-quadruped",
    modelName: "DeepLabCut / SuperAnimal-Quadruped",
    modelFunction: "Animal pose / keypoints (research)",
    version: "superanimal_quadruped/hrnet_w32",
    source: "https://github.com/DeepLabCut/DeepLabCut",
    checkpoint: "superanimal_quadruped/hrnet_w32+fasterrcnn_resnet50_fpn_v2",
    modelLicence: "NON_COMMERCIAL (DeepLabCut / SuperAnimal)",
    checkpointLicence: "DeepLabCut Model Zoo / SuperAnimal terms",
    commercialUseStatus: "NON_COMMERCIAL",
    testStatus: "TESTED",
    outcome: "TESTED",
    confidenceSummary: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
    videosTested: ["mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-standing-red-marker-day1"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_superanimal_pose.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-superanimal-92ae7fa96180/evidence/mission2-elephant-standing-red-marker-day1_superanimal_pose.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-day1_superanimal_pose.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-superanimal-92ae7fa96180/evidence/mission2-elephant-lying-day1_superanimal_pose.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-red-marker-day1_superanimal_pose.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-superanimal-92ae7fa96180/evidence/mission2-elephant-lying-red-marker-day1_superanimal_pose.jpg",
    },
    ],
    comments: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-superanimal-92ae7fa96180",
    videoTests: [
      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-superanimal-92ae7fa96180",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-superanimal-92ae7fa96180",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-superanimal-92ae7fa96180",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
        evidence: [],
      }
    ],
  },
  {
    id: "ap10k-mmpose-hrnet-w32",
    modelName: "AP-10K HRNet-W32 / MMPose",
    modelFunction: "Animal pose / keypoints (research comparison)",
    version: "ap10k/hrnet_w32_ap10k_256x256",
    source: "https://github.com/open-mmlab/mmpose",
    checkpoint: "hrnet_w32_ap10k_256x256",
    modelLicence: "Apache-2.0 (MMPose/AP-10K weights)",
    checkpointLicence: "Apache-2.0 (MMPose/AP-10K weights)",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "FAILED_TO_EXECUTE",
    outcome: "FAILED_TO_EXECUTE",
    confidenceSummary: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
    videosTested: ["mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-standing-red-marker-day1"],
    evidence: [
      {
      kind: "detector_output",
      label: "AP-10K HRNet-W32 / MMPose benchmark run",
      url: null,
      repositoryPath: "wolf-ai/artifacts/mission2/runs/mission2-mmpose-4adce7f26a37/",
    },
    ],
    comments: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-mmpose-4adce7f26a37",
    videoTests: [
      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-mmpose-4adce7f26a37",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-mmpose-4adce7f26a37",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-mmpose-4adce7f26a37",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Independent pose comparison on standing vs lying elephant crops. Error: No module named 'mmpose'",
        evidence: [],
      }
    ],
  },
  {
    id: "wolf-temporal-logic",
    modelName: "WOLF AI temporal logic",
    modelFunction: "Cross-flight stationary-animal logic",
    version: "mission2-v1",
    source: "WOLF AI internal logic",
    checkpoint: "MegaDetector V6 centroid comparison",
    modelLicence: "WOLF AI internal logic",
    checkpointLicence: "Internal",
    commercialUseStatus: "ACCEPTED",
    testStatus: "TESTED",
    outcome: "ACCEPTED",
    confidenceSummary: "Movement logic does not require red marker; marker duplicates are tested separately.",
    videosTested: ["mission2-elephant-lying-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "temporal_comparison.json",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-temporal-98a31c0eb599/temporal_comparison.json",
    },
    ],
    comments: "Movement logic does not require red marker; marker duplicates are tested separately.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-temporal-98a31c0eb599",
    videoTests: [
      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "Movement logic does not require red marker; marker duplicates are tested separately.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-temporal-98a31c0eb599",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Movement logic does not require red marker; marker duplicates are tested separately.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "Movement logic does not require red marker; marker duplicates are tested separately.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-temporal-98a31c0eb599",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Movement logic does not require red marker; marker duplicates are tested separately.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "Movement logic does not require red marker; marker duplicates are tested separately.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-temporal-98a31c0eb599",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Movement logic does not require red marker; marker duplicates are tested separately.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "ACCEPTED",
        testStatus: "TESTED",
        confidenceSummary: "Movement logic does not require red marker; marker duplicates are tested separately.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-temporal-98a31c0eb599",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Movement logic does not require red marker; marker duplicates are tested separately.",
        evidence: [],
      }
    ],
  },
  {
    id: "grounding-dino-injury",
    modelName: "Grounding DINO Tiny (injury prompts)",
    modelFunction: "Open-vocabulary injury/abnormality detection (research)",
    version: "IDEA-Research/grounding-dino-tiny",
    source: "https://github.com/IDEA-Research/GroundingDINO",
    checkpoint: "IDEA-Research/grounding-dino-tiny",
    modelLicence: "Apache-2.0",
    checkpointLicence: "Apache-2.0",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "TESTED",
    outcome: "TESTED",
    confidenceSummary: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_grounding_dino.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-grounding-dino-injury-a715365050e3/evidence/mission2-elephant-standing-red-marker-day1_grounding_dino.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-day1_grounding_dino.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-grounding-dino-injury-a715365050e3/evidence/mission2-elephant-lying-day1_grounding_dino.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-red-marker-day1_grounding_dino.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-grounding-dino-injury-a715365050e3/evidence/mission2-elephant-lying-red-marker-day1_grounding_dino.jpg",
    },
    ],
    comments: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-grounding-dino-injury-a715365050e3",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-grounding-dino-injury-a715365050e3",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-grounding-dino-injury-a715365050e3",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-grounding-dino-injury-a715365050e3",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-grounding-dino-injury-a715365050e3",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-grounding-dino-injury-a715365050e3",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Open-vocabulary detector using injury-related text prompts \u2014 not trained for wildlife aerial imagery.",
        evidence: [],
      }
    ],
  },
  {
    id: "owlv2-injury",
    modelName: "OWLv2 (injury queries)",
    modelFunction: "Open-vocabulary injury/abnormality detection (research)",
    version: "google/owlv2-base-patch16-ensemble",
    source: "https://huggingface.co/google/owlv2-base-patch16-ensemble",
    checkpoint: "google/owlv2-base-patch16-ensemble",
    modelLicence: "Apache-2.0",
    checkpointLicence: "Apache-2.0",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "TESTED",
    outcome: "TESTED",
    confidenceSummary: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_owlv2.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-owlv2-injury-0157c6349931/evidence/mission2-elephant-standing-red-marker-day1_owlv2.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-day1_owlv2.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-owlv2-injury-0157c6349931/evidence/mission2-elephant-lying-day1_owlv2.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-red-marker-day1_owlv2.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-owlv2-injury-0157c6349931/evidence/mission2-elephant-lying-red-marker-day1_owlv2.jpg",
    },
    ],
    comments: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-owlv2-injury-0157c6349931",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-owlv2-injury-0157c6349931",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-owlv2-injury-0157c6349931",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-owlv2-injury-0157c6349931",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-owlv2-injury-0157c6349931",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-owlv2-injury-0157c6349931",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Zero-shot OWL detector \u2014 high false-positive risk on non-injury texture.",
        evidence: [],
      }
    ],
  },
  {
    id: "yolo-world-injury",
    modelName: "YOLO-World v2 (injury classes)",
    modelFunction: "Open-vocabulary injury/abnormality detection (research)",
    version: "yolov8s-worldv2.pt",
    source: "https://docs.ultralytics.com/models/yolo-world/",
    checkpoint: "yolov8s-worldv2.pt",
    modelLicence: "AGPL-3.0 (Ultralytics) \u2014 commercial licence review required",
    checkpointLicence: "AGPL-3.0 (Ultralytics runtime)",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "TESTED",
    outcome: "TESTED",
    confidenceSummary: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_yolo_world.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-yolo-world-injury-398d8acf780a/evidence/mission2-elephant-standing-red-marker-day1_yolo_world.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-day1_yolo_world.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-yolo-world-injury-398d8acf780a/evidence/mission2-elephant-lying-day1_yolo_world.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-red-marker-day1_yolo_world.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-yolo-world-injury-398d8acf780a/evidence/mission2-elephant-lying-red-marker-day1_yolo_world.jpg",
    },
    ],
    comments: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-yolo-world-injury-398d8acf780a",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-yolo-world-injury-398d8acf780a",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-yolo-world-injury-398d8acf780a",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-yolo-world-injury-398d8acf780a",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-yolo-world-injury-398d8acf780a",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-yolo-world-injury-398d8acf780a",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Ultralytics YOLO-World \u2014 AGPL runtime; not validated for subtle wildlife injuries.",
        evidence: [],
      }
    ],
  },
  {
    id: "dinov2-crop-anomaly",
    modelName: "DINOv2 crop embedding anomaly",
    modelFunction: "Visual embedding anomaly on MegaDetector crops (research)",
    version: "facebook/dinov2-base",
    source: "https://github.com/facebookresearch/dinov2",
    checkpoint: "facebook/dinov2-base",
    modelLicence: "Apache-2.0 (DINOv2 weights)",
    checkpointLicence: "Apache-2.0",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "TESTED",
    outcome: "TESTED",
    confidenceSummary: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "mission2-elephant-standing-red-marker-day1_dinov2_crop.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-dinov2-crop-anomaly-dd5753f155e0/evidence/mission2-elephant-standing-red-marker-day1_dinov2_crop.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-day1_dinov2_crop.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-dinov2-crop-anomaly-dd5753f155e0/evidence/mission2-elephant-lying-day1_dinov2_crop.jpg",
    },
      {
      kind: "detector_output",
      label: "mission2-elephant-lying-red-marker-day1_dinov2_crop.jpg",
      url: null,
      repositoryPath: "artifacts/mission2/runs/mission2-dinov2-crop-anomaly-dd5753f155e0/evidence/mission2-elephant-lying-red-marker-day1_dinov2_crop.jpg",
    },
    ],
    comments: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-dinov2-crop-anomaly-dd5753f155e0",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-dinov2-crop-anomaly-dd5753f155e0",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-dinov2-crop-anomaly-dd5753f155e0",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-dinov2-crop-anomaly-dd5753f155e0",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-dinov2-crop-anomaly-dd5753f155e0",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "TESTED",
        testStatus: "TESTED",
        confidenceSummary: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-dinov2-crop-anomaly-dd5753f155e0",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "Generic embedding anomaly screen using clean synthetic videos as reference \u2014 not a dedicated injury detector.",
        evidence: [],
      }
    ],
  },
  {
    id: "sam2-grounded-injury",
    modelName: "SAM 2 grounded segmentation (injury research)",
    modelFunction: "Grounded segmentation \u2014 requires upstream injury detector (research)",
    version: "facebook/sam2-hiera-tiny (not executed)",
    source: "https://github.com/facebookresearch/sam2",
    checkpoint: "facebook/sam2-hiera-tiny",
    modelLicence: "Apache-2.0 (SAM 2)",
    checkpointLicence: "Apache-2.0",
    commercialUseStatus: "LICENCE_REVIEW",
    testStatus: "FAILED_TO_EXECUTE",
    outcome: "FAILED_TO_EXECUTE",
    confidenceSummary: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is vali",
    videosTested: ["mission2-elephant-standing-red-marker-day1", "mission2-elephant-lying-day1", "mission2-elephant-lying-red-marker-day1", "mission2-elephant-lying-day2", "mission2-elephant-lying-red-marker-day2"],
    evidence: [
      {
      kind: "detector_output",
      label: "SAM 2 grounded segmentation (injury research) benchmark run",
      url: null,
      repositoryPath: "wolf-ai/artifacts/mission2/runs/mission2-sam2-grounded-injury-da7f14d18fda/",
    },
    ],
    comments: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is validated",
    testedAt: "2026-09-06T02:58:20.314783+00:00",
    benchmarkRunReference: "mission2-sam2-grounded-injury-da7f14d18fda",
    videoTests: [
      {
        videoSlug: "mission2-elephant-standing-red-marker-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is vali",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-sam2-grounded-injury-da7f14d18fda",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is validated",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is vali",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-sam2-grounded-injury-da7f14d18fda",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is validated",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day1",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is vali",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-sam2-grounded-injury-da7f14d18fda",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is validated",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-day2",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is vali",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-sam2-grounded-injury-da7f14d18fda",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is validated",
        evidence: [],
      },      {
        videoSlug: "mission2-elephant-lying-red-marker-day2",
        outcome: "FAILED_TO_EXECUTE",
        testStatus: "FAILED_TO_EXECUTE",
        confidenceSummary: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is vali",
        detectionCount: "See benchmark JSON",
        uniqueAnimalCount: "Not applicable",
        benchmarkRunReference: "mission2-sam2-grounded-injury-da7f14d18fda",
        testedAt: "2026-09-06T02:58:20.314783+00:00",
        comments: "NOT RUN in this benchmark pass. SAM 2 segments prompted regions; WOLF would need a validated open-vocabulary injury detector to supply prompts first. Error: NOT RUN \u2014 segmentation-only model; deferred until upstream injury grounding is validated",
        evidence: [],
      }
    ],
  }
];

export const WOLF_MISSION2_MODEL_TESTING_ARCH_VIDEOS: WolfBenchmarkVideoRecord[] = [
  {
    slug: "mission2-elephant-standing-red-marker-day1",
    sourceDataset: "mission2-synthetic",
    sourceIdentifier: "mission2_elephant_standing_red_marker_day1.mp4",
    sourceUrl: "wolf-benchmark/mission-2/elephant/mission2_elephant_standing_red_marker_day1.mp4",
    videoLicence: "internal-synthetic-engineering-test",
    resolution: "1280\u00d7720",
    width: 1280,
    height: 720,
    fps: 24.0,
    durationSeconds: 10.005333,
    codec: "h264",
    sizeBytes: 9604836,
    droneCamera: "Google Flow synthetic (controlled engineering test)",
    altitude: "Not applicable (synthetic)",
    knownSpecies: "Elephant (synthetic)",
    frameCount: "240",
    benchmarkRole: "Mission 2 synthetic engineering test \u2014 standing, day1, red marker",
    benchmarkStatus: "Benchmarked — Mission 2 suite executed",
    modelsTested: ["megadetector-v6", "bytetrack", "ornimetrics-edge", "openclip-anomaly", "superanimal-quadruped", "ap10k-mmpose-hrnet-w32", "wolf-temporal-logic", "grounding-dino-injury", "owlv2-injury", "yolo-world-injury", "dinov2-crop-anomaly", "sam2-grounded-injury"],
    detectionCount: "See Mission 2 benchmark JSON",
    uniqueAnimalCount: "Not applicable",
    evidenceImages: [],
    benchmarkRunReferences: ["mission2-megadetector-6636252feb42", "mission2-bytetrack-46dbeb85f3cd", "mission2-ornimetrics-d154f6aed963", "mission2-openclip-5e83a3e817fa", "mission2-superanimal-92ae7fa96180", "mission2-mmpose-4adce7f26a37", "mission2-temporal-98a31c0eb599", "mission2-grounding-dino-injury-a715365050e3", "mission2-owlv2-injury-0157c6349931", "mission2-yolo-world-injury-398d8acf780a", "mission2-dinov2-crop-anomaly-dd5753f155e0", "mission2-sam2-grounded-injury-da7f14d18fda"],
    comments: "Controlled synthetic Mission 2 video. Duplicate check: n/a",
    storageObjectPath: "mission-2/elephant/mission2_elephant_standing_red_marker_day1.mp4",
    checksumSha256: "045745e4e6e55d2884a00be66db0cba3eb42d0bb51358e33c5e9cf721fe70d93",
  },
  {
    slug: "mission2-elephant-lying-day1",
    sourceDataset: "mission2-synthetic",
    sourceIdentifier: "mission2_elephant_lying_day1.mp4",
    sourceUrl: "wolf-benchmark/mission-2/elephant/mission2_elephant_lying_day1.mp4",
    videoLicence: "internal-synthetic-engineering-test",
    resolution: "1920\u00d71080",
    width: 1920,
    height: 1080,
    fps: 24.0,
    durationSeconds: 10.0,
    codec: "h264",
    sizeBytes: 36784765,
    droneCamera: "Google Flow synthetic (controlled engineering test)",
    altitude: "Not applicable (synthetic)",
    knownSpecies: "Elephant (synthetic)",
    frameCount: "240",
    benchmarkRole: "Mission 2 synthetic engineering test \u2014 lying, day1",
    benchmarkStatus: "Benchmarked — Mission 2 suite executed",
    modelsTested: ["megadetector-v6", "bytetrack", "ornimetrics-edge", "openclip-anomaly", "superanimal-quadruped", "ap10k-mmpose-hrnet-w32", "wolf-temporal-logic", "grounding-dino-injury", "owlv2-injury", "yolo-world-injury", "dinov2-crop-anomaly", "sam2-grounded-injury"],
    detectionCount: "See Mission 2 benchmark JSON",
    uniqueAnimalCount: "Not applicable",
    evidenceImages: [],
    benchmarkRunReferences: ["mission2-megadetector-6636252feb42", "mission2-bytetrack-46dbeb85f3cd", "mission2-ornimetrics-d154f6aed963", "mission2-openclip-5e83a3e817fa", "mission2-superanimal-92ae7fa96180", "mission2-mmpose-4adce7f26a37", "mission2-temporal-98a31c0eb599", "mission2-grounding-dino-injury-a715365050e3", "mission2-owlv2-injury-0157c6349931", "mission2-yolo-world-injury-398d8acf780a", "mission2-dinov2-crop-anomaly-dd5753f155e0", "mission2-sam2-grounded-injury-da7f14d18fda"],
    comments: "Controlled synthetic Mission 2 video. Duplicate check: n/a",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_day1.mp4",
    checksumSha256: "10c250730a81cb8f3b58e1c709c34eba71e5222d3c6c63756351183183ea5007",
  },
  {
    slug: "mission2-elephant-lying-red-marker-day1",
    sourceDataset: "mission2-synthetic",
    sourceIdentifier: "mission2_elephant_lying_red_marker_day1.mp4",
    sourceUrl: "wolf-benchmark/mission-2/elephant/mission2_elephant_lying_red_marker_day1.mp4",
    videoLicence: "internal-synthetic-engineering-test",
    resolution: "1280\u00d7720",
    width: 1280,
    height: 720,
    fps: 24.0,
    durationSeconds: 10.005333,
    codec: "h264",
    sizeBytes: 9641255,
    droneCamera: "Google Flow synthetic (controlled engineering test)",
    altitude: "Not applicable (synthetic)",
    knownSpecies: "Elephant (synthetic)",
    frameCount: "240",
    benchmarkRole: "Mission 2 synthetic engineering test \u2014 lying, day1, red marker",
    benchmarkStatus: "Benchmarked — Mission 2 suite executed",
    modelsTested: ["megadetector-v6", "bytetrack", "ornimetrics-edge", "openclip-anomaly", "superanimal-quadruped", "ap10k-mmpose-hrnet-w32", "wolf-temporal-logic", "grounding-dino-injury", "owlv2-injury", "yolo-world-injury", "dinov2-crop-anomaly", "sam2-grounded-injury"],
    detectionCount: "See Mission 2 benchmark JSON",
    uniqueAnimalCount: "Not applicable",
    evidenceImages: [],
    benchmarkRunReferences: ["mission2-megadetector-6636252feb42", "mission2-bytetrack-46dbeb85f3cd", "mission2-ornimetrics-d154f6aed963", "mission2-openclip-5e83a3e817fa", "mission2-superanimal-92ae7fa96180", "mission2-mmpose-4adce7f26a37", "mission2-temporal-98a31c0eb599", "mission2-grounding-dino-injury-a715365050e3", "mission2-owlv2-injury-0157c6349931", "mission2-yolo-world-injury-398d8acf780a", "mission2-dinov2-crop-anomaly-dd5753f155e0", "mission2-sam2-grounded-injury-da7f14d18fda"],
    comments: "Controlled synthetic Mission 2 video. Duplicate check: n/a",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_red_marker_day1.mp4",
    checksumSha256: "fd367383a30f205dbb40780578d636c314c2831cab4ea16f2567ef10d72abaff",
  },
  {
    slug: "mission2-elephant-lying-day2",
    sourceDataset: "mission2-synthetic",
    sourceIdentifier: "mission2_elephant_lying_day2.mp4",
    sourceUrl: "wolf-benchmark/mission-2/elephant/mission2_elephant_lying_day2.mp4",
    videoLicence: "internal-synthetic-engineering-test",
    resolution: "1920\u00d71080",
    width: 1920,
    height: 1080,
    fps: 24.0,
    durationSeconds: 10.0,
    codec: "h264",
    sizeBytes: 36784765,
    droneCamera: "Google Flow synthetic (controlled engineering test)",
    altitude: "Not applicable (synthetic)",
    knownSpecies: "Elephant (synthetic)",
    frameCount: "240",
    benchmarkRole: "Mission 2 synthetic engineering test \u2014 lying, day2, duplicate of mission2-elephant-lying-day1",
    benchmarkStatus: "Benchmarked — Mission 2 suite executed",
    modelsTested: ["megadetector-v6", "bytetrack", "ornimetrics-edge", "openclip-anomaly", "superanimal-quadruped", "ap10k-mmpose-hrnet-w32", "wolf-temporal-logic", "grounding-dino-injury", "owlv2-injury", "yolo-world-injury", "dinov2-crop-anomaly", "sam2-grounded-injury"],
    detectionCount: "See Mission 2 benchmark JSON",
    uniqueAnimalCount: "Not applicable",
    evidenceImages: [],
    benchmarkRunReferences: ["mission2-megadetector-6636252feb42", "mission2-bytetrack-46dbeb85f3cd", "mission2-ornimetrics-d154f6aed963", "mission2-openclip-5e83a3e817fa", "mission2-superanimal-92ae7fa96180", "mission2-mmpose-4adce7f26a37", "mission2-temporal-98a31c0eb599", "mission2-grounding-dino-injury-a715365050e3", "mission2-owlv2-injury-0157c6349931", "mission2-yolo-world-injury-398d8acf780a", "mission2-dinov2-crop-anomaly-dd5753f155e0", "mission2-sam2-grounded-injury-da7f14d18fda"],
    comments: "Controlled synthetic Mission 2 video. Duplicate check: MATCH",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_day2.mp4",
    checksumSha256: "10c250730a81cb8f3b58e1c709c34eba71e5222d3c6c63756351183183ea5007",
  },
  {
    slug: "mission2-elephant-lying-red-marker-day2",
    sourceDataset: "mission2-synthetic",
    sourceIdentifier: "mission2_elephant_lying_red_marker_day2.mp4",
    sourceUrl: "wolf-benchmark/mission-2/elephant/mission2_elephant_lying_red_marker_day2.mp4",
    videoLicence: "internal-synthetic-engineering-test",
    resolution: "1280\u00d7720",
    width: 1280,
    height: 720,
    fps: 24.0,
    durationSeconds: 10.005333,
    codec: "h264",
    sizeBytes: 9641255,
    droneCamera: "Google Flow synthetic (controlled engineering test)",
    altitude: "Not applicable (synthetic)",
    knownSpecies: "Elephant (synthetic)",
    frameCount: "240",
    benchmarkRole: "Mission 2 synthetic engineering test \u2014 lying, day2, red marker, duplicate of mission2-elephant-lying-red-marker-day1",
    benchmarkStatus: "Benchmarked — Mission 2 suite executed",
    modelsTested: ["megadetector-v6", "bytetrack", "ornimetrics-edge", "openclip-anomaly", "superanimal-quadruped", "ap10k-mmpose-hrnet-w32", "wolf-temporal-logic", "grounding-dino-injury", "owlv2-injury", "yolo-world-injury", "dinov2-crop-anomaly", "sam2-grounded-injury"],
    detectionCount: "See Mission 2 benchmark JSON",
    uniqueAnimalCount: "Not applicable",
    evidenceImages: [],
    benchmarkRunReferences: ["mission2-megadetector-6636252feb42", "mission2-bytetrack-46dbeb85f3cd", "mission2-ornimetrics-d154f6aed963", "mission2-openclip-5e83a3e817fa", "mission2-superanimal-92ae7fa96180", "mission2-mmpose-4adce7f26a37", "mission2-temporal-98a31c0eb599", "mission2-grounding-dino-injury-a715365050e3", "mission2-owlv2-injury-0157c6349931", "mission2-yolo-world-injury-398d8acf780a", "mission2-dinov2-crop-anomaly-dd5753f155e0", "mission2-sam2-grounded-injury-da7f14d18fda"],
    comments: "Controlled synthetic Mission 2 video. Duplicate check: MATCH",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_red_marker_day2.mp4",
    checksumSha256: "fd367383a30f205dbb40780578d636c314c2831cab4ea16f2567ef10d72abaff",
  }
];

