import type {
  Mission2EvidenceImage,
  WolfMission2BenchmarkVideoRecord,
  WolfMission2ModelTestingRecord,
} from "@/lib/wolf/wolf-mission2-model-testing-arch-types";

/** Bump when Mission 2 seed metadata changes. */
export const WOLF_MISSION2_MODEL_TESTING_ARCH_SEED_VERSION = 1;

const PENDING = "PENDING" as const;

function evidence(path: string, label: string, kind: Mission2EvidenceImage["kind"] = "detector_output"): Mission2EvidenceImage {
  return { kind, label, url: null, repositoryPath: path };
}

export const WOLF_MISSION2_MODEL_TESTING_ARCH_MODELS: WolfMission2ModelTestingRecord[] = [
  {
    id: "megadetector-v6",
    modelName: "MegaDetector V6",
    category: "Animal detection",
    purpose: "Common animal detector for Mission 2 welfare pipeline.",
    version: "MDV6-yolov10-c",
    checkpoint: "MDV6-yolov10-c",
    modelLicence: "MIT (MegaDetector / PyTorch-Wildlife source)",
    commercialLicenceStatus: "LICENCE_REVIEW",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "ACCEPTED",
    videosTested: [],
    evidence: [],
    comments: "Shared Mission 1 infrastructure — not a welfare classifier.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
  {
    id: "bytetrack",
    modelName: "ByteTrack",
    category: "Animal tracking",
    purpose: "Track animal identity and centroid trajectories for temporal welfare logic.",
    version: "supervision ByteTrack",
    checkpoint: "supervision ByteTrack",
    modelLicence: "MIT (supervision)",
    commercialLicenceStatus: "ACCEPTED",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "ACCEPTED",
    videosTested: [],
    evidence: [],
    comments: "Tracking foundation for WOLF temporal logic.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
  {
    id: "ornimetrics-edge",
    modelName: "Ornimetrics Edge",
    category: "Visual welfare / anomaly screening",
    purpose: "Screen MegaDetector animal crops for visual anomaly patterns.",
    version: "Ornimetrics/ornimetrics-edge",
    checkpoint: "Ornimetrics/ornimetrics-edge",
    modelLicence: "See Hugging Face model card",
    commercialLicenceStatus: "LICENCE_REVIEW",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "RESEARCH ONLY",
    videosTested: [],
    evidence: [],
    comments: "Research branch — not automatically part of V1 operations.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
  {
    id: "openclip-anomaly",
    modelName: "OpenCLIP anomaly approach",
    category: "Visual embedding / anomaly screening",
    purpose: "Compare animal-crop embeddings against injury-related text prompts.",
    version: "ViT-B-32/openai",
    checkpoint: "ViT-B-32/openai",
    modelLicence: "OpenCLIP checkpoint licence varies by pretrained tag",
    commercialLicenceStatus: "LICENCE_REVIEW",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "RESEARCH ONLY",
    videosTested: [],
    evidence: [],
    comments: "Experimental anomaly-screening approach.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
  {
    id: "superanimal-quadruped",
    modelName: "DeepLabCut / SuperAnimal-Quadruped",
    category: "Animal pose / keypoints",
    purpose: "Assess pretrained quadruped pose keypoints on standing and lying elephant crops.",
    version: "superanimal_quadruped",
    checkpoint: "superanimal_quadruped",
    modelLicence: "NON_COMMERCIAL (DeepLabCut / SuperAnimal)",
    commercialLicenceStatus: "NON_COMMERCIAL",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "RESEARCH ONLY",
    videosTested: [],
    evidence: [],
    comments: "Pose is not required for basic V1 welfare alert.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
  {
    id: "ap10k-mmpose-hrnet-w32",
    modelName: "AP-10K HRNet-W32 / MMPose",
    category: "Animal pose / keypoints",
    purpose: "Independent pose comparison on standing vs lying elephant crops.",
    version: "ap10k/hrnet_w32_ap10k_256x256",
    checkpoint: "hrnet_w32_ap10k_256x256",
    modelLicence: "Apache-2.0 (MMPose/AP-10K weights)",
    commercialLicenceStatus: "LICENCE_REVIEW",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "RESEARCH ONLY",
    videosTested: [],
    evidence: [],
    comments: "No authoritative keypoint ground truth on synthetic Mission 2 videos.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
  {
    id: "wolf-temporal-logic",
    modelName: "WOLF AI temporal logic",
    category: "Cross-flight stationary-animal logic",
    purpose: "Compare MegaDetector-derived animal positions across Day 1 and Day 2 flights.",
    version: "mission2-v1",
    checkpoint: "MegaDetector V6 centroid comparison",
    modelLicence: "WOLF AI internal logic",
    commercialLicenceStatus: "ACCEPTED",
    testStatus: PENDING,
    outcome: PENDING,
    result: "Awaiting Mission 2 benchmark execution.",
    runtime: "Pending",
    v1Relevance: "ACCEPTED",
    videosTested: [],
    evidence: [],
    comments: "Red marker is not required for movement logic.",
    testedAt: null,
    benchmarkRunReference: null,
    videoTests: [],
  },
];

export const WOLF_MISSION2_MODEL_TESTING_ARCH_VIDEOS: WolfMission2BenchmarkVideoRecord[] = [
  {
    slug: "mission2-elephant-standing-red-marker-day1",
    filename: "mission2_elephant_standing_red_marker_day1.mp4",
    day: "Day 1",
    condition: "Standing + red marker",
    redMarker: true,
    posture: "standing",
    duplicateRelationship: "—",
    resolution: "Pending verification",
    width: 0,
    height: 0,
    fps: 0,
    durationSeconds: 0,
    frameCount: "Pending",
    codec: "Pending",
    sizeBytes: 0,
    checksumSha256: "Pending verification",
    testPurpose: "Visible injury/red-marker test; standing pose condition.",
    modelsTested: [],
    evidence: [],
    benchmarkRunReferences: [],
    notes: "Controlled synthetic engineering test (Google Flow).",
    storageObjectPath: "mission-2/elephant/mission2_elephant_standing_red_marker_day1.mp4",
  },
  {
    slug: "mission2-elephant-lying-day1",
    filename: "mission2_elephant_lying_day1.mp4",
    day: "Day 1",
    condition: "Lying, no marker",
    redMarker: false,
    posture: "lying",
    duplicateRelationship: "Source for Day 2 duplicate (Video 4)",
    resolution: "Pending verification",
    width: 0,
    height: 0,
    fps: 0,
    durationSeconds: 0,
    frameCount: "Pending",
    codec: "Pending",
    sizeBytes: 0,
    checksumSha256: "Pending verification",
    testPurpose: "Lying pose; Day 1 stationary observation.",
    modelsTested: [],
    evidence: [],
    benchmarkRunReferences: [],
    notes: "Controlled synthetic engineering test (Google Flow).",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_day1.mp4",
  },
  {
    slug: "mission2-elephant-lying-red-marker-day1",
    filename: "mission2_elephant_lying_red_marker_day1.mp4",
    day: "Day 1",
    condition: "Lying + red marker",
    redMarker: true,
    posture: "lying",
    duplicateRelationship: "Source for Day 2 duplicate (Video 5)",
    resolution: "Pending verification",
    width: 0,
    height: 0,
    fps: 0,
    durationSeconds: 0,
    frameCount: "Pending",
    codec: "Pending",
    sizeBytes: 0,
    checksumSha256: "Pending verification",
    testPurpose: "Visible injury/red-marker while lying; combined injury + posture condition.",
    modelsTested: [],
    evidence: [],
    benchmarkRunReferences: [],
    notes: "Controlled synthetic engineering test (Google Flow).",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_red_marker_day1.mp4",
  },
  {
    slug: "mission2-elephant-lying-day2",
    filename: "mission2_elephant_lying_day2.mp4",
    day: "Day 2",
    condition: "Lying, no marker",
    redMarker: false,
    posture: "lying",
    duplicateRelationship: "EXACT DUPLICATE of mission2-elephant-lying-day1 (Video 2)",
    resolution: "Pending verification",
    width: 0,
    height: 0,
    fps: 0,
    durationSeconds: 0,
    frameCount: "Pending",
    codec: "Pending",
    sizeBytes: 0,
    checksumSha256: "Pending verification",
    testPurpose: "Day 2 stationary observation; cross-flight no-movement test.",
    modelsTested: [],
    evidence: [],
    benchmarkRunReferences: [],
    notes: "Exact duplicate of Video 2 to simulate repeated observation.",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_day2.mp4",
  },
  {
    slug: "mission2-elephant-lying-red-marker-day2",
    filename: "mission2_elephant_lying_red_marker_day2.mp4",
    day: "Day 2",
    condition: "Lying + red marker",
    redMarker: true,
    posture: "lying",
    duplicateRelationship: "EXACT DUPLICATE of mission2-elephant-lying-red-marker-day1 (Video 3)",
    resolution: "Pending verification",
    width: 0,
    height: 0,
    fps: 0,
    durationSeconds: 0,
    frameCount: "Pending",
    codec: "Pending",
    sizeBytes: 0,
    checksumSha256: "Pending verification",
    testPurpose: "Day 2 combined observation; cross-flight no-movement with marker.",
    modelsTested: [],
    evidence: [],
    benchmarkRunReferences: [],
    notes: "Exact duplicate of Video 3 to simulate repeated observation.",
    storageObjectPath: "mission-2/elephant/mission2_elephant_lying_red_marker_day2.mp4",
  },
];
