/** SAEC technology asset seed rows — consumed by createSaecAssetRegistry in asset-management-data. */

export const SAEC_ASSET_SEEDS = [
  {
    id: "saec-ast-van-01",
    assetTag: "SAEC-VAN-001",
    category: "Vehicle",
    location: "Pretoria",
    model: "Toyota Hilux Double Cab",
    serialNumber: "AHTGK3CD80A123456",
    purchaseDate: "2024-02-15",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Gauteng service route · CY 123-456",
  },
  {
    id: "saec-ast-van-02",
    assetTag: "SAEC-VAN-014",
    category: "Vehicle",
    location: "Johannesburg",
    model: "Ford Ranger 2.0 TDCi",
    serialNumber: "WF0XXXGCDX1234567",
    purchaseDate: "2023-11-01",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Sandton / East Rand service",
  },
  {
    id: "saec-ast-crane-01",
    assetTag: "SAEC-INST-021",
    category: "Tools",
    location: "Pretoria",
    model: "Mobile scaffold tower 6m",
    serialNumber: "MST-6M-2024-07",
    purchaseDate: "2024-07-10",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Installation team allocation",
  },
  {
    id: "saec-ast-test-01",
    assetTag: "SAEC-TEST-003",
    category: "Payload Module",
    location: "Pretoria",
    model: "Elevator governor test rig",
    serialNumber: "EGT-RIG-2022-01",
    purchaseDate: "2022-05-20",
    operationalStatus: "In Service" as const,
    firmwareVersion: "v2.4",
    notes: "QMS calibrated annually",
  },
  {
    id: "saec-ast-tool-01",
    assetTag: "SAEC-TOOL-108",
    category: "Tools",
    location: "Cape Town",
    model: "Escalator commissioning kit",
    serialNumber: "CANNY-KIT-CT-04",
    purchaseDate: "2025-01-08",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Western Cape installations",
  },
  {
    id: "saec-ast-wh-01",
    assetTag: "SAEC-WH-PALLET",
    category: "Transport Case",
    location: "Pretoria",
    model: "Electric pallet stacker 1.5t",
    serialNumber: "EPS-15-2023-02",
    purchaseDate: "2023-08-01",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Spare parts warehouse",
  },
  {
    id: "saec-ast-laptop-01",
    assetTag: "SAEC-IT-042",
    category: "Remote Controller",
    location: "Pretoria",
    model: "Dell Latitude 5540",
    serialNumber: "DL5540-ZA-1042",
    purchaseDate: "2025-02-01",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Field service laptop · Tshepo Modise",
  },
  {
    id: "saec-ast-lift-kit",
    assetTag: "SAEC-SPARE-220",
    category: "Charging Hub",
    location: "Johannesburg",
    model: "MRL door operator kit",
    serialNumber: "DO-KIT-220-2025",
    purchaseDate: "2025-06-12",
    operationalStatus: "In Service" as const,
    firmwareVersion: "N/A",
    notes: "Warehouse spare — KLW range",
  },
] as const;

export const SAEC_ASSET_CATEGORIES = [
  "Vehicle",
  "Tools",
  "Payload Module",
  "Transport Case",
  "Remote Controller",
  "Charging Hub",
];

export const SAEC_ASSET_LOCATIONS = ["Pretoria", "Johannesburg", "Cape Town", "Durban"];
