import type { EngineeringMockState } from "@/lib/engineering-mock-store";

export function buildSaecEngineeringState(): EngineeringMockState {
  return {
    engineers: [
      {
        id: "saec-eng-01",
        name: "Pieter van der Merwe",
        role: "Chief Engineer",
        department: "Engineering",
        manager: "Dewald Lassen",
        skills: ["Lift design", "MRL", "Compliance"],
        currentProject: "V&A Waterfront upgrade",
        allocationPct: 60,
        billablePct: 45,
        availability: "40%",
        leave: "None",
        location: "Pretoria",
        status: "Allocated",
      },
      {
        id: "saec-eng-02",
        name: "Elaine Fourie",
        role: "Design Engineer",
        department: "Engineering",
        manager: "Pieter van der Merwe",
        skills: ["KLH", "Structural", "AutoCAD"],
        currentProject: "Ponte City modernisation",
        allocationPct: 85,
        billablePct: 70,
        availability: "15%",
        leave: "None",
        location: "Johannesburg",
        status: "Allocated",
      },
      {
        id: "saec-eng-03",
        name: "Bongani Cele",
        role: "Site Engineer",
        department: "Installation",
        manager: "Pieter van der Merwe",
        skills: ["Commissioning", "Escalators", "Site safety"],
        currentProject: "Centurion Mall KLK",
        allocationPct: 100,
        billablePct: 85,
        availability: "0%",
        leave: "None",
        location: "Centurion",
        status: "Overloaded",
      },
      {
        id: "saec-eng-04",
        name: "Nadia Govender",
        role: "QA Engineer",
        department: "QMS",
        manager: "Lerato Nkosi",
        skills: ["Inspections", "ISO audits", "CAPA"],
        currentProject: "National compliance review",
        allocationPct: 45,
        billablePct: 30,
        availability: "55%",
        leave: "None",
        location: "Pretoria",
        status: "Available",
      },
    ],
    projects: [
      {
        id: "saec-eng-prj-01",
        name: "Killarney Mall escalator engineering package",
        kind: "Client",
        client: "Killarney Mall",
        owner: "Elaine Fourie",
        team: ["Elaine Fourie", "Bongani Cele"],
        sprint: "Commissioning",
        progress: 72,
        budget: "R 4.2M",
        hoursUsed: 820,
        hoursTotal: 1100,
        health: "Green",
        milestones: ["Mechanical install complete", "Commissioning sign-off"],
        dependencies: ["Client electrical upgrade"],
      },
      {
        id: "saec-eng-prj-02",
        name: "Ponte City lift modernisation — technical design",
        kind: "Client",
        client: "Growthpoint Properties",
        owner: "Pieter van der Merwe",
        team: ["Pieter van der Merwe", "Elaine Fourie"],
        sprint: "Design",
        progress: 58,
        budget: "R 6.8M",
        hoursUsed: 640,
        hoursTotal: 1200,
        health: "Amber",
        milestones: ["Machine room survey", "Door operator spec"],
        dependencies: ["Structural consultant review"],
      },
      {
        id: "saec-eng-prj-03",
        name: "V&A Waterfront public escalator replacement",
        kind: "Client",
        client: "V&A Waterfront",
        owner: "Bongani Cele",
        team: ["Bongani Cele", "Nadia Govender"],
        sprint: "Site work",
        progress: 64,
        budget: "R 5.1M",
        hoursUsed: 710,
        hoursTotal: 1050,
        health: "Green",
        milestones: ["Escalator delivery", "Public area handover"],
        dependencies: ["Cape Town logistics"],
      },
    ],
    activity: [
      {
        id: "saec-eng-act-1",
        at: new Date().toISOString(),
        label: "Drawing issued",
        detail: "KLW door operator layout — Brooklyn Mall",
      },
      {
        id: "saec-eng-act-2",
        at: new Date().toISOString(),
        label: "Site inspection",
        detail: "Ponte City lift machine room survey completed",
      },
    ],
    incidents: [
      {
        id: "saec-eng-inc-1",
        title: "Escalator step alignment deviation",
        severity: "SEV2",
        status: "Open",
        owner: "Bongani Cele",
      },
    ],
    debt: [
      {
        id: "saec-eng-debt-1",
        title: "Legacy AutoCAD template library",
        area: "Engineering documentation",
        effort: "3 sprints",
        priority: "Medium",
      },
    ],
    currentSprint: "Engineering Sprint 18 · Aug 2026",
    upcomingReleases: [
      "KLW commissioning checklist v3",
      "Escalator safety audit pack",
      "Site inspection mobile forms",
    ],
    infraStatus: "Healthy",
  };
}
