import type { HrMockState } from "@/lib/hr-mock-store";
import {
  SAEC_RECRUITMENT_CANDIDATES,
  SAEC_RECRUITMENT_VACANCIES,
} from "@/lib/saec/demo/hr-recruitment-seed";
import {
  blankCompetencyScores,
  blankQuestionResponses,
} from "@/lib/hr-performance-data";
import { isoDaysFromNow, uid } from "@/lib/hr-mock-store";

export function buildSaecHrMockState(): HrMockState {
  return {
    leaveRequests: [
      {
        id: "saec-leave-1",
        employeeId: "saec-person-thabo",
        employeeName: "Thabo Mokoena",
        department: "Sales",
        location: "Johannesburg",
        role: "Regional Sales Manager",
        managerName: "Dewald Lassen",
        type: "annual",
        startDate: isoDaysFromNow(10),
        endDate: isoDaysFromNow(14),
        days: 5,
        status: "approved",
        notes: "Family travel",
        requestedAt: isoDaysFromNow(-7),
        decidedAt: isoDaysFromNow(-5),
      },
    ],
    leaveBalances: [],
    publicHolidays: [
      {
        id: "saec-hol-heritage",
        name: "Heritage Day",
        date: "2026-09-24",
        calendar: "South Africa",
      },
    ],
    vacancies: SAEC_RECRUITMENT_VACANCIES,
    candidates: SAEC_RECRUITMENT_CANDIDATES,
    reviews: [
      {
        id: "saec-review-1",
        employeeId: "saec-person-thabo",
        employeeName: "Thabo Mokoena",
        department: "Sales",
        role: "Regional Sales Manager",
        managerName: "Dewald Lassen",
        reviewPeriod: "H1 2026",
        status: "submitted",
        overallRating: 4,
        strengths: "Exceeded Gauteng sales targets; strong mall portfolio relationships.",
        areasForImprovement: "Delegate admin follow-ups during peak tender season.",
        trainingRecommendations: "Advanced negotiation programme",
        promotionRecommendation: "later",
        salaryReviewRecommendation: "increase",
        managerRecommendation: "develop",
        employeeGoals: "Close R12M Gauteng pipeline and onboard two mall accounts.",
        nextReviewDate: isoDaysFromNow(90),
        summary: "Exceeded Gauteng sales targets; strong mall portfolio relationships.",
        responses: blankQuestionResponses(),
        objectives: [],
        competencies: blankCompetencyScores(),
        developmentPlan: [],
        createdAt: isoDaysFromNow(-40),
        updatedAt: isoDaysFromNow(-14),
        submittedAt: isoDaysFromNow(-14),
        approvedAt: null,
        completedAt: isoDaysFromNow(-14),
      },
      {
        id: "saec-review-2",
        employeeId: "saec-person-pieter",
        employeeName: "Pieter van der Merwe",
        department: "Installation",
        role: "Installation Director",
        managerName: "Dewald Lassen",
        reviewPeriod: "H1 2026",
        status: "draft",
        overallRating: null,
        strengths: "Centurion and Brooklyn mall programmes on schedule.",
        areasForImprovement: "Standardise subcontractor QA sign-off.",
        trainingRecommendations: "Lean site management",
        promotionRecommendation: null,
        salaryReviewRecommendation: "hold",
        managerRecommendation: "develop",
        employeeGoals: "Deliver Centurion Mall commissioning by September.",
        nextReviewDate: isoDaysFromNow(95),
        summary: "Installation programme delivery — Centurion & Brooklyn malls.",
        responses: blankQuestionResponses(),
        objectives: [],
        competencies: blankCompetencyScores(),
        developmentPlan: [],
        createdAt: isoDaysFromNow(-20),
        updatedAt: isoDaysFromNow(-3),
        submittedAt: null,
        approvedAt: null,
        completedAt: null,
      },
    ],
    goals: [
      {
        id: "saec-goal-1",
        title: "Close R12M Gauteng pipeline",
        description: "Mall modernisation tenders and renewals in Gauteng.",
        progressPercent: 68,
        dueDate: isoDaysFromNow(90),
        status: "on_track",
        weight: 30,
        owner: "Thabo Mokoena",
        scope: "employee",
        employeeId: "saec-person-thabo",
        employeeName: "Thabo Mokoena",
        department: "Sales",
      },
    ],
    reports: [],
    activity: [
      {
        id: uid("saec-hr-act"),
        at: isoDaysFromNow(0),
        label: "OmniTransit HR dataset loaded",
        detail: "Demonstration employees and recruitment pipeline.",
      },
    ],
  };
}
