import type { HrMockState } from "@/lib/hr-mock-store";
import { emptyOfferDetails, emptyInterview } from "@/lib/hr-recruitment-data";
import {
  blankCompetencyScores,
  blankQuestionResponses,
} from "@/lib/hr-performance-data";
import { isoDaysFromNow, uid } from "@/lib/hr-mock-store";

export function buildSaecHrMockState(): HrMockState {
  return {
    leaveRequests: [
      {
        id: "saec-leave-1",
        employeeId: "saec-person-thabo",
        employeeName: "Thabo Mokoena",
        department: "Sales",
        location: "Johannesburg",
        role: "Regional Sales Manager",
        managerName: "Dewald Lassen",
        type: "annual",
        startDate: isoDaysFromNow(10),
        endDate: isoDaysFromNow(14),
        days: 5,
        status: "approved",
        notes: "Family travel",
        requestedAt: isoDaysFromNow(-7),
        decidedAt: isoDaysFromNow(-5),
      },
    ],
    leaveBalances: [],
    publicHolidays: [
      {
        id: "saec-hol-heritage",
        name: "Heritage Day",
        date: "2026-09-24",
        calendar: "South Africa",
      },
    ],
    vacancies: [
      {
        id: "saec-vac-eng",
        title: "Senior Installation Engineer",
        department: "Installation",
        location: "Gauteng",
        employmentType: "Full time",
        hiringManager: "Pieter van der Merwe",
        status: "open",
        openedAt: isoDaysFromNow(-21),
        targetStartDate: isoDaysFromNow(45),
        closingDate: isoDaysFromNow(30),
        headcount: 1,
        salaryBand: "R 480k – R 620k",
        description: "Lead escalator and lift installation projects nationally.",
        requirements: "Trade qualification and 5+ years vertical transport experience.",
      },
    ],
    candidates: [
      {
        id: "saec-cand-1",
        name: "Sipho Dlamini",
        email: "sipho.dlamini@example.co.za",
        phone: "+27 82 441 2290",
        vacancyId: "saec-vac-eng",
        role: "Senior Installation Engineer",
        department: "Installation",
        location: "Gauteng",
        stage: "interview",
        rating: 4,
        interviewer: "Pieter van der Merwe",
        recruiter: "Annelize Fourie",
        expectedSalary: "R 580k",
        availability: "1 month notice",
        source: "Referral",
        appliedAt: isoDaysFromNow(-12),
        notes: "Strong escalator commissioning background — Gauteng malls.",
        cvLabel: "Sipho_Dlamini_CV.pdf",
        rejected: false,
        interviews: [
          {
            ...emptyInterview(),
            id: "saec-int-1",
            scheduledAt: `${isoDaysFromNow(3)}T10:00`,
            type: "video",
            interviewer: "Pieter van der Merwe",
            interviewers: "Pieter van der Merwe",
            status: "scheduled",
            notes: "Technical panel — mall installation case study.",
          },
        ],
        offer: emptyOfferDetails(),
        timeline: [
          {
            id: "saec-tl-1",
            at: isoDaysFromNow(-12),
            label: "Application received",
            detail: "Referral from Gauteng service lead",
          },
        ],
      },
      {
        id: "saec-cand-2",
        name: "Nomsa Khumalo",
        email: "nomsa.k@example.co.za",
        phone: "+27 83 902 1144",
        vacancyId: "saec-vac-eng",
        role: "Senior Installation Engineer",
        department: "Installation",
        location: "Western Cape",
        stage: "screening",
        rating: 3,
        interviewer: "Pieter van der Merwe",
        recruiter: "Annelize Fourie",
        expectedSalary: "R 520k",
        availability: "2 weeks notice",
        source: "LinkedIn",
        appliedAt: isoDaysFromNow(-5),
        notes: "Lift technician — Western Cape relocation considered.",
        cvLabel: "Nomsa_Khumalo_CV.pdf",
        rejected: false,
        interviews: [],
        offer: emptyOfferDetails(),
        timeline: [
          {
            id: "saec-tl-2",
            at: isoDaysFromNow(-5),
            label: "Application received",
            detail: "LinkedIn inbound",
          },
        ],
      },
    ],
    reviews: [
      {
        id: "saec-review-1",
        employeeId: "saec-person-thabo",
        employeeName: "Thabo Mokoena",
        department: "Sales",
        role: "Regional Sales Manager",
        managerName: "Dewald Lassen",
        reviewPeriod: "H1 2026",
        status: "submitted",
        overallRating: 4,
        strengths: "Exceeded Gauteng sales targets; strong mall portfolio relationships.",
        areasForImprovement: "Delegate admin follow-ups during peak tender season.",
        trainingRecommendations: "Advanced negotiation programme",
        promotionRecommendation: "later",
        salaryReviewRecommendation: "increase",
        managerRecommendation: "develop",
        employeeGoals: "Close R12M Gauteng pipeline and onboard two mall accounts.",
        nextReviewDate: isoDaysFromNow(90),
        summary: "Exceeded Gauteng sales targets; strong mall portfolio relationships.",
        responses: blankQuestionResponses(),
        objectives: [],
        competencies: blankCompetencyScores(),
        developmentPlan: [],
        createdAt: isoDaysFromNow(-40),
        updatedAt: isoDaysFromNow(-14),
        submittedAt: isoDaysFromNow(-14),
        approvedAt: null,
        completedAt: isoDaysFromNow(-14),
      },
      {
        id: "saec-review-2",
        employeeId: "saec-person-pieter",
        employeeName: "Pieter van der Merwe",
        department: "Installation",
        role: "Installation Director",
        managerName: "Dewald Lassen",
        reviewPeriod: "H1 2026",
        status: "draft",
        overallRating: null,
        strengths: "Centurion and Brooklyn mall programmes on schedule.",
        areasForImprovement: "Standardise subcontractor QA sign-off.",
        trainingRecommendations: "Lean site management",
        promotionRecommendation: null,
        salaryReviewRecommendation: "hold",
        managerRecommendation: "develop",
        employeeGoals: "Deliver Centurion Mall commissioning by September.",
        nextReviewDate: isoDaysFromNow(95),
        summary: "Installation programme delivery — Centurion & Brooklyn malls.",
        responses: blankQuestionResponses(),
        objectives: [],
        competencies: blankCompetencyScores(),
        developmentPlan: [],
        createdAt: isoDaysFromNow(-20),
        updatedAt: isoDaysFromNow(-3),
        submittedAt: null,
        approvedAt: null,
        completedAt: null,
      },
    ],
    goals: [
      {
        id: "saec-goal-1",
        title: "Close R12M Gauteng pipeline",
        description: "Mall modernisation tenders and renewals in Gauteng.",
        progressPercent: 68,
        dueDate: isoDaysFromNow(90),
        status: "on_track",
        weight: 30,
        owner: "Thabo Mokoena",
        scope: "employee",
        employeeId: "saec-person-thabo",
        employeeName: "Thabo Mokoena",
        department: "Sales",
      },
    ],
    reports: [],
    activity: [
      {
        id: uid("saec-hr-act"),
        at: isoDaysFromNow(0),
        label: "OmniTransit HR dataset loaded",
        detail: "Demonstration employees and recruitment pipeline.",
      },
    ],
  };
}
