import type { HrCandidate, HrVacancy } from "@/lib/hr-recruitment-data";
import { emptyOfferDetails, emptyInterview } from "@/lib/hr-recruitment-data";
import { isoDaysFromNow } from "@/lib/hr-mock-store";

export const SAEC_RECRUITMENT_VACANCIES: HrVacancy[] = [
  {
    id: "saec-vac-eng",
    title: "Senior Installation Engineer",
    department: "Installation",
    location: "Gauteng",
    employmentType: "Full time",
    hiringManager: "Pieter van der Merwe",
    status: "open",
    openedAt: isoDaysFromNow(-21),
    targetStartDate: isoDaysFromNow(45),
    closingDate: isoDaysFromNow(30),
    headcount: 1,
    salaryBand: "R 480k – R 620k",
    description: "Lead escalator and lift installation projects nationally.",
    requirements: "Trade qualification and 5+ years vertical transport experience.",
  },
  {
    id: "saec-vac-svc",
    title: "Field Service Technician — Western Cape",
    department: "Service",
    location: "Western Cape",
    employmentType: "Full time",
    hiringManager: "Lerato Nkosi",
    status: "open",
    openedAt: isoDaysFromNow(-14),
    targetStartDate: isoDaysFromNow(60),
    closingDate: isoDaysFromNow(35),
    headcount: 2,
    salaryBand: "R 320k – R 420k",
    description: "Maintain passenger lifts and escalators across Cape retail portfolio.",
    requirements: "Lift technician ticket and mall service experience.",
  },
  {
    id: "saec-vac-sales",
    title: "Commercial Account Manager — KwaZulu-Natal",
    department: "Sales",
    location: "Durban",
    employmentType: "Full time",
    hiringManager: "Dewald Lassen",
    status: "open",
    openedAt: isoDaysFromNow(-10),
    targetStartDate: isoDaysFromNow(50),
    closingDate: isoDaysFromNow(28),
    headcount: 1,
    salaryBand: "R 450k – R 580k",
    description: "Grow retail and healthcare vertical transport accounts in KZN.",
    requirements: "B2B facilities sales and tender experience.",
  },
  {
    id: "saec-vac-qms",
    title: "Quality Assurance Coordinator",
    department: "Quality",
    location: "Pretoria",
    employmentType: "Full time",
    hiringManager: "Nadia Govender",
    status: "open",
    openedAt: isoDaysFromNow(-18),
    targetStartDate: isoDaysFromNow(40),
    closingDate: isoDaysFromNow(25),
    headcount: 1,
    salaryBand: "R 380k – R 480k",
    description: "Support ISO 9001 surveillance audits and site file compliance.",
    requirements: "QMS experience in engineering or manufacturing.",
  },
  {
    id: "saec-vac-project",
    title: "Installation Project Coordinator",
    department: "Installation",
    location: "Johannesburg",
    employmentType: "Full time",
    hiringManager: "Pieter van der Merwe",
    status: "on_hold",
    openedAt: isoDaysFromNow(-45),
    targetStartDate: isoDaysFromNow(20),
    closingDate: isoDaysFromNow(5),
    headcount: 1,
    salaryBand: "R 360k – R 460k",
    description: "Coordinate mall installation programmes and subcontractor QA.",
    requirements: "Project coordination in construction or vertical transport.",
  },
  {
    id: "saec-vac-intern",
    title: "Engineering Graduate — Field Support",
    department: "Engineering",
    location: "Gauteng",
    employmentType: "Contract",
    hiringManager: "Bongani Cele",
    status: "open",
    openedAt: isoDaysFromNow(-7),
    targetStartDate: isoDaysFromNow(90),
    closingDate: isoDaysFromNow(45),
    headcount: 2,
    salaryBand: "R 240k – R 300k",
    description: "12-month graduate programme supporting commissioning teams.",
    requirements: "Mechanical or electrical engineering degree.",
  },
];

export const SAEC_RECRUITMENT_CANDIDATES: HrCandidate[] = [
  {
    id: "saec-cand-1",
    name: "Sipho Dlamini",
    email: "sipho.dlamini@example.co.za",
    phone: "+27 82 441 2290",
    vacancyId: "saec-vac-eng",
    role: "Senior Installation Engineer",
    department: "Installation",
    location: "Gauteng",
    stage: "interview",
    rating: 4,
    interviewer: "Pieter van der Merwe",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 580k",
    availability: "1 month notice",
    source: "Referral",
    appliedAt: isoDaysFromNow(-12),
    notes: "Strong escalator commissioning background — Gauteng malls.",
    cvLabel: "Sipho_Dlamini_CV.pdf",
    rejected: false,
    interviews: [
      {
        ...emptyInterview(),
        id: "saec-int-1",
        scheduledAt: `${isoDaysFromNow(3)}T10:00`,
        type: "video",
        interviewer: "Pieter van der Merwe",
        interviewers: "Pieter van der Merwe",
        status: "scheduled",
        notes: "Technical panel — mall installation case study.",
      },
    ],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-1",
        at: isoDaysFromNow(-12),
        label: "Application received",
        detail: "Referral from Gauteng service lead",
      },
    ],
  },
  {
    id: "saec-cand-2",
    name: "Nomsa Khumalo",
    email: "nomsa.k@example.co.za",
    phone: "+27 83 902 1144",
    vacancyId: "saec-vac-eng",
    role: "Senior Installation Engineer",
    department: "Installation",
    location: "Western Cape",
    stage: "screening",
    rating: 3,
    interviewer: "Pieter van der Merwe",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 520k",
    availability: "2 weeks notice",
    source: "LinkedIn",
    appliedAt: isoDaysFromNow(-5),
    notes: "Lift technician — Western Cape relocation considered.",
    cvLabel: "Nomsa_Khumalo_CV.pdf",
    rejected: false,
    interviews: [],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-2",
        at: isoDaysFromNow(-5),
        label: "Application received",
        detail: "LinkedIn inbound",
      },
    ],
  },
  {
    id: "saec-cand-3",
    name: "James Okonkwo",
    email: "james.okonkwo@example.co.za",
    phone: "+27 84 220 1188",
    vacancyId: "saec-vac-svc",
    role: "Field Service Technician",
    department: "Service",
    location: "Cape Town",
    stage: "offer",
    rating: 5,
    interviewer: "Lerato Nkosi",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 390k",
    availability: "Immediate",
    source: "Agency",
    appliedAt: isoDaysFromNow(-28),
    notes: "Excellent mall escalator fault response record.",
    cvLabel: "James_Okonkwo_CV.pdf",
    rejected: false,
    interviews: [
      {
        ...emptyInterview(),
        id: "saec-int-3",
        scheduledAt: `${isoDaysFromNow(-10)}T14:00`,
        type: "onsite",
        interviewer: "Lerato Nkosi",
        interviewers: "Lerato Nkosi, Bongani Cele",
        status: "completed",
        notes: "Strong practical assessment.",
        outcome: "pass",
      },
    ],
    offer: {
      salary: "R 395k",
      startDate: isoDaysFromNow(21),
      status: "sent",
      employmentType: "Full time",
      notes: "Awaiting medical clearance.",
      sentAt: isoDaysFromNow(-2),
    },
    timeline: [
      {
        id: "saec-tl-3a",
        at: isoDaysFromNow(-28),
        label: "Application received",
        detail: "Agency shortlist",
      },
      {
        id: "saec-tl-3b",
        at: isoDaysFromNow(-2),
        label: "Offer issued",
        detail: "R 395k package",
      },
    ],
  },
  {
    id: "saec-cand-4",
    name: "Fatima Patel",
    email: "fatima.patel@example.co.za",
    phone: "+27 81 770 4421",
    vacancyId: "saec-vac-sales",
    role: "Commercial Account Manager",
    department: "Sales",
    location: "Durban",
    stage: "interview",
    rating: 4,
    interviewer: "Dewald Lassen",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 520k",
    availability: "3 weeks notice",
    source: "Referral",
    appliedAt: isoDaysFromNow(-9),
    notes: "Healthcare facilities sales background.",
    cvLabel: "Fatima_Patel_CV.pdf",
    rejected: false,
    interviews: [
      {
        ...emptyInterview(),
        id: "saec-int-4",
        scheduledAt: `${isoDaysFromNow(5)}T09:30`,
        type: "video",
        interviewer: "Dewald Lassen",
        interviewers: "Dewald Lassen, Thabo Mokoena",
        status: "scheduled",
        notes: "Pipeline presentation.",
      },
    ],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-4",
        at: isoDaysFromNow(-9),
        label: "Application received",
        detail: "Referral from KZN client",
      },
    ],
  },
  {
    id: "saec-cand-5",
    name: "Gerhard Venter",
    email: "gerhard.venter@example.co.za",
    phone: "+27 82 903 7710",
    vacancyId: "saec-vac-qms",
    role: "Quality Assurance Coordinator",
    department: "Quality",
    location: "Pretoria",
    stage: "screening",
    rating: 3,
    interviewer: "Nadia Govender",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 420k",
    availability: "1 month notice",
    source: "Careers page",
    appliedAt: isoDaysFromNow(-15),
    notes: "ISO 9001 internal audit experience.",
    cvLabel: "Gerhard_Venter_CV.pdf",
    rejected: false,
    interviews: [],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-5",
        at: isoDaysFromNow(-15),
        label: "Application received",
        detail: "Careers page",
      },
    ],
  },
  {
    id: "saec-cand-6",
    name: "Michelle Jacobs",
    email: "michelle.jacobs@example.co.za",
    phone: "+27 83 441 9022",
    vacancyId: "saec-vac-project",
    role: "Installation Project Coordinator",
    department: "Installation",
    location: "Johannesburg",
    stage: "screening",
    rating: 2,
    interviewer: "Pieter van der Merwe",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 400k",
    availability: "2 weeks notice",
    source: "LinkedIn",
    appliedAt: isoDaysFromNow(-40),
    notes: "Limited mall programme experience.",
    cvLabel: "Michelle_Jacobs_CV.pdf",
    rejected: true,
    interviews: [],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-6",
        at: isoDaysFromNow(-35),
        label: "Rejected",
        detail: "Insufficient programme scale",
      },
    ],
  },
  {
    id: "saec-cand-7",
    name: "Themba Ncube",
    email: "themba.ncube@example.co.za",
    phone: "+27 84 551 2290",
    vacancyId: "saec-vac-intern",
    role: "Engineering Graduate",
    department: "Engineering",
    location: "Gauteng",
    stage: "screening",
    rating: 4,
    interviewer: "Bongani Cele",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 260k",
    availability: "Immediate",
    source: "Careers page",
    appliedAt: isoDaysFromNow(-4),
    notes: "Wits mechanical engineering graduate.",
    cvLabel: "Themba_Ncube_CV.pdf",
    rejected: false,
    interviews: [],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-7",
        at: isoDaysFromNow(-4),
        label: "Application received",
        detail: "Graduate fair",
      },
    ],
  },
  {
    id: "saec-cand-8",
    name: "Liezel van Jaarsveld",
    email: "liezel.v@example.co.za",
    phone: "+27 82 770 3314",
    vacancyId: "saec-vac-svc",
    role: "Field Service Technician",
    department: "Service",
    location: "Stellenbosch",
    stage: "interview",
    rating: 4,
    interviewer: "Lerato Nkosi",
    recruiter: "Annelize Fourie",
    expectedSalary: "R 360k",
    availability: "1 month notice",
    source: "Referral",
    appliedAt: isoDaysFromNow(-11),
    notes: "Wine estate lift maintenance background.",
    cvLabel: "Liezel_van_Jaarsveld_CV.pdf",
    rejected: false,
    interviews: [
      {
        ...emptyInterview(),
        id: "saec-int-8",
        scheduledAt: `${isoDaysFromNow(2)}T11:00`,
        type: "onsite",
        interviewer: "Lerato Nkosi",
        interviewers: "Lerato Nkosi",
        status: "scheduled",
        notes: "Cape Town depot practical.",
      },
    ],
    offer: emptyOfferDetails(),
    timeline: [
      {
        id: "saec-tl-8",
        at: isoDaysFromNow(-11),
        label: "Application received",
        detail: "Western Cape referral",
      },
    ],
  },
];
