import type { InventoryMockState } from "@/lib/inventory-mock-store";
import { isoDaysFromNow, uid } from "@/lib/inventory-mock-store";
import { emptyAssignment, type InventoryAsset } from "@/lib/inventory-data";
import { SAEC_HEAD_OFFICE } from "@/lib/saec/demo/company";

function stockNote(text: string) {
  return [
    {
      id: uid("note"),
      at: isoDaysFromNow(0),
      author: "Warehouse",
      kind: "operational" as const,
      text,
    },
  ];
}

export function buildSaecInventoryState(): InventoryMockState {
  const assets: InventoryAsset[] = [
    {
      id: "saec-inv-1",
      assetTag: "INV-4101",
      name: "MRL door operator kit (KLW)",
      category: "Tools",
      manufacturer: "OmniTransit Spares",
      model: "DO-KLW-2025",
      serialNumber: "DO-KLW-BATCH-12",
      purchaseDate: isoDaysFromNow(-30),
      purchaseCost: "R 186 000",
      warrantyExpiry: isoDaysFromNow(300),
      currentValue: "R 172 000",
      location: "Pretoria warehouse",
      status: "operational" as const,
      condition: "excellent" as const,
      department: "Warehouse",
      assignedTo: "",
      nextService: "",
      certificationExpiry: "",
      assignment: emptyAssignment(),
      services: [],
      documents: [],
      history: [
        {
          id: uid("hist"),
          at: isoDaysFromNow(-5),
          label: "Stock received",
          detail: "Inbound from supplier · 6 kits",
        },
      ],
      notes: stockNote("On hand: 14 kits · reserved for Gauteng installs"),
      archived: false,
    },
    {
      id: "saec-inv-2",
      assetTag: "INV-4102",
      name: "Escalator step chain assembly",
      category: "Other",
      manufacturer: "Canopy Components",
      model: "ESC-STEP-48",
      serialNumber: "ESC-STEP-2026-03",
      purchaseDate: isoDaysFromNow(-45),
      purchaseCost: "R 92 500",
      warrantyExpiry: "",
      currentValue: "R 88 000",
      location: "Johannesburg stores",
      status: "operational" as const,
      condition: "good" as const,
      department: "Warehouse",
      assignedTo: "",
      nextService: "",
      certificationExpiry: "",
      assignment: emptyAssignment(),
      services: [],
      documents: [],
      history: [],
      notes: stockNote("On hand: 8 assemblies · Cape Town backlog"),
      archived: false,
    },
    {
      id: "saec-inv-3",
      assetTag: "INV-4103",
      name: "Governor test rig consumables pack",
      category: "Tools",
      manufacturer: "OmniTransit QMS",
      model: "GTR-CON-2026",
      serialNumber: "GTR-CON-01",
      purchaseDate: isoDaysFromNow(-20),
      purchaseCost: "R 24 800",
      warrantyExpiry: "",
      currentValue: "R 22 100",
      location: "Pretoria test lab",
      status: "operational" as const,
      condition: "excellent" as const,
      department: "QMS",
      assignedTo: "Nadia Govender",
      nextService: isoDaysFromNow(60),
      certificationExpiry: isoDaysFromNow(120),
      assignment: {
        employee: "Nadia Govender",
        department: "QMS",
        office: SAEC_HEAD_OFFICE.city,
        project: "Calibration programme",
        issueDate: isoDaysFromNow(-10),
        expectedReturn: "",
      },
      services: [],
      documents: [],
      history: [],
      notes: stockNote("Calibrated quarterly · next due Oct 2026"),
      archived: false,
    },
    {
      id: "saec-inv-4",
      assetTag: "INV-4104",
      name: "Service van tool chest — installation",
      category: "Tools",
      manufacturer: "Facom",
      model: "TOOL-CHEST-PRO",
      serialNumber: "FCM-CT-108",
      purchaseDate: isoDaysFromNow(-120),
      purchaseCost: "R 38 500",
      warrantyExpiry: isoDaysFromNow(400),
      currentValue: "R 34 200",
      location: "Pretoria fleet",
      status: "operational" as const,
      condition: "good" as const,
      department: "Installation",
      assignedTo: "Bongani Cele",
      nextService: "",
      certificationExpiry: "",
      assignment: {
        employee: "Bongani Cele",
        department: "Installation",
        office: "Centurion",
        project: "Centurion Mall KLK",
        issueDate: isoDaysFromNow(-30),
        expectedReturn: "",
      },
      services: [],
      documents: [],
      history: [],
      notes: [],
      archived: false,
    },
    {
      id: "saec-inv-5",
      assetTag: "INV-4105",
      name: "Lift rope 10mm × 100m coil",
      category: "Other",
      manufacturer: "WireCo SA",
      model: "ROPE-10MM-100",
      serialNumber: "WC-10-2025-44",
      purchaseDate: isoDaysFromNow(-60),
      purchaseCost: "R 64 000",
      warrantyExpiry: "",
      currentValue: "R 61 500",
      location: "Durban stores",
      status: "operational" as const,
      condition: "excellent" as const,
      department: "Warehouse",
      assignedTo: "",
      nextService: "",
      certificationExpiry: "",
      assignment: emptyAssignment(),
      services: [],
      documents: [],
      history: [],
      notes: stockNote("On hand: 3 coils · KZN modernisation reserve"),
      archived: false,
    },
  ];

  return {
    assets,
    activity: [
      {
        id: "act-saec-inv-1",
        at: isoDaysFromNow(0),
        label: "OmniTransit inventory loaded",
        detail: "Elevator spares, tools, and commissioning kits · national stores",
      },
    ],
  };
}
