/**
 * Demo WOLF estate deployments — seed definitions for WOLF Central only.
 * Not customer workspaces; Pailex customer workspace is explicitly deferred.
 */

import type { WolfEstateAlert, WolfReserveRecord } from "@/lib/wolf/central/types";

export const WOLF_DEMO_RESERVE_SEEDS: Omit<WolfReserveRecord, "id">[] = [
  {
    slug: "pailex-demo",
    name: "PAILEX",
    country: "South Africa",
    latitude: -24.75,
    longitude: 31.5,
    isDemo: true,
    deploymentStatus: "Demo deployment",
    largeDroneCount: 2,
    smallDroneCount: 2,
    dockCount: 2,
    fleetOperational: 4,
    fleetTotal: 4,
    animals: {
      status: "normal",
      headline: "47 detections",
      detail: "Census completed",
      detections: 47,
      censusStatus: "Completed",
    },
    containment: {
      status: "attention",
      headline: "18/18 patrols completed",
      detail: "1 anomaly",
      patrolsCompleted: 18,
      patrolsTotal: 18,
      anomalyCount: 1,
    },
    environment: {
      status: "normal",
      headline: "Fire normal · Flood normal",
      fireStatus: "Normal",
      floodStatus: "Normal",
    },
    droneOperations: {
      status: "attention",
      headline: "12 missions",
      detail: "1 attention",
      activeMissions: 1,
      completedMissions: 11,
      failedMissions: 0,
    },
    attentionStatus: "attention",
    futureWorkspaceSlug: "pailex",
    hasCustomerWorkspace: false,
  },
  {
    slug: "marula-ridge-demo",
    name: "Marula Ridge (Fictional Demo)",
    country: "South Africa",
    latitude: -33.2,
    longitude: 26.5,
    isDemo: true,
    deploymentStatus: "Demo deployment",
    largeDroneCount: 2,
    smallDroneCount: 2,
    dockCount: 2,
    fleetOperational: 4,
    fleetTotal: 4,
    animals: {
      status: "normal",
      headline: "32 detections",
      detail: "Census in progress",
      detections: 32,
      censusStatus: "In progress",
    },
    containment: {
      status: "normal",
      headline: "16/16 patrols completed",
      patrolsCompleted: 16,
      patrolsTotal: 16,
      anomalyCount: 0,
    },
    environment: {
      status: "normal",
      headline: "Fire normal · Flood normal",
      fireStatus: "Normal",
      floodStatus: "Normal",
    },
    droneOperations: {
      status: "attention",
      headline: "8 missions",
      detail: "Morning perimeter mission missed",
      activeMissions: 0,
      completedMissions: 7,
      failedMissions: 1,
    },
    attentionStatus: "attention",
    futureWorkspaceSlug: null,
    hasCustomerWorkspace: false,
  },
  {
    slug: "ngoma-valley-demo",
    name: "Ngoma Valley (Fictional Demo)",
    country: "Kenya",
    latitude: -1.4,
    longitude: 35.2,
    isDemo: true,
    deploymentStatus: "Demo deployment",
    largeDroneCount: 2,
    smallDroneCount: 2,
    dockCount: 2,
    fleetOperational: 4,
    fleetTotal: 4,
    animals: {
      status: "normal",
      headline: "58 detections",
      detail: "Census completed",
      detections: 58,
      censusStatus: "Completed",
    },
    containment: {
      status: "normal",
      headline: "14/14 patrols completed",
      patrolsCompleted: 14,
      patrolsTotal: 14,
      anomalyCount: 0,
    },
    environment: {
      status: "normal",
      headline: "Fire normal · Flood normal",
      fireStatus: "Normal",
      floodStatus: "Normal",
    },
    droneOperations: {
      status: "normal",
      headline: "6 missions",
      activeMissions: 0,
      completedMissions: 6,
      failedMissions: 0,
    },
    attentionStatus: "normal",
    futureWorkspaceSlug: null,
    hasCustomerWorkspace: false,
  },
];

export const WOLF_DEMO_ALERT_SEEDS: Omit<WolfEstateAlert, "id" | "createdAt">[] = [
  {
    reserveId: "pailex-demo",
    reserveName: "PAILEX",
    title: "Drone 02",
    detail: "Battery health declining",
    severity: "attention",
  },
  {
    reserveId: "marula-ridge-demo",
    reserveName: "Marula Ridge (Fictional Demo)",
    title: "Morning perimeter mission",
    detail: "Morning perimeter mission missed",
    severity: "attention",
  },
  {
    reserveId: "ngoma-valley-demo",
    reserveName: "Ngoma Valley (Fictional Demo)",
    title: "Operator training",
    detail: "Operator training due",
    severity: "attention",
  },
];
