import type { TechnologyTelecomServiceInput } from "@/lib/technology-telecom/types";

type StarterRow = TechnologyTelecomServiceInput & { location: string };

/** OmniTransit (SAEC) — South African carriers, ZAR monthly amounts (whole units). */
export function buildSaecTechnologyTelecomCatalogue(): StarterRow[] {
  return [
    {
      service: "Office fibre",
      carrier: "Telkom Business",
      numberOrCircuit: "TLK-PTA-HQ-8842 · 1 Gbps · renews 2027-03-15",
      assignedTo: "Pretoria HQ",
      location: "Pretoria",
      monthlyCostMinor: 18_500,
      status: "Active",
    },
    {
      service: "Office fibre",
      carrier: "Vodacom Business",
      numberOrCircuit: "VBC-JHB-DEP-3291 · 500 Mbps · renews 2026-11-30",
      assignedTo: "Johannesburg service depot",
      location: "Johannesburg",
      monthlyCostMinor: 14_200,
      status: "Active",
    },
    {
      service: "Office fibre",
      carrier: "Liquid Intelligent Technologies",
      numberOrCircuit: "LIQ-CPT-BRN-6610 · 1 Gbps · renews 2027-01-20",
      assignedTo: "Cape Town branch",
      location: "Cape Town",
      monthlyCostMinor: 12_800,
      status: "Active",
    },
    {
      service: "Data connection",
      carrier: "MTN Business",
      numberOrCircuit: "MTN-DBN-HUB-4420 · 200 Mbps · renews 2026-10-12",
      assignedTo: "Durban logistics hub",
      location: "Durban",
      monthlyCostMinor: 9_500,
      status: "Active",
    },
    {
      service: "Fixed line",
      carrier: "Telkom",
      numberOrCircuit: "+27 12 460 7700 · PBX trunk",
      assignedTo: "National switchboard",
      location: "Pretoria",
      monthlyCostMinor: 3_200,
      status: "Active",
    },
    {
      service: "Mobile plan",
      carrier: "Vodacom",
      numberOrCircuit: "+27 82 441 2290",
      assignedTo: "Thabo Mokoena",
      location: "Johannesburg",
      monthlyCostMinor: 890,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15 Pro",
    },
    {
      service: "Mobile plan",
      carrier: "MTN",
      numberOrCircuit: "+27 83 902 1144",
      assignedTo: "Pieter van der Merwe",
      location: "Pretoria",
      monthlyCostMinor: 820,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15",
    },
    {
      service: "Mobile plan",
      carrier: "Vodacom",
      numberOrCircuit: "+27 84 120 8831",
      assignedTo: "Lerato Nkosi",
      location: "Johannesburg",
      monthlyCostMinor: 780,
      status: "Active",
      manufacturer: "Samsung",
      model: "Galaxy S24",
    },
    {
      service: "Mobile plan",
      carrier: "Cell C",
      numberOrCircuit: "+27 81 554 9012",
      assignedTo: "Bongani Cele",
      location: "Durban",
      monthlyCostMinor: 650,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
    {
      service: "Mobile plan",
      carrier: "MTN",
      numberOrCircuit: "+27 82 903 4410",
      assignedTo: "Nadia Govender",
      location: "Cape Town",
      monthlyCostMinor: 720,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15",
    },
    {
      service: "Mobile plan",
      carrier: "Vodacom",
      numberOrCircuit: "+27 83 771 2298",
      assignedTo: "Dewald Lassen",
      location: "Pretoria",
      monthlyCostMinor: 950,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15 Pro",
    },
    {
      service: "Mobile plan",
      carrier: "Telkom Mobile",
      numberOrCircuit: "+27 81 402 1188",
      assignedTo: "Field engineer pool",
      location: "Gauteng",
      monthlyCostMinor: 540,
      status: "Pending",
      manufacturer: "Samsung",
      model: "Galaxy A54",
    },
    {
      service: "Mobile plan",
      carrier: "MTN",
      numberOrCircuit: "+27 82 660 3314",
      assignedTo: "Annelize Fourie",
      location: "Pretoria",
      monthlyCostMinor: 680,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
  ];
}

/** Representative telecom register rows for empty workspaces (amounts use workspace reporting currency). */
export function buildTechnologyTelecomStarterCatalogue(): StarterRow[] {
  const rows: StarterRow[] = [
    {
      service: "Office fibre",
      carrier: "BT Business",
      numberOrCircuit: "BT-MAN-NST-8842 · 1 Gbps symmetrical",
      assignedTo: "Manchester HQ",
      location: "Manchester",
      monthlyCostMinor: 520,
      status: "Active",
    },
    {
      service: "Office fibre",
      carrier: "Virgin Media Business",
      numberOrCircuit: "VM-BRI-NST-3291 · 500 Mbps",
      assignedTo: "Bristol office",
      location: "Bristol",
      monthlyCostMinor: 315,
      status: "Active",
    },
    {
      service: "Office fibre",
      carrier: "AT&T Business",
      numberOrCircuit: "ATT-AUS-NST-6610 · 1 Gbps",
      assignedTo: "Austin office",
      location: "Austin",
      monthlyCostMinor: 445,
      status: "Active",
    },
    {
      service: "Mobile plan",
      carrier: "EE",
      numberOrCircuit: "+44 7700 901101",
      assignedTo: "Daniel Cooper",
      location: "Manchester",
      monthlyCostMinor: 78,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15 Pro",
    },
    {
      service: "Mobile plan",
      carrier: "Vodafone",
      numberOrCircuit: "+44 7700 901102",
      assignedTo: "Marcus Morgan",
      location: "Manchester",
      monthlyCostMinor: 72,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15",
    },
    {
      service: "Mobile plan",
      carrier: "EE",
      numberOrCircuit: "+44 7700 901103",
      assignedTo: "Hannah Reed",
      location: "Manchester",
      monthlyCostMinor: 68,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
    {
      service: "Mobile plan",
      carrier: "O2",
      numberOrCircuit: "+44 7700 901104",
      assignedTo: "Harry Shah",
      location: "Manchester",
      monthlyCostMinor: 76,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15 Pro",
    },
    {
      service: "Mobile plan",
      carrier: "EE",
      numberOrCircuit: "+44 7700 901105",
      assignedTo: "Emily Hughes",
      location: "Manchester",
      monthlyCostMinor: 65,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15",
    },
    {
      service: "Mobile plan",
      carrier: "Vodafone",
      numberOrCircuit: "+44 7700 901106",
      assignedTo: "Oliver Foster",
      location: "Manchester",
      monthlyCostMinor: 54,
      status: "Active",
      manufacturer: "Samsung",
      model: "Galaxy S24",
    },
    {
      service: "Mobile plan",
      carrier: "AT&T",
      numberOrCircuit: "+1 512 555 0142",
      assignedTo: "Oliver Price",
      location: "Austin",
      monthlyCostMinor: 66,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
    {
      service: "Mobile plan",
      carrier: "AT&T",
      numberOrCircuit: "+1 512 555 0143",
      assignedTo: "Elena Hughes",
      location: "Austin",
      monthlyCostMinor: 58,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
  ];

  return rows;
}
