import type { TechnologyTelecomServiceInput } from "@/lib/technology-telecom/types";

type StarterRow = TechnologyTelecomServiceInput & { location: string };

/** Representative telecom register rows for empty workspaces (amounts use workspace reporting currency). */
export function buildTechnologyTelecomStarterCatalogue(): StarterRow[] {
  const rows: StarterRow[] = [
    {
      service: "Office fibre",
      carrier: "BT Business",
      numberOrCircuit: "BT-MAN-NST-8842 · 1 Gbps symmetrical",
      assignedTo: "Manchester HQ",
      location: "Manchester",
      monthlyCostMinor: 520,
      status: "Active",
    },
    {
      service: "Office fibre",
      carrier: "Virgin Media Business",
      numberOrCircuit: "VM-BRI-NST-3291 · 500 Mbps",
      assignedTo: "Bristol office",
      location: "Bristol",
      monthlyCostMinor: 315,
      status: "Active",
    },
    {
      service: "Office fibre",
      carrier: "AT&T Business",
      numberOrCircuit: "ATT-AUS-NST-6610 · 1 Gbps",
      assignedTo: "Austin office",
      location: "Austin",
      monthlyCostMinor: 445,
      status: "Active",
    },
    {
      service: "Mobile plan",
      carrier: "EE",
      numberOrCircuit: "+44 7700 901101",
      assignedTo: "Daniel Cooper",
      location: "Manchester",
      monthlyCostMinor: 78,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15 Pro",
    },
    {
      service: "Mobile plan",
      carrier: "Vodafone",
      numberOrCircuit: "+44 7700 901102",
      assignedTo: "Marcus Morgan",
      location: "Manchester",
      monthlyCostMinor: 72,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15",
    },
    {
      service: "Mobile plan",
      carrier: "EE",
      numberOrCircuit: "+44 7700 901103",
      assignedTo: "Hannah Reed",
      location: "Manchester",
      monthlyCostMinor: 68,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
    {
      service: "Mobile plan",
      carrier: "O2",
      numberOrCircuit: "+44 7700 901104",
      assignedTo: "Harry Shah",
      location: "Manchester",
      monthlyCostMinor: 76,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15 Pro",
    },
    {
      service: "Mobile plan",
      carrier: "EE",
      numberOrCircuit: "+44 7700 901105",
      assignedTo: "Emily Hughes",
      location: "Manchester",
      monthlyCostMinor: 65,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 15",
    },
    {
      service: "Mobile plan",
      carrier: "Vodafone",
      numberOrCircuit: "+44 7700 901106",
      assignedTo: "Oliver Foster",
      location: "Manchester",
      monthlyCostMinor: 54,
      status: "Active",
      manufacturer: "Samsung",
      model: "Galaxy S24",
    },
    {
      service: "Mobile plan",
      carrier: "AT&T",
      numberOrCircuit: "+1 512 555 0142",
      assignedTo: "Oliver Price",
      location: "Austin",
      monthlyCostMinor: 66,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
    {
      service: "Mobile plan",
      carrier: "AT&T",
      numberOrCircuit: "+1 512 555 0143",
      assignedTo: "Elena Hughes",
      location: "Austin",
      monthlyCostMinor: 58,
      status: "Active",
      manufacturer: "Apple",
      model: "iPhone 14",
    },
  ];

  return rows;
}
