/**
 * OnwardAir HR operations fixtures — leave, recruitment, performance, reports.
 * Employee names align with onwardair.tech OUR TEAM (see hr-team-data.ts).
 */

import { emptyHrReportFilters, type HrSavedReport } from "@/lib/hr-reports-data";
import type { HrLeaveBalance, HrLeaveRequest, HrPublicHoliday } from "@/lib/hr-leave-data";
import {
  emptyOfferDetails,
  type HrCandidate,
  type HrVacancy,
} from "@/lib/hr-recruitment-data";
import {
  blankCompetencyScores,
  blankQuestionResponses,
  type HrPerformanceObjective,
  type HrPerformanceReview,
} from "@/lib/hr-performance-data";

function isoDaysFromNow(offset: number) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

const SCOTT = {
  id: "oa-hr-01",
  name: "Scott Parazynski, MD",
  role: "Founder, CEO",
  department: "Leadership",
};
const BRIAN = {
  id: "oa-hr-02",
  name: "Brian Whiteside",
  role: "COO",
  department: "Leadership",
};
const CAROLYN = {
  id: "oa-hr-04",
  name: "Carolyn Scott",
  role: "Senior Director of Marketing",
  department: "Marketing",
};
const DAN = {
  id: "oa-hr-05",
  name: "Dan Wax",
  role: "Director of Supply Chain",
  department: "Operations",
};
const MIKE = {
  id: "oa-hr-06",
  name: "Mike Teeter",
  role: "Senior Mechanical Engineer",
  department: "Engineering",
};
const KEVEN = {
  id: "oa-hr-07",
  name: "Keven Coates",
  role: "Senior Electrical Engineer",
  department: "Engineering",
};
const JON = {
  id: "oa-hr-08",
  name: "Jon Fenner",
  role: "Senior R&D Engineer",
  department: "Engineering",
};
const DAVID = {
  id: "oa-hr-09",
  name: "David Colling",
  role: "Senior Aerospace Engineer",
  department: "Engineering",
};

function ratedResponses(scores: number[]) {
  return blankQuestionResponses().map((item, index) => ({
    ...item,
    rating: (scores[index] ?? 4) as 1 | 2 | 3 | 4 | 5,
    managerComments: index % 6 === 0 ? "Strong contribution to Vertex programme." : "",
    employeeComments: index % 8 === 0 ? "Aligned — focus area for next cycle." : "",
  }));
}

function competencies(scores: number[], prefix: string) {
  return blankCompetencyScores().map((item, index) => ({
    ...item,
    id: `${prefix}-${index}`,
    score: (scores[index] ?? 4) as 1 | 2 | 3 | 4 | 5,
    notes: index === 0 ? "Key strength for OnwardAir engineering" : "",
  }));
}

/** Three open roles — hiring managers from OnwardAir leadership. */
export function buildOnwardAirRecruitmentVacancies(): HrVacancy[] {
  return [
    {
      id: "oa-vac-1",
      title: "Senior Flight Controls Engineer",
      department: "Engineering",
      location: "Houston, TX",
      employmentType: "Full time",
      hiringManager: BRIAN.name,
      status: "open",
      openedAt: isoDaysFromNow(-18),
      targetStartDate: isoDaysFromNow(45),
      closingDate: isoDaysFromNow(28),
      headcount: 1,
      salaryBand: "$145–175k",
      description:
        "Own flight-control software and 4-DoF hand-controller integration for Vertex VTOL™ — simulation, HIL, and flight-test support through first hover demo.",
      requirements:
        "Flight controls or avionics background · C++/Python or MATLAB · experience with VTOL or UAV systems preferred · Houston-based or willing to relocate",
    },
    {
      id: "oa-vac-2",
      title: "Battery & Power Systems Engineer",
      department: "Engineering",
      location: "Houston, TX",
      employmentType: "Full time",
      hiringManager: DAN.name,
      status: "open",
      openedAt: isoDaysFromNow(-12),
      targetStartDate: isoDaysFromNow(40),
      closingDate: isoDaysFromNow(21),
      headcount: 1,
      salaryBand: "$135–165k",
      description:
        "Lead pack architecture and supplier diligence for FLEX Pod™ energy modules — thermal, BMS, and certification pathway support.",
      requirements:
        "Lithium pack / BMS experience · supplier management · aerospace or EV power systems · US work authorisation",
    },
    {
      id: "oa-vac-3",
      title: "FAA Certification Programme Manager",
      department: "Operations",
      location: "Houston, TX / Hybrid",
      employmentType: "Full time",
      hiringManager: SCOTT.name,
      status: "open",
      openedAt: isoDaysFromNow(-7),
      targetStartDate: isoDaysFromNow(35),
      closingDate: isoDaysFromNow(24),
      headcount: 1,
      salaryBand: "$150–185k",
      description:
        "Drive Vertex VTOL experimental / type certification plan with counsel and FAA interactions; keep board and engineering aligned on milestones.",
      requirements:
        "FAA Part 21 / Part 23 or experimental aircraft experience · programme management · clear written communication · aviation regulatory network preferred",
    },
  ];
}

/** Fake candidates across hiring stages for the three open OnwardAir roles. */
export function buildOnwardAirRecruitmentCandidates(): HrCandidate[] {
  return [
    {
      id: "oa-cand-1",
      name: "Priya Anand",
      email: "priya.anand@example.com",
      phone: "+1 713 555 0142",
      vacancyId: "oa-vac-1",
      role: "Senior Flight Controls Engineer",
      department: "Engineering",
      location: "Houston, TX",
      stage: "interview",
      rating: 4,
      interviewer: BRIAN.name,
      recruiter: BRIAN.name,
      expectedSalary: "$160k",
      availability: "3 weeks notice",
      source: "LinkedIn",
      appliedAt: isoDaysFromNow(-16),
      notes: "Strong MATLAB / Simulink flight-control background; UAV experience.",
      cvLabel: "Priya_Anand_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "oa-int-1a",
          scheduledAt: `${isoDaysFromNow(-6)}T10:00`,
          type: "video",
          interviewer: BRIAN.name,
          interviewers: BRIAN.name,
          status: "completed",
          outcome: "pass",
          rating: 4,
          strengths: "Clear control-law intuition; calm under technical grilling.",
          weaknesses: "Less exposure to manned VTOL certification constraints.",
          feedback: "Advance to panel with Mike Teeter.",
          notes: "Recommend onsite / panel.",
          recommendation: "yes",
        },
        {
          id: "oa-int-1b",
          scheduledAt: `${isoDaysFromNow(3)}T14:00`,
          type: "panel",
          interviewer: `${BRIAN.name} + Mike Teeter`,
          interviewers: `${BRIAN.name}, Mike Teeter`,
          status: "scheduled",
          outcome: "pending",
          rating: null,
          strengths: "",
          weaknesses: "",
          feedback: "",
          notes: "Houston HQ panel.",
          recommendation: null,
        },
      ],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-1a", at: isoDaysFromNow(-16), label: "Application received", detail: "Via LinkedIn" },
        { id: "oa-tl-1b", at: isoDaysFromNow(-12), label: "Screening complete", detail: "Moved to interview" },
        { id: "oa-tl-1c", at: isoDaysFromNow(-6), label: "First interview", detail: `Video with ${BRIAN.name}` },
        { id: "oa-tl-1d", at: isoDaysFromNow(3), label: "Panel interview scheduled", detail: "Houston HQ" },
      ],
    },
    {
      id: "oa-cand-2",
      name: "Marcus Hale",
      email: "marcus.hale@example.com",
      phone: "+1 832 555 0198",
      vacancyId: "oa-vac-1",
      role: "Senior Flight Controls Engineer",
      department: "Engineering",
      location: "Austin, TX",
      stage: "screening",
      rating: 3,
      interviewer: BRIAN.name,
      recruiter: BRIAN.name,
      expectedSalary: "$155k",
      availability: "Immediate",
      source: "Referral",
      appliedAt: isoDaysFromNow(-9),
      notes: "Referral from network; autopilot software at prior startup.",
      cvLabel: "Marcus_Hale_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "oa-int-2a",
          scheduledAt: `${isoDaysFromNow(1)}T11:00`,
          type: "phone",
          interviewer: BRIAN.name,
          interviewers: BRIAN.name,
          status: "scheduled",
          outcome: "pending",
          rating: null,
          strengths: "",
          weaknesses: "",
          feedback: "",
          notes: "Phone screen.",
          recommendation: null,
        },
      ],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-2a", at: isoDaysFromNow(-9), label: "Application received", detail: "Employee referral" },
        { id: "oa-tl-2b", at: isoDaysFromNow(-5), label: "Moved to screening", detail: "Recruiter triage complete" },
        { id: "oa-tl-2c", at: isoDaysFromNow(1), label: "Phone screen scheduled", detail: BRIAN.name },
      ],
    },
    {
      id: "oa-cand-3",
      name: "Elena Vargas",
      email: "elena.vargas@example.com",
      phone: "+1 281 555 0174",
      vacancyId: "oa-vac-1",
      role: "Senior Flight Controls Engineer",
      department: "Engineering",
      location: "Houston, TX",
      stage: "applications",
      rating: 0,
      interviewer: "",
      recruiter: BRIAN.name,
      expectedSalary: "$148k",
      availability: "4 weeks notice",
      source: "Careers page",
      appliedAt: isoDaysFromNow(-3),
      notes: "New application — aerospace controls MS.",
      cvLabel: "Elena_Vargas_CV.pdf",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-3a", at: isoDaysFromNow(-3), label: "Application received", detail: "Via careers page" },
      ],
    },
    {
      id: "oa-cand-4",
      name: "James Okonkwo",
      email: "james.okonkwo@example.com",
      phone: "+1 713 555 0119",
      vacancyId: "oa-vac-2",
      role: "Battery & Power Systems Engineer",
      department: "Engineering",
      location: "Houston, TX",
      stage: "offer",
      rating: 5,
      interviewer: DAN.name,
      recruiter: DAN.name,
      expectedSalary: "$158k",
      availability: "2 weeks notice",
      source: "Agency",
      appliedAt: isoDaysFromNow(-28),
      notes: "EV pack lead at prior OEM; strong BMS depth.",
      cvLabel: "James_Okonkwo_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "oa-int-4a",
          scheduledAt: `${isoDaysFromNow(-18)}T09:30`,
          type: "video",
          interviewer: DAN.name,
          interviewers: DAN.name,
          status: "completed",
          outcome: "pass",
          rating: 5,
          strengths: "Pack thermal and supplier diligence excellence.",
          weaknesses: "Limited aviation certification exposure.",
          feedback: "Clear hire for power systems.",
          notes: "Advance to offer.",
          recommendation: "strong_yes",
        },
        {
          id: "oa-int-4b",
          scheduledAt: `${isoDaysFromNow(-10)}T13:00`,
          type: "onsite",
          interviewer: `${DAN.name} + Keven Coates`,
          interviewers: `${DAN.name}, Keven Coates`,
          status: "completed",
          outcome: "pass",
          rating: 5,
          strengths: "Hands-on BMS debugging; clear communicator.",
          weaknesses: "None material.",
          feedback: "Team consensus to offer.",
          notes: "Houston lab tour completed.",
          recommendation: "strong_yes",
        },
      ],
      offer: {
        status: "sent",
        salary: "$158,000",
        startDate: isoDaysFromNow(21),
        employmentType: "Full time",
        notes: "Standard benefits + ESOP grant per band.",
        sentAt: isoDaysFromNow(-2),
      },
      timeline: [
        { id: "oa-tl-4a", at: isoDaysFromNow(-28), label: "Application received", detail: "Agency intro" },
        { id: "oa-tl-4b", at: isoDaysFromNow(-22), label: "Screening complete", detail: "Moved to interview" },
        { id: "oa-tl-4c", at: isoDaysFromNow(-18), label: "First interview", detail: DAN.name },
        { id: "oa-tl-4d", at: isoDaysFromNow(-10), label: "Onsite interview", detail: "Lab tour + Keven Coates" },
        { id: "oa-tl-4e", at: isoDaysFromNow(-2), label: "Offer sent", detail: "$158k · start in 3 weeks" },
      ],
    },
    {
      id: "oa-cand-5",
      name: "Sofia Rahman",
      email: "sofia.rahman@example.com",
      phone: "+1 346 555 0160",
      vacancyId: "oa-vac-2",
      role: "Battery & Power Systems Engineer",
      department: "Engineering",
      location: "Dallas, TX",
      stage: "screening",
      rating: 3,
      interviewer: DAN.name,
      recruiter: DAN.name,
      expectedSalary: "$145k",
      availability: "1 month notice",
      source: "Job board",
      appliedAt: isoDaysFromNow(-11),
      notes: "Cell chemistry background; lighter systems integration.",
      cvLabel: "Sofia_Rahman_CV.pdf",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-5a", at: isoDaysFromNow(-11), label: "Application received", detail: "Via job board" },
        { id: "oa-tl-5b", at: isoDaysFromNow(-7), label: "Moved to screening", detail: "Awaiting phone screen" },
      ],
    },
    {
      id: "oa-cand-6",
      name: "Tom Bradley",
      email: "tom.bradley@example.com",
      phone: "+1 512 555 0133",
      vacancyId: "oa-vac-2",
      role: "Battery & Power Systems Engineer",
      department: "Engineering",
      location: "Houston, TX",
      stage: "applications",
      rating: 0,
      interviewer: "",
      recruiter: DAN.name,
      expectedSalary: "$140k",
      availability: "Immediate",
      source: "Careers page",
      appliedAt: isoDaysFromNow(-2),
      notes: "Early-career pack engineer.",
      cvLabel: "Tom_Bradley_CV.pdf",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-6a", at: isoDaysFromNow(-2), label: "Application received", detail: "Via careers page" },
      ],
    },
    {
      id: "oa-cand-7",
      name: "Rachel Nguyen",
      email: "rachel.nguyen@example.com",
      phone: "+1 202 555 0188",
      vacancyId: "oa-vac-3",
      role: "FAA Certification Programme Manager",
      department: "Operations",
      location: "Houston, TX / Hybrid",
      stage: "interview",
      rating: 4,
      interviewer: SCOTT.name,
      recruiter: SCOTT.name,
      expectedSalary: "$175k",
      availability: "6 weeks notice",
      source: "Direct approach",
      appliedAt: isoDaysFromNow(-14),
      notes: "Former Part 23 programme lead; strong FAA relationships.",
      cvLabel: "Rachel_Nguyen_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "oa-int-7a",
          scheduledAt: `${isoDaysFromNow(-4)}T16:00`,
          type: "video",
          interviewer: SCOTT.name,
          interviewers: SCOTT.name,
          status: "completed",
          outcome: "pass",
          rating: 4,
          strengths: "Certification roadmap fluency; credible with counsel.",
          weaknesses: "Less eVTOL-specific exposure.",
          feedback: "Strong cultural fit; schedule panel with Brian.",
          notes: "Follow up with Whiteside.",
          recommendation: "yes",
        },
        {
          id: "oa-int-7b",
          scheduledAt: `${isoDaysFromNow(5)}T10:30`,
          type: "panel",
          interviewer: `${SCOTT.name} + ${BRIAN.name}`,
          interviewers: `${SCOTT.name}, ${BRIAN.name}`,
          status: "scheduled",
          outcome: "pending",
          rating: null,
          strengths: "",
          weaknesses: "",
          feedback: "",
          notes: "Certification pathway deep-dive.",
          recommendation: null,
        },
      ],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-7a", at: isoDaysFromNow(-14), label: "Application received", detail: "Direct approach" },
        { id: "oa-tl-7b", at: isoDaysFromNow(-10), label: "Screening complete", detail: "Moved to interview" },
        { id: "oa-tl-7c", at: isoDaysFromNow(-4), label: "First interview", detail: SCOTT.name },
        { id: "oa-tl-7d", at: isoDaysFromNow(5), label: "Panel interview scheduled", detail: "Scott + Brian" },
      ],
    },
    {
      id: "oa-cand-8",
      name: "David Chen",
      email: "david.chen@example.com",
      phone: "+1 703 555 0155",
      vacancyId: "oa-vac-3",
      role: "FAA Certification Programme Manager",
      department: "Operations",
      location: "Washington, DC / Hybrid",
      stage: "applications",
      rating: 0,
      interviewer: "",
      recruiter: SCOTT.name,
      expectedSalary: "$180k",
      availability: "2 months notice",
      source: "LinkedIn",
      appliedAt: isoDaysFromNow(-5),
      notes: "DER background; interested in hybrid remote.",
      cvLabel: "David_Chen_CV.pdf",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-8a", at: isoDaysFromNow(-5), label: "Application received", detail: "Via LinkedIn" },
      ],
    },
    {
      id: "oa-cand-9",
      name: "Amanda Brooks",
      email: "amanda.brooks@example.com",
      phone: "+1 404 555 0121",
      vacancyId: "oa-vac-3",
      role: "FAA Certification Programme Manager",
      department: "Operations",
      location: "Atlanta, GA",
      stage: "role_approved",
      rating: 0,
      interviewer: "",
      recruiter: SCOTT.name,
      expectedSalary: "",
      availability: "Unknown",
      source: "Referral",
      appliedAt: isoDaysFromNow(-1),
      notes: "Warm intro — CV pending.",
      cvLabel: "",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "oa-tl-9a", at: isoDaysFromNow(-1), label: "Pipeline created", detail: "Referral — awaiting materials" },
      ],
    },
    {
      id: "oa-cand-10",
      name: "Chris Delgado",
      email: "chris.delgado@example.com",
      phone: "+1 210 555 0190",
      vacancyId: "oa-vac-1",
      role: "Senior Flight Controls Engineer",
      department: "Engineering",
      location: "San Antonio, TX",
      stage: "accepted",
      rating: 4,
      interviewer: BRIAN.name,
      recruiter: BRIAN.name,
      expectedSalary: "$152k",
      availability: "Start confirmed",
      source: "Referral",
      appliedAt: isoDaysFromNow(-45),
      notes: "Accepted offer for related contractor conversion track — kept for pipeline history.",
      cvLabel: "Chris_Delgado_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "oa-int-10a",
          scheduledAt: `${isoDaysFromNow(-30)}T11:00`,
          type: "video",
          interviewer: BRIAN.name,
          interviewers: BRIAN.name,
          status: "completed",
          outcome: "pass",
          rating: 4,
          strengths: "Flight-test software experience.",
          weaknesses: "Availability delayed.",
          feedback: "Good hire when timing aligned.",
          notes: "",
          recommendation: "yes",
        },
      ],
      offer: {
        status: "accepted",
        salary: "$152,000",
        startDate: isoDaysFromNow(14),
        employmentType: "Full time",
        notes: "Accepted — onboarding pack issued.",
        sentAt: isoDaysFromNow(-8),
      },
      timeline: [
        { id: "oa-tl-10a", at: isoDaysFromNow(-45), label: "Application received", detail: "Referral" },
        { id: "oa-tl-10b", at: isoDaysFromNow(-30), label: "Interview complete", detail: BRIAN.name },
        { id: "oa-tl-10c", at: isoDaysFromNow(-8), label: "Offer sent", detail: "$152k" },
        { id: "oa-tl-10d", at: isoDaysFromNow(-5), label: "Offer accepted", detail: "Start in 2 weeks" },
      ],
    },
  ];
}

export function buildOnwardAirLeaveRequests(): HrLeaveRequest[] {
  return [
    {
      id: "oa-leave-1",
      employeeId: MIKE.id,
      employeeName: MIKE.name,
      department: MIKE.department,
      location: "Houston",
      role: MIKE.role,
      managerName: BRIAN.name,
      type: "annual",
      startDate: isoDaysFromNow(-1),
      endDate: isoDaysFromNow(3),
      days: 4,
      status: "approved",
      notes: "Family trip",
      requestedAt: isoDaysFromNow(-20),
      decidedAt: isoDaysFromNow(-18),
    },
    {
      id: "oa-leave-2",
      employeeId: CAROLYN.id,
      employeeName: CAROLYN.name,
      department: CAROLYN.department,
      location: "Houston",
      role: CAROLYN.role,
      managerName: SCOTT.name,
      type: "annual",
      startDate: isoDaysFromNow(8),
      endDate: isoDaysFromNow(12),
      days: 5,
      status: "approved",
      notes: "Summer break",
      requestedAt: isoDaysFromNow(-14),
      decidedAt: isoDaysFromNow(-12),
    },
    {
      id: "oa-leave-3",
      employeeId: KEVEN.id,
      employeeName: KEVEN.name,
      department: KEVEN.department,
      location: "Houston",
      role: KEVEN.role,
      managerName: BRIAN.name,
      type: "training",
      startDate: isoDaysFromNow(5),
      endDate: isoDaysFromNow(6),
      days: 2,
      status: "approved",
      notes: "Battery systems workshop — Austin",
      requestedAt: isoDaysFromNow(-6),
      decidedAt: isoDaysFromNow(-5),
    },
    {
      id: "oa-leave-4",
      employeeId: JON.id,
      employeeName: JON.name,
      department: JON.department,
      location: "Houston",
      role: JON.role,
      managerName: BRIAN.name,
      type: "sick",
      startDate: isoDaysFromNow(0),
      endDate: isoDaysFromNow(1),
      days: 2,
      status: "approved",
      notes: "Recovery",
      requestedAt: isoDaysFromNow(0),
      decidedAt: isoDaysFromNow(0),
    },
    {
      id: "oa-leave-5",
      employeeId: DAVID.id,
      employeeName: DAVID.name,
      department: DAVID.department,
      location: "Houston",
      role: DAVID.role,
      managerName: BRIAN.name,
      type: "annual",
      startDate: isoDaysFromNow(18),
      endDate: isoDaysFromNow(22),
      days: 5,
      status: "pending",
      notes: "Requested for late August",
      requestedAt: isoDaysFromNow(-2),
      decidedAt: null,
    },
    {
      id: "oa-leave-6",
      employeeId: DAN.id,
      employeeName: DAN.name,
      department: DAN.department,
      location: "Houston",
      role: DAN.role,
      managerName: SCOTT.name,
      type: "remote",
      startDate: isoDaysFromNow(3),
      endDate: isoDaysFromNow(3),
      days: 1,
      status: "approved",
      notes: "Supplier site visit follow-up (WFH)",
      requestedAt: isoDaysFromNow(-4),
      decidedAt: isoDaysFromNow(-3),
    },
  ];
}

export function buildOnwardAirLeaveBalances(): HrLeaveBalance[] {
  return [
    {
      employeeId: MIKE.id,
      employeeName: MIKE.name,
      department: MIKE.department,
      location: "Houston",
      annualAllocated: 20,
      annualTaken: 8,
      sickTaken: 1,
      trainingTaken: 0,
    },
    {
      employeeId: CAROLYN.id,
      employeeName: CAROLYN.name,
      department: CAROLYN.department,
      location: "Houston",
      annualAllocated: 20,
      annualTaken: 5,
      sickTaken: 0,
      trainingTaken: 1,
    },
    {
      employeeId: KEVEN.id,
      employeeName: KEVEN.name,
      department: KEVEN.department,
      location: "Houston",
      annualAllocated: 20,
      annualTaken: 6,
      sickTaken: 2,
      trainingTaken: 2,
    },
    {
      employeeId: JON.id,
      employeeName: JON.name,
      department: JON.department,
      location: "Houston",
      annualAllocated: 20,
      annualTaken: 4,
      sickTaken: 2,
      trainingTaken: 0,
    },
    {
      employeeId: DAVID.id,
      employeeName: DAVID.name,
      department: DAVID.department,
      location: "Houston",
      annualAllocated: 20,
      annualTaken: 3,
      sickTaken: 0,
      trainingTaken: 1,
    },
    {
      employeeId: DAN.id,
      employeeName: DAN.name,
      department: DAN.department,
      location: "Houston",
      annualAllocated: 20,
      annualTaken: 7,
      sickTaken: 0,
      trainingTaken: 0,
    },
  ];
}

export function buildOnwardAirPublicHolidays(): HrPublicHoliday[] {
  return [
    {
      id: "oa-hol-labor",
      name: "Labor Day",
      date: "2026-09-07",
      calendar: "United States (Federal)",
    },
    {
      id: "oa-hol-thanksgiving",
      name: "Thanksgiving Day",
      date: "2026-11-26",
      calendar: "United States (Federal)",
    },
    {
      id: "oa-hol-christmas",
      name: "Christmas Day",
      date: "2026-12-25",
      calendar: "United States (Federal)",
    },
    {
      id: "oa-hol-ny",
      name: "New Year's Day",
      date: "2027-01-01",
      calendar: "United States (Federal)",
    },
  ];
}

export function buildOnwardAirPerformanceReviews(): HrPerformanceReview[] {
  return [
    {
      id: "oa-rev-brian",
      employeeId: BRIAN.id,
      employeeName: BRIAN.name,
      department: BRIAN.department,
      role: BRIAN.role,
      managerName: SCOTT.name,
      reviewPeriod: "H1 2026",
      status: "completed",
      overallRating: 5,
      strengths: "Programme discipline across engineering and ops; clear Seed milestone ownership.",
      areasForImprovement: "Protect CEO bandwidth during certification counsel cycles.",
      trainingRecommendations: "FAA programme leadership intensive",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "increase",
      managerRecommendation: "retain",
      employeeGoals: "Deliver first powered hover demo path and hold engineering hire plan.",
      nextReviewDate: isoDaysFromNow(100),
      summary: "Excellent half — Vertex engineering cadence and supplier diligence on track.",
      responses: ratedResponses([5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5]),
      objectives: [
        {
          id: "oa-obj-brian-1",
          title: "Hover demo readiness",
          description: "Keep flight-controls and airframe gates green through Q3.",
          progressPercent: 78,
          dueDate: isoDaysFromNow(40),
          status: "on_track",
          weight: 45,
          owner: BRIAN.name,
          scope: "employee",
          employeeId: BRIAN.id,
          employeeName: BRIAN.name,
          department: BRIAN.department,
        },
      ],
      competencies: competencies([5, 5, 4, 5, 5, 4, 5, 5, 4, 5], "oa-comp-brian"),
      developmentPlan: [
        {
          id: "oa-dev-brian-1",
          focus: "Certification leadership",
          action: "Lead September board update on FAA pathway options",
          owner: BRIAN.name,
          targetDate: isoDaysFromNow(30),
          status: "in_progress",
          kind: "stretch",
          budget: "$2,500",
          nextReviewDate: isoDaysFromNow(15),
        },
      ],
      createdAt: isoDaysFromNow(-60),
      updatedAt: isoDaysFromNow(-10),
      submittedAt: isoDaysFromNow(-20),
      approvedAt: isoDaysFromNow(-12),
      completedAt: isoDaysFromNow(-10),
      reviewType: "annual",
      priority: "high",
      dueDate: isoDaysFromNow(-15),
      challenges: "Parallel Seed outreach and engineering hiring.",
      achievements: "Prototype build plan locked; ESOP messaging aligned at 15% FD.",
      employeeSelfAssessment: "Proud of engineering cohesion — need deeper FAA bandwidth.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: true,
      careerAspirations: "Continue as COO with broader programme P&L ownership.",
      managerCareerComments: "Clear successor for operating leadership.",
      signedOffManager: true,
      signedOffEmployee: true,
    },
    {
      id: "oa-rev-mike",
      employeeId: MIKE.id,
      employeeName: MIKE.name,
      department: MIKE.department,
      role: MIKE.role,
      managerName: BRIAN.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 4,
      strengths: "Mechanical architecture for FLEX Pod interfaces; calm under test pressure.",
      areasForImprovement: "Documentation cadence for supplier packs.",
      trainingRecommendations: "DFMEA workshop",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "retain",
      employeeGoals: "Complete Pod mechanical ICD and support first integration fixture.",
      nextReviewDate: isoDaysFromNow(90),
      summary: "Solid contributor — keep documentation tempo with hire plan.",
      responses: ratedResponses([4, 5, 4, 4, 5, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 5]),
      objectives: [
        {
          id: "oa-obj-mike-1",
          title: "FLEX Pod ICD",
          description: "Lock mechanical interfaces for Q3 supplier RFQ.",
          progressPercent: 65,
          dueDate: isoDaysFromNow(25),
          status: "on_track",
          weight: 50,
          owner: MIKE.name,
          scope: "employee",
          employeeId: MIKE.id,
          employeeName: MIKE.name,
          department: MIKE.department,
        },
      ],
      competencies: competencies([4, 5, 4, 4, 5, 4, 4, 4, 5, 4], "oa-comp-mike"),
      developmentPlan: [
        {
          id: "oa-dev-mike-1",
          focus: "Technical writing",
          action: "Publish ICD revision pack for board appendix",
          owner: MIKE.name,
          targetDate: isoDaysFromNow(35),
          status: "planned",
          kind: "training",
          budget: "$800",
          nextReviewDate: isoDaysFromNow(20),
        },
      ],
      createdAt: isoDaysFromNow(-40),
      updatedAt: isoDaysFromNow(-3),
      submittedAt: isoDaysFromNow(-3),
      approvedAt: null,
      completedAt: null,
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(7),
      challenges: "Supplier lead times on machined fixtures.",
      achievements: "Prototype jig signed off.",
      employeeSelfAssessment: "Happy with mechanical progress — want clearer doc templates.",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Lead mechanical systems for production readiness.",
      managerCareerComments: "Strong individual contributor; grow leadership next cycle.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "oa-rev-carolyn",
      employeeId: CAROLYN.id,
      employeeName: CAROLYN.name,
      department: CAROLYN.department,
      role: CAROLYN.role,
      managerName: SCOTT.name,
      reviewPeriod: "H1 2026",
      status: "draft",
      overallRating: null,
      strengths: "Brand narrative for Vertex / FLEX Pods; investor event polish.",
      areasForImprovement: "Tighten campaign metrics for Seed pipeline support.",
      trainingRecommendations: "B2B demand-gen analytics",
      promotionRecommendation: null,
      salaryReviewRecommendation: "hold",
      managerRecommendation: "retain",
      employeeGoals: "Support Seed deck v1.5 distribution and Q3 investor day.",
      nextReviewDate: isoDaysFromNow(60),
      summary: "Review in progress — marketing support to fundraising strong.",
      responses: blankQuestionResponses(),
      objectives: [
        {
          id: "oa-obj-carolyn-1",
          title: "Investor day narrative",
          description: "Own storyboard and collateral for September investor sessions.",
          progressPercent: 40,
          dueDate: isoDaysFromNow(35),
          status: "on_track",
          weight: 40,
          owner: CAROLYN.name,
          scope: "employee",
          employeeId: CAROLYN.id,
          employeeName: CAROLYN.name,
          department: CAROLYN.department,
        },
      ],
      competencies: blankCompetencyScores(),
      developmentPlan: [],
      createdAt: isoDaysFromNow(-15),
      updatedAt: isoDaysFromNow(-1),
      submittedAt: null,
      approvedAt: null,
      completedAt: null,
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(14),
      challenges: "Balancing brand work with Seed outreach calendar.",
      achievements: "Pitch narrative refresh shipped with deck v1.5.",
      employeeSelfAssessment: "",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: false,
      careerAspirations: "Broader GTM ownership as commercial ops scale.",
      managerCareerComments: "",
      signedOffManager: false,
      signedOffEmployee: false,
    },
  ];
}

export function buildOnwardAirPerformanceGoals(): HrPerformanceObjective[] {
  return [
    {
      id: "oa-goal-org-1",
      title: "Seed raise progress",
      description: "Advance Seed pipeline toward $5.0M target through Q4 2026.",
      progressPercent: 35,
      dueDate: isoDaysFromNow(120),
      status: "on_track",
      weight: 30,
      owner: SCOTT.name,
      scope: "organisation",
      employeeId: undefined,
      employeeName: undefined,
      department: "Leadership",
    },
    {
      id: "oa-goal-org-2",
      title: "First hover demo path",
      description: "Hold engineering gates for powered hover demonstration readiness.",
      progressPercent: 55,
      dueDate: isoDaysFromNow(90),
      status: "on_track",
      weight: 40,
      owner: BRIAN.name,
      scope: "organisation",
      employeeId: undefined,
      employeeName: undefined,
      department: "Engineering",
    },
    {
      id: "oa-goal-org-3",
      title: "Certification pathway clarity",
      description: "Board-ready FAA pathway recommendation with counsel.",
      progressPercent: 45,
      dueDate: isoDaysFromNow(50),
      status: "on_track",
      weight: 30,
      owner: SCOTT.name,
      scope: "organisation",
      employeeId: undefined,
      employeeName: undefined,
      department: "Operations",
    },
  ];
}

export function buildOnwardAirHrReports(): HrSavedReport[] {
  return [
    {
      id: "oa-rep-1",
      name: "OnwardAir Headcount — Aug 2026",
      kind: "headcount",
      output: "excel",
      filters: emptyHrReportFilters(),
      createdAt: isoDaysFromNow(-3),
      updatedAt: isoDaysFromNow(-3),
      createdBy: BRIAN.name,
      rowCount: 12,
      previewLines: [
        "Headcount",
        "Department: All",
        "Location: Houston",
        "",
        "Segment,Count,Share",
        "Leadership,2,17%",
        "Engineering,6,50%",
        "Operations,1,8%",
        "Marketing,1,8%",
        "Finance,1,8%",
        "Other,1,8%",
      ],
    },
    {
      id: "oa-rep-2",
      name: "OnwardAir Leave Summary — YTD 2026",
      kind: "leave_summary",
      output: "pdf",
      filters: {
        ...emptyHrReportFilters(),
        location: "Houston",
        dateFrom: "2026-01-01",
        dateTo: "2026-08-04",
      },
      createdAt: isoDaysFromNow(-5),
      updatedAt: isoDaysFromNow(-5),
      createdBy: CAROLYN.name,
      rowCount: 6,
      previewLines: [
        "Leave Summary",
        "Location: Houston",
        "Period: 2026-01-01 to 2026-08-04",
        "",
        "Type,Approved days,Pending requests",
        "Annual Leave,33,1",
        "Sick Leave,5,0",
        "Training,3,0",
        "Remote,1,0",
      ],
    },
    {
      id: "oa-rep-3",
      name: "OnwardAir Recruitment Pipeline — Seed build",
      kind: "recruitment",
      output: "excel",
      filters: emptyHrReportFilters(),
      createdAt: isoDaysFromNow(-1),
      updatedAt: isoDaysFromNow(-1),
      createdBy: BRIAN.name,
      rowCount: 3,
      previewLines: [
        "Recruitment Report",
        "Department: All",
        "Location: Houston",
        "",
        "Role,Stage,Candidates,Hiring manager",
        "Senior Flight Controls Engineer,Interview,4,Brian Whiteside",
        "Battery & Power Systems Engineer,Screening,3,Dan Wax",
        "FAA Certification Programme Manager,Applications,5,Scott Parazynski, MD",
      ],
    },
  ];
}

export function buildOnwardAirHrActivity(): { id: string; at: string; label: string; detail: string }[] {
  return [
    {
      id: "oa-act-1",
      at: isoDaysFromNow(0),
      label: "Recruitment role opened",
      detail: "FAA Certification Programme Manager — Houston · Scott Parazynski",
    },
    {
      id: "oa-act-2",
      at: isoDaysFromNow(-1),
      label: "Leave approved",
      detail: "Mike Teeter — annual leave (4 days)",
    },
    {
      id: "oa-act-3",
      at: isoDaysFromNow(-3),
      label: "Performance review submitted",
      detail: "Mike Teeter — H1 2026",
    },
    {
      id: "oa-act-4",
      at: isoDaysFromNow(-7),
      label: "Recruitment role opened",
      detail: "Battery & Power Systems Engineer — Houston · Dan Wax",
    },
    {
      id: "oa-act-5",
      at: isoDaysFromNow(-12),
      label: "Performance review completed",
      detail: "Brian Whiteside — H1 2026",
    },
    {
      id: "oa-act-6",
      at: isoDaysFromNow(-18),
      label: "Recruitment role opened",
      detail: "Senior Flight Controls Engineer — Houston · Brian Whiteside",
    },
  ];
}
