/**
 * OnwardAir Project Management — internal + external portfolio fixtures.
 * Houston / USD · Vertex VTOL™ & FLEX Pods™ programme work.
 */

import type { PortfolioProject } from "@/lib/project-portfolios";

function project(
  partial: Omit<PortfolioProject, "createdAt" | "updatedAt"> & {
    createdAt?: string;
    updatedAt?: string;
  },
): PortfolioProject {
  return {
    createdAt: partial.createdAt ?? "2026-01-20T09:00:00.000Z",
    updatedAt: partial.updatedAt ?? "2026-08-01T14:30:00.000Z",
    ...partial,
  };
}

/** 15 internal programmes — running OnwardAir's own business. */
export const ONWARDAIR_INTERNAL_PROJECT_PORTFOLIO: PortfolioProject[] = [
  project({
    id: "oa-int-hover-demo",
    kind: "internal",
    name: "Vertex VTOL First Hover Demo",
    clientId: null,
    clientName: "OnwardAir",
    department: "Engineering",
    site: "Houston HQ · Flight Test",
    region: "Texas · Engineering",
    operator: "Brian Whiteside",
    projectManager: "Brian Whiteside",
    phase: "live",
    startDate: "2026-01-15",
    endDate: "2026-11-30",
    progressPct: 58,
    budgetLabel: "$1,250,000",
    stakeholders: ["Scott Parazynski", "Mike Teeter", "David Colling"],
    notes: "Path to first powered hover demonstration — flight controls, airframe, and HIL gates.",
    milestones: [
      { id: "m1", name: "HIL rig commissioned", dueDate: "2026-03-31", status: "done" },
      { id: "m2", name: "Control laws freeze v1", dueDate: "2026-06-30", status: "done" },
      { id: "m3", name: "Ground taxi complete", dueDate: "2026-09-15", status: "upcoming" },
      { id: "m4", name: "Hover demo", dueDate: "2026-11-30", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Flight-controls hire lag delaying software velocity",
        severity: "medium",
        owner: "Brian Whiteside",
      },
    ],
  }),
  project({
    id: "oa-int-flex-pod",
    kind: "internal",
    name: "FLEX Pod™ Integration Prototype",
    clientId: null,
    clientName: "OnwardAir",
    department: "Engineering",
    site: "Houston HQ · Mechanical Lab",
    region: "Texas · Engineering",
    operator: "Mike Teeter",
    projectManager: "Mike Teeter",
    phase: "live",
    startDate: "2026-02-01",
    endDate: "2026-10-15",
    progressPct: 64,
    budgetLabel: "$420,000",
    stakeholders: ["Brian Whiteside", "Dan Wax", "Jon Fenner"],
    notes: "Mechanical ICD, quick-release interfaces, and first integration fixture for modular pods.",
    milestones: [
      { id: "m1", name: "ICD draft", dueDate: "2026-04-15", status: "done" },
      { id: "m2", name: "Fixture sign-off", dueDate: "2026-07-01", status: "done" },
      { id: "m3", name: "Pod swap ≤15 min demo", dueDate: "2026-09-30", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Machined fixture lead times",
        severity: "medium",
        owner: "Mike Teeter",
      },
    ],
  }),
  project({
    id: "oa-int-battery-pack",
    kind: "internal",
    name: "Battery Pack & BMS Qualification",
    clientId: null,
    clientName: "OnwardAir",
    department: "Engineering",
    site: "Houston · Power Lab",
    region: "Texas · Engineering",
    operator: "Keven Coates",
    projectManager: "Dan Wax",
    phase: "live",
    startDate: "2026-03-01",
    endDate: "2026-12-15",
    progressPct: 41,
    budgetLabel: "$680,000",
    stakeholders: ["Dan Wax", "Keven Coates", "Brian Whiteside"],
    notes: "Pack architecture, thermal, BMS, and supplier diligence for FLEX Pod energy modules.",
    milestones: [
      { id: "m1", name: "Supplier shortlist", dueDate: "2026-05-01", status: "done" },
      { id: "m2", name: "Thermal model locked", dueDate: "2026-08-15", status: "upcoming" },
      { id: "m3", name: "Pack A sample received", dueDate: "2026-11-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Battery supplier lead time beyond prototype schedule",
        severity: "high",
        owner: "Dan Wax",
      },
    ],
  }),
  project({
    id: "oa-int-faa-pathway",
    kind: "internal",
    name: "FAA Certification Pathway",
    clientId: null,
    clientName: "OnwardAir",
    department: "Operations",
    site: "Houston HQ · Regulatory",
    region: "US · Certification",
    operator: "Scott Parazynski, MD",
    projectManager: "Scott Parazynski, MD",
    phase: "live",
    startDate: "2026-01-10",
    endDate: "2027-03-31",
    progressPct: 36,
    budgetLabel: "$320,000",
    stakeholders: ["Brian Whiteside", "GEN Duncan McNabb", "Outside Counsel"],
    notes: "Experimental / type certification scoping with AeroLaw counsel; board-ready pathway options.",
    milestones: [
      { id: "m1", name: "Counsel SOW signed", dueDate: "2026-02-28", status: "done" },
      { id: "m2", name: "Pathway options brief", dueDate: "2026-09-10", status: "upcoming" },
      { id: "m3", name: "Board decision lock", dueDate: "2026-12-10", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "FAA interaction timeline slip",
        severity: "high",
        owner: "Scott Parazynski, MD",
      },
    ],
  }),
  project({
    id: "oa-int-seed-raise",
    kind: "internal",
    name: "Seed Raise Programme",
    clientId: null,
    clientName: "OnwardAir",
    department: "Fundraising",
    site: "Houston / Remote · Investor Ops",
    region: "US · Capital",
    operator: "Rick Perez",
    projectManager: "Scott Parazynski, MD",
    phase: "live",
    startDate: "2026-05-01",
    endDate: "2026-12-31",
    progressPct: 32,
    budgetLabel: "$180,000",
    stakeholders: ["Rick Perez", "Carolyn Scott", "Dylan Taylor"],
    notes: "Active Seed raise toward $5.0M — deck, data rooms, pipeline, and term-sheet readiness.",
    milestones: [
      { id: "m1", name: "Deck v1.5 live", dueDate: "2026-07-28", status: "done" },
      { id: "m2", name: "Lead diligence open", dueDate: "2026-09-30", status: "upcoming" },
      { id: "m3", name: "Soft circle target", dueDate: "2026-11-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Raise closes below $5.0M target before year-end",
        severity: "high",
        owner: "Rick Perez",
      },
    ],
  }),
  project({
    id: "oa-int-data-room",
    kind: "internal",
    name: "Investor Data Room Build-Out",
    clientId: null,
    clientName: "OnwardAir",
    department: "Fundraising",
    site: "Cloud · Secure files",
    region: "US · Capital",
    operator: "Rick Perez",
    projectManager: "Rick Perez",
    phase: "live",
    startDate: "2026-06-01",
    endDate: "2026-09-30",
    progressPct: 72,
    budgetLabel: "$45,000",
    stakeholders: ["Scott Parazynski", "Monte Mann", "Cameron Burr"],
    notes: "Structured data rooms for Seed leads — financials, IP summary, cap table, contracts.",
    milestones: [
      { id: "m1", name: "Folder taxonomy", dueDate: "2026-06-20", status: "done" },
      { id: "m2", name: "Core docs uploaded", dueDate: "2026-08-01", status: "done" },
      { id: "m3", name: "Access audit complete", dueDate: "2026-09-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Stale financial pack vs GL close",
        severity: "low",
        owner: "Monte Mann",
      },
    ],
  }),
  project({
    id: "oa-int-4dof",
    kind: "internal",
    name: "4-DoF Hand Controller Integration",
    clientId: null,
    clientName: "OnwardAir",
    department: "Engineering",
    site: "Houston · Flight Controls",
    region: "Texas · Engineering",
    operator: "Jon Fenner",
    projectManager: "Brian Whiteside",
    phase: "live",
    startDate: "2026-02-15",
    endDate: "2026-09-30",
    progressPct: 67,
    budgetLabel: "$210,000",
    stakeholders: ["Scott Parazynski", "Jon Fenner", "Keven Coates"],
    notes: "Integrate patented multi-DoF controller IP into Vertex flight interface stack.",
    milestones: [
      { id: "m1", name: "Interface spec", dueDate: "2026-04-01", status: "done" },
      { id: "m2", name: "Bench integration", dueDate: "2026-07-15", status: "done" },
      { id: "m3", name: "Flight-sim acceptance", dueDate: "2026-09-20", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Cross-coupling edge cases in high-gain modes",
        severity: "medium",
        owner: "Jon Fenner",
      },
    ],
  }),
  project({
    id: "oa-int-ip-docket",
    kind: "internal",
    name: "IP Docket & Trademark Hygiene",
    clientId: null,
    clientName: "OnwardAir",
    department: "Corporate",
    site: "Houston · Legal / IP",
    region: "US · Corporate",
    operator: "Rick Perez",
    projectManager: "Scott Parazynski, MD",
    phase: "live",
    startDate: "2026-03-01",
    endDate: "2026-12-31",
    progressPct: 45,
    budgetLabel: "$95,000",
    stakeholders: ["Fish & Richardson", "Board"],
    notes: "Maintain patent schedule, provisional filings queue, and Vertex / FLEX Pods brand marks.",
    milestones: [
      { id: "m1", name: "Register inventory", dueDate: "2026-05-01", status: "done" },
      { id: "m2", name: "Provisional batch filed", dueDate: "2026-09-30", status: "upcoming" },
      { id: "m3", name: "Year-end docket review", dueDate: "2026-12-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Unverified claims needing counsel review before marketing use",
        severity: "medium",
        owner: "Rick Perez",
      },
    ],
  }),
  project({
    id: "oa-int-supply-chain",
    kind: "internal",
    name: "Critical Parts Supply Chain",
    clientId: null,
    clientName: "OnwardAir",
    department: "Operations",
    site: "Houston · Supply Chain",
    region: "US · Ops",
    operator: "Dan Wax",
    projectManager: "Dan Wax",
    phase: "live",
    startDate: "2026-04-01",
    endDate: "2026-11-30",
    progressPct: 52,
    budgetLabel: "$155,000",
    stakeholders: ["Brian Whiteside", "Mike Teeter", "Monte Mann"],
    notes: "Dual-source critical aero and power parts; lead-time buffers for prototype build.",
    milestones: [
      { id: "m1", name: "BOM criticality map", dueDate: "2026-05-15", status: "done" },
      { id: "m2", name: "Dual-source for top 20 SKUs", dueDate: "2026-09-01", status: "upcoming" },
      { id: "m3", name: "Buffer stock policy", dueDate: "2026-11-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Single-source composites vendor capacity",
        severity: "medium",
        owner: "Dan Wax",
      },
    ],
  }),
  project({
    id: "oa-int-board-ops",
    kind: "internal",
    name: "Board Meeting Cadence & Decks",
    clientId: null,
    clientName: "OnwardAir",
    department: "Board",
    site: "Houston HQ · Governance",
    region: "US · Board",
    operator: "Dylan Taylor",
    projectManager: "Scott Parazynski, MD",
    phase: "live",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progressPct: 70,
    budgetLabel: "$40,000",
    stakeholders: ["Board Members", "Carolyn Scott"],
    notes: "Quarterly board cadence, AI draft decks, minutes structure, and pack lock process.",
    milestones: [
      { id: "m1", name: "Q2 2026 pack closed", dueDate: "2026-06-11", status: "done" },
      { id: "m2", name: "Sept 2026 materials lock", dueDate: "2026-08-27", status: "upcoming" },
      { id: "m3", name: "Dec 2026 pack", dueDate: "2026-12-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Late engineering inputs before pack freeze",
        severity: "low",
        owner: "Dylan Taylor",
      },
    ],
  }),
  project({
    id: "oa-int-brand-gtm",
    kind: "internal",
    name: "Brand & Investor Narrative",
    clientId: null,
    clientName: "OnwardAir",
    department: "Marketing",
    site: "Houston · Marketing",
    region: "US · GTM",
    operator: "Carolyn Scott",
    projectManager: "Carolyn Scott",
    phase: "live",
    startDate: "2026-05-15",
    endDate: "2026-10-31",
    progressPct: 55,
    budgetLabel: "$75,000",
    stakeholders: ["Scott Parazynski", "Rick Perez"],
    notes: "Vertex / FLEX Pods narrative, investor day collateral, and site refresh alignment.",
    milestones: [
      { id: "m1", name: "Narrative refresh", dueDate: "2026-07-15", status: "done" },
      { id: "m2", name: "Investor day storyboard", dueDate: "2026-09-15", status: "upcoming" },
      { id: "m3", name: "Site content sync", dueDate: "2026-10-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Claims language vs counsel-approved IP wording",
        severity: "low",
        owner: "Carolyn Scott",
      },
    ],
  }),
  project({
    id: "oa-int-hr-hiring",
    kind: "internal",
    name: "Critical Engineering Hiring Wave",
    clientId: null,
    clientName: "OnwardAir",
    department: "Human Resources",
    site: "Houston · People Ops",
    region: "US · HR",
    operator: "Brian Whiteside",
    projectManager: "Brian Whiteside",
    phase: "live",
    startDate: "2026-06-01",
    endDate: "2026-11-15",
    progressPct: 38,
    budgetLabel: "$90,000",
    stakeholders: ["Scott Parazynski", "Dan Wax", "HR"],
    notes:
      "Fill Senior Flight Controls, Battery & Power, and FAA Certification Programme Manager roles.",
    milestones: [
      { id: "m1", name: "Roles opened", dueDate: "2026-07-15", status: "done" },
      { id: "m2", name: "First offer accepted", dueDate: "2026-09-01", status: "upcoming" },
      { id: "m3", name: "Three seats filled", dueDate: "2026-11-01", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Competitive offers for flight-controls talent",
        severity: "medium",
        owner: "Brian Whiteside",
      },
    ],
  }),
  project({
    id: "oa-int-sim-cloud",
    kind: "internal",
    name: "Engineering Simulation Cloud",
    clientId: null,
    clientName: "OnwardAir",
    department: "Technology",
    site: "AWS us-east-1",
    region: "Cloud · Engineering",
    operator: "Keven Coates",
    projectManager: "Brian Whiteside",
    phase: "live",
    startDate: "2026-03-15",
    endDate: "2026-10-31",
    progressPct: 61,
    budgetLabel: "$110,000",
    stakeholders: ["IT", "Engineering", "Finance"],
    notes: "Scale CFD / controls simulation workloads and secure investor data-room hosting.",
    milestones: [
      { id: "m1", name: "MSA & budget lock", dueDate: "2026-04-30", status: "done" },
      { id: "m2", name: "Sim cluster live", dueDate: "2026-07-31", status: "done" },
      { id: "m3", name: "Cost guardrails", dueDate: "2026-10-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Committed spend vs Seed runway",
        severity: "low",
        owner: "Monte Mann",
      },
    ],
  }),
  project({
    id: "oa-int-defence-pilot",
    kind: "internal",
    name: "Defence Logistics Pilot Pipeline",
    clientId: null,
    clientName: "OnwardAir",
    department: "Business Development",
    site: "Houston / Remote",
    region: "US · BD",
    operator: "GEN Duncan McNabb",
    projectManager: "Scott Parazynski, MD",
    phase: "upcoming",
    startDate: "2026-09-01",
    endDate: "2027-03-31",
    progressPct: 12,
    budgetLabel: "$65,000",
    stakeholders: ["Board", "Rick Perez", "Carolyn Scott"],
    notes: "Map defence-logistics pilot opportunities for Q4 board; outreach via McNabb network.",
    milestones: [
      { id: "m1", name: "Opportunity map", dueDate: "2026-09-30", status: "upcoming" },
      { id: "m2", name: "Two LOIs targeted", dueDate: "2026-12-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Classification / export-control scoping",
        severity: "medium",
        owner: "GEN Duncan McNabb",
      },
    ],
  }),
  project({
    id: "oa-int-finance-usd",
    kind: "internal",
    name: "USD Financials & Close Process",
    clientId: null,
    clientName: "OnwardAir",
    department: "Finance",
    site: "Houston · Finance",
    region: "US · Finance",
    operator: "Monte Mann",
    projectManager: "Monte Mann",
    phase: "live",
    startDate: "2026-02-01",
    endDate: "2026-09-30",
    progressPct: 78,
    budgetLabel: "$55,000",
    stakeholders: ["Scott Parazynski", "Board", "PwC"],
    notes: "USD GL, management pack, and month-end close aligned to Seed diligence needs.",
    milestones: [
      { id: "m1", name: "Chart of accounts USD", dueDate: "2026-03-15", status: "done" },
      { id: "m2", name: "Close checklist live", dueDate: "2026-06-30", status: "done" },
      { id: "m3", name: "Diligence pack template", dueDate: "2026-09-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Bank feed timing for multi-entity view",
        severity: "low",
        owner: "Monte Mann",
      },
    ],
  }),
];

/** 2 external delivery programmes — customer / partner work. */
export const ONWARDAIR_EXTERNAL_PROJECT_PORTFOLIO: PortfolioProject[] = [
  project({
    id: "oa-ext-operator-demo",
    kind: "external",
    name: "Middle-Mile Operator Demo Path",
    clientId: "oa-cli-skybridge",
    clientName: "SkyBridge Logistics",
    site: "Gulf Coast · Operator trial",
    region: "United States",
    operator: "Jordan Blake",
    projectManager: "Brian Whiteside",
    accountManager: "Carolyn Scott",
    phase: "live",
    startDate: "2026-04-15",
    endDate: "2026-12-15",
    progressPct: 44,
    budgetLabel: "$285,000",
    contractValueLabel: "$285,000",
    deliveryStatus: "On track",
    billingStatus: "Milestone billing",
    customerContacts: ["Jordan Blake (COO)", "Priya Nair (Ops)"],
    notes:
      "Joint planning for a middle-mile logistics demo using Vertex VTOL / FLEX Pod concept of operations with SkyBridge.",
    milestones: [
      { id: "m1", name: "CONOPS workshop", dueDate: "2026-05-30", status: "done" },
      { id: "m2", name: "Site survey", dueDate: "2026-08-15", status: "done" },
      { id: "m3", name: "Demo readiness review", dueDate: "2026-11-01", status: "upcoming" },
      { id: "m4", name: "Operator readout", dueDate: "2026-12-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Operator airspace coordination window",
        severity: "medium",
        owner: "Brian Whiteside",
      },
    ],
  }),
  project({
    id: "oa-ext-medevac-study",
    kind: "external",
    name: "Medical Logistics Concept Study",
    clientId: "oa-cli-medreach",
    clientName: "MedReach Alliance",
    site: "Houston / Remote · Study",
    region: "United States",
    operator: "Dr. Lena Ortiz",
    projectManager: "Gabe Mena, MD",
    accountManager: "Scott Parazynski, MD",
    phase: "upcoming",
    startDate: "2026-09-15",
    endDate: "2027-02-28",
    progressPct: 8,
    budgetLabel: "$160,000",
    contractValueLabel: "$160,000",
    deliveryStatus: "Scheduled",
    billingStatus: "Kick-off invoice scheduled",
    customerContacts: ["Dr. Lena Ortiz", "Marcus Chen"],
    notes:
      "Feasibility study for rapid medical logistics missions using modular FLEX Pod payloads with hospital network partners.",
    milestones: [
      { id: "m1", name: "Kick-off & data room", dueDate: "2026-09-30", status: "upcoming" },
      { id: "m2", name: "Mission profile options", dueDate: "2026-11-30", status: "upcoming" },
      { id: "m3", name: "Study report", dueDate: "2027-02-15", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Clinical stakeholder availability for workshops",
        severity: "low",
        owner: "Gabe Mena, MD",
      },
    ],
  }),
];
