/**
 * OnwardAir Project Management — task / Gantt / critical-path fixtures.
 * Loaded when `internal_project_tasks` has no rows for an `oa-*` project id.
 * Milestone flags drive the Milestones panel; critical flags drive the Gantt critical path.
 */

import type { ProjectTask } from "@/lib/project-detail-data";

type TaskDraft = Omit<ProjectTask, "id" | "description"> & {
  id?: string;
  description?: string;
};

function tasks(projectId: string, items: TaskDraft[]): ProjectTask[] {
  return items.map((item, index) => ({
    id: item.id ?? `${projectId}-t${String(index + 1).padStart(2, "0")}`,
    name: item.name,
    description: item.description ?? "",
    startDate: item.startDate,
    dueDate: item.dueDate,
    progress: item.progress,
    resource: item.resource,
    milestone: item.milestone,
    critical: item.critical,
  }));
}

/** Per-project work packages — dates span each programme window with overlapping Gantt bars. */
export const ONWARDAIR_PROJECT_TASKS: Record<string, ProjectTask[]> = {
  "oa-int-hover-demo": tasks("oa-int-hover-demo", [
    {
      name: "HIL rig commissioned",
      description: "Hardware-in-the-loop bench, actuator harness, and sensor calibration complete.",
      startDate: "2026-01-15",
      dueDate: "2026-03-31",
      progress: 100,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
    {
      name: "Airframe structural load cases",
      description: "Static + fatigue cases for hover envelope; FEA correlation with coupon tests.",
      startDate: "2026-02-10",
      dueDate: "2026-05-15",
      progress: 100,
      resource: "Mike Teeter",
      milestone: false,
      critical: true,
    },
    {
      name: "Control laws freeze v1",
      description: "Inner-loop attitude and rate controllers frozen for taxi/hover software build.",
      startDate: "2026-04-01",
      dueDate: "2026-06-30",
      progress: 100,
      resource: "David Colling",
      milestone: true,
      critical: true,
    },
    {
      name: "Flight software integration sprint",
      description: "FCU flash, telemetry pipeline, and failsafe modes on HIL before taxi.",
      startDate: "2026-06-15",
      dueDate: "2026-08-20",
      progress: 72,
      resource: "Brian Whiteside",
      milestone: false,
      critical: true,
    },
    {
      name: "Ground taxi complete",
      description: "Powered taxi envelope, brake/steer response, and abort procedures signed.",
      startDate: "2026-08-01",
      dueDate: "2026-09-15",
      progress: 35,
      resource: "Mike Teeter",
      milestone: true,
      critical: true,
    },
    {
      name: "Range & safety briefings",
      description: "Flight-test ops plan, NOTAM coordination, and observer staffing for hover day.",
      startDate: "2026-09-01",
      dueDate: "2026-10-31",
      progress: 15,
      resource: "Scott Parazynski, MD",
      milestone: false,
      critical: false,
    },
    {
      name: "Hover demo",
      description: "First powered hover demonstration — gate for Seed narrative and follow-on funding.",
      startDate: "2026-10-15",
      dueDate: "2026-11-30",
      progress: 0,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
  ]),

  "oa-int-flex-pod": tasks("oa-int-flex-pod", [
    {
      name: "ICD draft",
      description: "Mechanical / electrical / data ICD between airframe hardpoints and FLEX Pod™.",
      startDate: "2026-02-01",
      dueDate: "2026-04-15",
      progress: 100,
      resource: "Mike Teeter",
      milestone: true,
      critical: true,
    },
    {
      name: "Quick-release prototype fab",
      description: "Machine and assemble latch set; first fit check on fixture plate.",
      startDate: "2026-03-15",
      dueDate: "2026-06-10",
      progress: 100,
      resource: "Jon Fenner",
      milestone: false,
      critical: true,
    },
    {
      name: "Fixture sign-off",
      description: "Integration fixture dimensional survey and pod align repeatability ≤2 mm.",
      startDate: "2026-05-01",
      dueDate: "2026-07-01",
      progress: 100,
      resource: "Mike Teeter",
      milestone: true,
      critical: true,
    },
    {
      name: "Harness & connector qualification",
      description: "Blind-mate connectors, EMI screening, and disconnect under load case.",
      startDate: "2026-06-20",
      dueDate: "2026-08-25",
      progress: 55,
      resource: "Dan Wax",
      milestone: false,
      critical: true,
    },
    {
      name: "Pod swap ≤15 min demo",
      description: "Timed swap drill with two operators — target ≤15 minutes pad-to-pad.",
      startDate: "2026-08-15",
      dueDate: "2026-09-30",
      progress: 20,
      resource: "Mike Teeter",
      milestone: true,
      critical: true,
    },
    {
      name: "Ops playbook & training video",
      description: "Field procedure, torque cards, and training clip for partner demos.",
      startDate: "2026-09-15",
      dueDate: "2026-10-15",
      progress: 0,
      resource: "Jordan Blake",
      milestone: false,
      critical: false,
    },
  ]),

  "oa-int-battery-pack": tasks("oa-int-battery-pack", [
    {
      name: "Supplier shortlist",
      description: "RFQ closed; three pack/BMS vendors scored on energy density, cycle life, lead time.",
      startDate: "2026-03-01",
      dueDate: "2026-05-01",
      progress: 100,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "Cell characterization campaign",
      description: "Capacity, impedance, and abuse screening for shortlisted chemistry.",
      startDate: "2026-04-15",
      dueDate: "2026-07-15",
      progress: 85,
      resource: "Keven Coates",
      milestone: false,
      critical: true,
    },
    {
      name: "Thermal model locked",
      description: "Pack thermal CFD + BMS derate curves frozen for hover duty cycle.",
      startDate: "2026-06-01",
      dueDate: "2026-08-15",
      progress: 40,
      resource: "Keven Coates",
      milestone: true,
      critical: true,
    },
    {
      name: "BMS firmware bench bring-up",
      description: "Cell balancing, SOC estimator, and fault injection on bench harness.",
      startDate: "2026-07-20",
      dueDate: "2026-10-15",
      progress: 25,
      resource: "David Colling",
      milestone: false,
      critical: true,
    },
    {
      name: "Pack A sample received",
      description: "First engineering sample pack delivered, inspected, and logged into inventory.",
      startDate: "2026-09-15",
      dueDate: "2026-11-01",
      progress: 0,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "Qualification test plan sign-off",
      description: "UN38.3, thermal runaway containment, and vibration plan for cert path.",
      startDate: "2026-10-20",
      dueDate: "2026-12-15",
      progress: 0,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-int-faa-pathway": tasks("oa-int-faa-pathway", [
    {
      name: "Counsel SOW signed",
      description: "Aviation counsel engaged for Part 21 / experimental pathway options.",
      startDate: "2026-01-10",
      dueDate: "2026-02-28",
      progress: 100,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "Regulatory landscape memo",
      description: "Comparable VTOL / UAS precedents and Houston test-site constraints.",
      startDate: "2026-03-01",
      dueDate: "2026-05-30",
      progress: 100,
      resource: "Outside counsel",
      milestone: false,
      critical: true,
    },
    {
      name: "Safety case outline",
      description: "Hazard log draft, DAL targets, and means of compliance matrix skeleton.",
      startDate: "2026-05-15",
      dueDate: "2026-08-15",
      progress: 55,
      resource: "Brian Whiteside",
      milestone: false,
      critical: true,
    },
    {
      name: "Pathway options brief",
      description: "Board-ready brief comparing experimental, type, and exemption paths.",
      startDate: "2026-07-01",
      dueDate: "2026-09-10",
      progress: 30,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "FAA pre-app meeting prep",
      description: "Slides, questions, and engineering artefacts for first FAA engagement.",
      startDate: "2026-09-15",
      dueDate: "2026-11-15",
      progress: 5,
      resource: "Mike Teeter",
      milestone: false,
      critical: true,
    },
    {
      name: "Board decision lock",
      description: "Board selects preferred certification pathway and budget envelope.",
      startDate: "2026-11-01",
      dueDate: "2026-12-10",
      progress: 0,
      resource: "Dylan Taylor",
      milestone: true,
      critical: true,
    },
    {
      name: "Formal application package draft",
      description: "Assemble first formal submission package under selected pathway.",
      startDate: "2027-01-05",
      dueDate: "2027-03-31",
      progress: 0,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-int-seed-raise": tasks("oa-int-seed-raise", [
    {
      name: "Deck v1.5 live",
      description: "Investor narrative, unit economics, and hover-demo timeline refreshed.",
      startDate: "2026-05-01",
      dueDate: "2026-07-28",
      progress: 100,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Target list & warm intros",
      description: "Prioritised Seed list (aerospace, logistics, defence-adjacent) with intro path.",
      startDate: "2026-06-15",
      dueDate: "2026-08-20",
      progress: 90,
      resource: "Carolyn Scott",
      milestone: false,
      critical: true,
    },
    {
      name: "Lead diligence open",
      description: "Data room access granted to lead; Q&A tracker opened.",
      startDate: "2026-08-15",
      dueDate: "2026-09-30",
      progress: 35,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Partner meeting cadence",
      description: "Weekly partner calls; technical deep-dives with Brian / Mike as needed.",
      startDate: "2026-09-01",
      dueDate: "2026-11-15",
      progress: 20,
      resource: "Scott Parazynski, MD",
      milestone: false,
      critical: true,
    },
    {
      name: "Soft circle target",
      description: "Verbal / soft commitments toward Seed soft-circle target.",
      startDate: "2026-10-01",
      dueDate: "2026-11-15",
      progress: 0,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Term sheet negotiation",
      description: "Negotiate valuation, board seat, and information rights with lead.",
      startDate: "2026-11-16",
      dueDate: "2026-12-31",
      progress: 0,
      resource: "Outside counsel",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-int-data-room": tasks("oa-int-data-room", [
    {
      name: "Folder taxonomy",
      description: "Investor-grade folder tree: corporate, IP, tech, financials, HR, legal.",
      startDate: "2026-06-01",
      dueDate: "2026-06-20",
      progress: 100,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Cap table & formation pack",
      description: "Formation docs, cap table export, and option plan summary uploaded.",
      startDate: "2026-06-10",
      dueDate: "2026-07-15",
      progress: 100,
      resource: "Monte Mann",
      milestone: false,
      critical: true,
    },
    {
      name: "Core docs uploaded",
      description: "Patents, pitch, financial model, org chart, and key contracts live.",
      startDate: "2026-06-21",
      dueDate: "2026-08-01",
      progress: 100,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Technical appendix refresh",
      description: "Hover-demo evidence pack and FLEX Pod ICD excerpts for diligence.",
      startDate: "2026-07-20",
      dueDate: "2026-09-01",
      progress: 65,
      resource: "Brian Whiteside",
      milestone: false,
      critical: false,
    },
    {
      name: "Access audit complete",
      description: "Permission review, watermarking, and access log export for counsel.",
      startDate: "2026-08-15",
      dueDate: "2026-09-15",
      progress: 40,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Diligence FAQ freeze",
      description: "Consolidate recurring Q&A into a living FAQ for Seed process.",
      startDate: "2026-09-01",
      dueDate: "2026-09-30",
      progress: 15,
      resource: "Carolyn Scott",
      milestone: false,
      critical: false,
    },
  ]),

  "oa-int-4dof": tasks("oa-int-4dof", [
    {
      name: "Interface spec",
      description: "4-DoF hand controller electrical + protocol interface to FCU.",
      startDate: "2026-02-15",
      dueDate: "2026-04-01",
      progress: 100,
      resource: "Jon Fenner",
      milestone: true,
      critical: true,
    },
    {
      name: "Prototype controller assembly",
      description: "Grips, encoders, and haptics assembled for first bench build.",
      startDate: "2026-03-20",
      dueDate: "2026-05-30",
      progress: 100,
      resource: "Jon Fenner",
      milestone: false,
      critical: true,
    },
    {
      name: "Bench integration",
      description: "Controller talking to HIL; latency and deadband characterisation done.",
      startDate: "2026-05-15",
      dueDate: "2026-07-15",
      progress: 100,
      resource: "David Colling",
      milestone: true,
      critical: true,
    },
    {
      name: "Pilot ergonomics study",
      description: "Operator feedback sessions; grip angle and force curve tweaks.",
      startDate: "2026-07-01",
      dueDate: "2026-08-25",
      progress: 50,
      resource: "Gabe Mena, MD",
      milestone: false,
      critical: false,
    },
    {
      name: "Flight-sim acceptance",
      description: "Controller accepted in flight-sim environment against hover training syllabus.",
      startDate: "2026-08-10",
      dueDate: "2026-09-20",
      progress: 25,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
    {
      name: "Field cable & connector kit",
      description: "Flight-test harness kit bagged and labeled for hover campaign.",
      startDate: "2026-09-01",
      dueDate: "2026-09-30",
      progress: 10,
      resource: "Dan Wax",
      milestone: false,
      critical: false,
    },
  ]),

  "oa-int-ip-docket": tasks("oa-int-ip-docket", [
    {
      name: "Register inventory",
      description: "Full docket of patents, trademarks, trade secrets, and know-how indexed.",
      startDate: "2026-03-01",
      dueDate: "2026-05-01",
      progress: 100,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Trademark watch & renewals",
      description: "Vertex VTOL™ / FLEX Pod™ mark status and renewal calendar.",
      startDate: "2026-04-15",
      dueDate: "2026-07-01",
      progress: 100,
      resource: "Outside IP counsel",
      milestone: false,
      critical: false,
    },
    {
      name: "Invention harvest workshops",
      description: "Engineering sessions to capture hover / pod / BMS inventions for provisionals.",
      startDate: "2026-06-01",
      dueDate: "2026-08-15",
      progress: 70,
      resource: "Brian Whiteside",
      milestone: false,
      critical: true,
    },
    {
      name: "Provisional batch filed",
      description: "Batch of provisional applications filed covering priority claims.",
      startDate: "2026-08-01",
      dueDate: "2026-09-30",
      progress: 30,
      resource: "Outside IP counsel",
      milestone: true,
      critical: true,
    },
    {
      name: "Trade-secret policy update",
      description: "Access controls and NDAs aligned with data-room and partner demos.",
      startDate: "2026-09-15",
      dueDate: "2026-11-15",
      progress: 10,
      resource: "Scott Parazynski, MD",
      milestone: false,
      critical: false,
    },
    {
      name: "Year-end docket review",
      description: "Board-level IP hygiene review and 2027 prosecution budget.",
      startDate: "2026-11-15",
      dueDate: "2026-12-15",
      progress: 0,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
  ]),

  "oa-int-supply-chain": tasks("oa-int-supply-chain", [
    {
      name: "BOM criticality map",
      description: "Rank SKUs by lead time, sole-source risk, and hover-demo dependency.",
      startDate: "2026-04-01",
      dueDate: "2026-05-15",
      progress: 100,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "Vendor scorecards",
      description: "Quality, on-time, and financial health scorecards for top 30 vendors.",
      startDate: "2026-05-01",
      dueDate: "2026-07-15",
      progress: 100,
      resource: "Ops analyst",
      milestone: false,
      critical: true,
    },
    {
      name: "Dual-source for top 20 SKUs",
      description: "Qualify alternate sources for highest-risk long-lead parts.",
      startDate: "2026-06-15",
      dueDate: "2026-09-01",
      progress: 45,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "Inbound QA sampling plan",
      description: "Incoming inspection sampling aligned to flight-critical vs commercial parts.",
      startDate: "2026-08-01",
      dueDate: "2026-10-15",
      progress: 25,
      resource: "Mike Teeter",
      milestone: false,
      critical: false,
    },
    {
      name: "Buffer stock policy",
      description: "Safety-stock levels and reorder points for hover-demo critical path.",
      startDate: "2026-09-15",
      dueDate: "2026-11-15",
      progress: 5,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "ERP / spreadsheet cutover",
      description: "Move critical BOM tracking from sheets into controlled inventory view.",
      startDate: "2026-10-15",
      dueDate: "2026-11-30",
      progress: 0,
      resource: "Monte Mann",
      milestone: false,
      critical: false,
    },
  ]),

  "oa-int-board-ops": tasks("oa-int-board-ops", [
    {
      name: "Q2 2026 pack closed",
      description: "June board materials archived; actions tracked to owners.",
      startDate: "2026-01-01",
      dueDate: "2026-06-11",
      progress: 100,
      resource: "Dylan Taylor",
      milestone: true,
      critical: true,
    },
    {
      name: "Minutes & action tracker hygiene",
      description: "Standard template and follow-up cadence for all board actions.",
      startDate: "2026-06-15",
      dueDate: "2026-07-31",
      progress: 100,
      resource: "EA / Corp Sec",
      milestone: false,
      critical: false,
    },
    {
      name: "Sept 2026 materials lock",
      description: "Deck, financials, and risk register locked for September meeting.",
      startDate: "2026-07-15",
      dueDate: "2026-08-27",
      progress: 55,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "AI board deck assist pilot",
      description: "Trial AI CREATE BOARD MEETING DECK flow on Sept pack draft.",
      startDate: "2026-08-01",
      dueDate: "2026-09-10",
      progress: 40,
      resource: "Rick Perez",
      milestone: false,
      critical: false,
    },
    {
      name: "Dec 2026 pre-read circulate",
      description: "Year-end strategy and Seed update pre-read to directors.",
      startDate: "2026-10-15",
      dueDate: "2026-11-20",
      progress: 0,
      resource: "Dylan Taylor",
      milestone: true,
      critical: true,
    },
    {
      name: "Mar 2027 agenda draft",
      description: "Q1 2027 agenda skeleton with hover-demo and FAA pathway items.",
      startDate: "2026-12-01",
      dueDate: "2026-12-31",
      progress: 0,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-int-brand-gtm": tasks("oa-int-brand-gtm", [
    {
      name: "Brand voice guidelines",
      description: "Tone, claims hygiene, and Vertex / FLEX Pod naming rules for all channels.",
      startDate: "2026-04-01",
      dueDate: "2026-05-20",
      progress: 100,
      resource: "Carolyn Scott",
      milestone: true,
      critical: true,
    },
    {
      name: "Investor one-pager refresh",
      description: "Single-page narrative aligned to Seed deck v1.5.",
      startDate: "2026-05-15",
      dueDate: "2026-07-01",
      progress: 100,
      resource: "Rick Perez",
      milestone: false,
      critical: true,
    },
    {
      name: "Website hero & story arc",
      description: "Homepage story for middle-mile logistics + medical logistics use cases.",
      startDate: "2026-06-15",
      dueDate: "2026-08-30",
      progress: 60,
      resource: "Carolyn Scott",
      milestone: true,
      critical: true,
    },
    {
      name: "Press / media kit",
      description: "Boilerplate, founder bios, and approved imagery for partners.",
      startDate: "2026-08-01",
      dueDate: "2026-10-01",
      progress: 25,
      resource: "Comms",
      milestone: false,
      critical: false,
    },
    {
      name: "Partner demo narrative",
      description: "SkyBridge / MedReach talking points and leave-behind sheets.",
      startDate: "2026-09-15",
      dueDate: "2026-11-15",
      progress: 10,
      resource: "Jordan Blake",
      milestone: true,
      critical: true,
    },
    {
      name: "Year-end brand audit",
      description: "Consistency check across deck, site, and data-room collateral.",
      startDate: "2026-11-15",
      dueDate: "2026-12-15",
      progress: 0,
      resource: "Carolyn Scott",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-int-hr-hiring": tasks("oa-int-hr-hiring", [
    {
      name: "Role scorecards locked",
      description: "Flight controls, mechanical, and BMS role scorecards approved by hiring managers.",
      startDate: "2026-03-15",
      dueDate: "2026-04-30",
      progress: 100,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "Sourcing pipeline fill",
      description: "Outbound + referral pipeline to ≥3 qualified candidates per open role.",
      startDate: "2026-04-15",
      dueDate: "2026-07-01",
      progress: 100,
      resource: "Brian Whiteside",
      milestone: false,
      critical: true,
    },
    {
      name: "First offer accepted",
      description: "Critical engineering hire accepted — onboarding plan attached.",
      startDate: "2026-06-01",
      dueDate: "2026-08-15",
      progress: 55,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "Interview loop calibration",
      description: "Panel rubrics and debrief cadence across engineering managers.",
      startDate: "2026-07-15",
      dueDate: "2026-09-15",
      progress: 40,
      resource: "Mike Teeter",
      milestone: false,
      critical: false,
    },
    {
      name: "Q4 headcount checkpoint",
      description: "Board update on filled vs open critical roles vs hover-demo risk.",
      startDate: "2026-09-01",
      dueDate: "2026-10-31",
      progress: 10,
      resource: "Dan Wax",
      milestone: true,
      critical: true,
    },
    {
      name: "Onboarding kits standardised",
      description: "Laptop, access, and 30/60/90 templates for Houston engineering hires.",
      startDate: "2026-10-15",
      dueDate: "2026-11-30",
      progress: 0,
      resource: "People Ops",
      milestone: false,
      critical: false,
    },
  ]),

  "oa-int-sim-cloud": tasks("oa-int-sim-cloud", [
    {
      name: "Cloud GPU account live",
      description: "Secure cloud GPU tenancy with cost alerts and SSO.",
      startDate: "2026-05-01",
      dueDate: "2026-06-15",
      progress: 100,
      resource: "David Colling",
      milestone: true,
      critical: true,
    },
    {
      name: "CFD / FEA solver images",
      description: "Container images for primary solvers pinned and versioned.",
      startDate: "2026-06-01",
      dueDate: "2026-07-31",
      progress: 100,
      resource: "Cloud eng",
      milestone: false,
      critical: true,
    },
    {
      name: "Pilot job queue",
      description: "First batch jobs from flight controls and structures teams.",
      startDate: "2026-07-15",
      dueDate: "2026-09-15",
      progress: 50,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
    {
      name: "Results archive & naming",
      description: "Standard output paths, metadata tags, and retention policy.",
      startDate: "2026-08-20",
      dueDate: "2026-10-15",
      progress: 30,
      resource: "Mike Teeter",
      milestone: false,
      critical: false,
    },
    {
      name: "Team self-serve GA",
      description: "Engineers can submit / monitor jobs without ops babysitting.",
      startDate: "2026-10-01",
      dueDate: "2026-11-15",
      progress: 5,
      resource: "David Colling",
      milestone: true,
      critical: true,
    },
    {
      name: "FinOps monthly review",
      description: "Spend vs budget review with engineering leads.",
      startDate: "2026-11-01",
      dueDate: "2026-12-15",
      progress: 0,
      resource: "Monte Mann",
      milestone: false,
      critical: false,
    },
  ]),

  "oa-int-defence-pilot": tasks("oa-int-defence-pilot", [
    {
      name: "Opportunity map",
      description: "Defence / logistics pilot opportunities scored for fit and timeline.",
      startDate: "2026-06-01",
      dueDate: "2026-07-20",
      progress: 100,
      resource: "Scott Parazynski, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "NDA & teaser pack",
      description: "Clean teaser and NDA path for first three target accounts.",
      startDate: "2026-07-01",
      dueDate: "2026-08-30",
      progress: 80,
      resource: "Carolyn Scott",
      milestone: false,
      critical: true,
    },
    {
      name: "First CONOPS workshop",
      description: "Joint concept-of-operations workshop with priority prospect.",
      startDate: "2026-08-15",
      dueDate: "2026-10-15",
      progress: 35,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
    {
      name: "Security / ITAR checklist",
      description: "Export-control and facility checklist before deeper tech share.",
      startDate: "2026-09-15",
      dueDate: "2026-11-15",
      progress: 20,
      resource: "Outside counsel",
      milestone: false,
      critical: true,
    },
    {
      name: "Pilot proposal draft",
      description: "Paid pilot SOW outline with success criteria and data rights.",
      startDate: "2026-10-20",
      dueDate: "2026-12-15",
      progress: 0,
      resource: "Rick Perez",
      milestone: true,
      critical: true,
    },
    {
      name: "Pipeline board readout",
      description: "Defence pipeline status in Dec board pack.",
      startDate: "2026-12-01",
      dueDate: "2026-12-20",
      progress: 0,
      resource: "Dylan Taylor",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-int-finance-usd": tasks("oa-int-finance-usd", [
    {
      name: "Chart of accounts USD lock",
      description: "USD CoA and entity structure confirmed for Houston ops.",
      startDate: "2026-02-01",
      dueDate: "2026-03-31",
      progress: 100,
      resource: "Monte Mann",
      milestone: true,
      critical: true,
    },
    {
      name: "Monthly close calendar",
      description: "Close checklist, owners, and day-5 / day-10 targets.",
      startDate: "2026-03-15",
      dueDate: "2026-05-15",
      progress: 100,
      resource: "Controller",
      milestone: false,
      critical: true,
    },
    {
      name: "Burn & runway dashboard",
      description: "Live burn, runway, and Seed-use-of-proceeds view for leadership.",
      startDate: "2026-05-01",
      dueDate: "2026-07-31",
      progress: 75,
      resource: "Monte Mann",
      milestone: true,
      critical: true,
    },
    {
      name: "Vendor AP automation",
      description: "Invoice intake and approval paths for critical engineering vendors.",
      startDate: "2026-07-01",
      dueDate: "2026-09-30",
      progress: 40,
      resource: "Finance ops",
      milestone: false,
      critical: false,
    },
    {
      name: "Board financial pack template",
      description: "Standard P&L, cash, and forecast slides for each board meeting.",
      startDate: "2026-08-15",
      dueDate: "2026-10-31",
      progress: 25,
      resource: "Monte Mann",
      milestone: true,
      critical: true,
    },
    {
      name: "Year-end audit readiness",
      description: "Evidence folders and reconciliations ready for year-end review.",
      startDate: "2026-10-15",
      dueDate: "2026-12-15",
      progress: 5,
      resource: "External accountant",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-ext-operator-demo": tasks("oa-ext-operator-demo", [
    {
      name: "CONOPS workshop",
      description: "Joint SkyBridge workshop on middle-mile routes, payloads, and turn times.",
      startDate: "2026-04-15",
      dueDate: "2026-05-30",
      progress: 100,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
    {
      name: "Site shortlist & constraints",
      description: "Gulf Coast candidate pads, airspace, and ground logistics constraints.",
      startDate: "2026-05-20",
      dueDate: "2026-07-15",
      progress: 100,
      resource: "Jordan Blake",
      milestone: false,
      critical: true,
    },
    {
      name: "Site survey",
      description: "On-site survey with SkyBridge ops; pad dimensions and power logged.",
      startDate: "2026-07-01",
      dueDate: "2026-08-15",
      progress: 100,
      resource: "Mike Teeter",
      milestone: true,
      critical: true,
    },
    {
      name: "FLEX Pod demo kit prep",
      description: "Demo pod fixtures, mock cargo, and swap drill kit for operator day.",
      startDate: "2026-08-01",
      dueDate: "2026-10-15",
      progress: 45,
      resource: "Dan Wax",
      milestone: false,
      critical: true,
    },
    {
      name: "Demo readiness review",
      description: "Joint go/no-go with SkyBridge COO on safety, weather, and staffing.",
      startDate: "2026-09-15",
      dueDate: "2026-11-01",
      progress: 15,
      resource: "Brian Whiteside",
      milestone: true,
      critical: true,
    },
    {
      name: "Airspace coordination window",
      description: "Coordinate temporary flight / demo window with local authorities.",
      startDate: "2026-10-01",
      dueDate: "2026-11-30",
      progress: 10,
      resource: "Scott Parazynski, MD",
      milestone: false,
      critical: true,
    },
    {
      name: "Operator readout",
      description: "Post-demo readout, metrics, and next-step commercial options.",
      startDate: "2026-11-15",
      dueDate: "2026-12-15",
      progress: 0,
      resource: "Carolyn Scott",
      milestone: true,
      critical: false,
    },
  ]),

  "oa-ext-medevac-study": tasks("oa-ext-medevac-study", [
    {
      name: "Kick-off & data room",
      description: "MedReach kick-off; share study charter and NDA-gated materials.",
      startDate: "2026-09-15",
      dueDate: "2026-09-30",
      progress: 40,
      resource: "Gabe Mena, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "Clinical stakeholder map",
      description: "Hospital network contacts, pharmacy, and blood-bank stakeholders.",
      startDate: "2026-09-25",
      dueDate: "2026-10-31",
      progress: 15,
      resource: "Dr. Lena Ortiz",
      milestone: false,
      critical: true,
    },
    {
      name: "Mission profile options",
      description: "Three mission profiles (pharma, blood, device) with range and time targets.",
      startDate: "2026-10-15",
      dueDate: "2026-11-30",
      progress: 0,
      resource: "Gabe Mena, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "Cold-chain / payload ICD sketch",
      description: "FLEX Pod medical payload constraints and cold-chain sketch.",
      startDate: "2026-11-01",
      dueDate: "2027-01-15",
      progress: 0,
      resource: "Mike Teeter",
      milestone: false,
      critical: true,
    },
    {
      name: "Workshop series (×3)",
      description: "Facilitated workshops with MedReach clinical and ops leads.",
      startDate: "2026-11-15",
      dueDate: "2027-01-31",
      progress: 0,
      resource: "Scott Parazynski, MD",
      milestone: false,
      critical: false,
    },
    {
      name: "Study report",
      description: "Feasibility report with recommended pilot scope and risks.",
      startDate: "2027-01-15",
      dueDate: "2027-02-15",
      progress: 0,
      resource: "Gabe Mena, MD",
      milestone: true,
      critical: true,
    },
    {
      name: "Executive readout",
      description: "MedReach alliance exec briefing and optional paid-pilot proposal.",
      startDate: "2027-02-10",
      dueDate: "2027-02-28",
      progress: 0,
      resource: "Carolyn Scott",
      milestone: true,
      critical: false,
    },
  ]),
};

export function getOnwardAirProjectTasks(projectId: string): ProjectTask[] | null {
  const list = ONWARDAIR_PROJECT_TASKS[projectId];
  if (!list) return null;
  return list.map((task) => ({ ...task }));
}

export function isOnwardAirProjectTaskId(projectId: string): boolean {
  return projectId.startsWith("oa-int-") || projectId.startsWith("oa-ext-");
}
