import type { MarketingDashboardKpis } from "@/lib/marketing/types";

export const SAEC_MARKETING_NEWSLETTERS = [
  {
    id: "saec-nl-001",
    title: "August mall modernisation update",
    subject: "OmniTransit — Centurion & Killarney programme progress",
    preview: "Commissioning milestones, safety briefings, and client spotlight.",
    status: "sent",
    audience: "Property & retail clients",
    scheduledAt: "2026-08-08T09:00:00.000Z",
    sentAt: "2026-08-08T09:15:00.000Z",
    openRate: 38.2,
    clickRate: 12.4,
  },
  {
    id: "saec-nl-002",
    title: "Q3 engineering competency bulletin",
    subject: "KLK range training cohort — results & field readiness",
    preview: "Engineering certification outcomes and installation quality metrics.",
    status: "scheduled",
    audience: "Internal engineering",
    scheduledAt: "2026-08-28T08:00:00.000Z",
    sentAt: null,
    openRate: null,
    clickRate: null,
  },
  {
    id: "saec-nl-003",
    title: "Healthcare vertical transport briefing",
    subject: "Hospital lift uptime programme — Gauteng & Western Cape",
    preview: "Redundancy planning, after-hours callouts, and SLA renewal windows.",
    status: "sent",
    audience: "Healthcare portfolio",
    scheduledAt: "2026-07-18T08:00:00.000Z",
    sentAt: "2026-07-18T08:30:00.000Z",
    openRate: 41.6,
    clickRate: 14.8,
  },
  {
    id: "saec-nl-004",
    title: "Sandton office tower escalator refresh",
    subject: "Night-shift commissioning plan — client coordination",
    preview: "Traffic management, mall trading hours, and inspection sign-off.",
    status: "sent",
    audience: "Commercial property managers",
    scheduledAt: "2026-06-12T09:00:00.000Z",
    sentAt: "2026-06-12T09:10:00.000Z",
    openRate: 35.9,
    clickRate: 11.2,
  },
  {
    id: "saec-nl-005",
    title: "Field safety month — working at height",
    subject: "Shaft access, rescue drills, and PPE compliance",
    preview: "Mandatory refresher schedule for installation and service teams.",
    status: "draft",
    audience: "National field teams",
    scheduledAt: null,
    sentAt: null,
    openRate: null,
    clickRate: null,
  },
];

export const SAEC_MARKETING_MAILING_LISTS = [
  {
    id: "saec-ml-clients",
    name: "Retail & property portfolio contacts",
    segment: "Clients",
    subscribers: 842,
    growth30d: 28,
    lastCampaign: "August mall modernisation update",
    status: "Active",
  },
  {
    id: "saec-ml-prospects",
    name: "Healthcare & infrastructure prospects",
    segment: "Prospects",
    subscribers: 312,
    growth30d: 14,
    lastCampaign: "Hospital lift uptime programme",
    status: "Active",
  },
  {
    id: "saec-ml-engineering",
    name: "Engineering & installation partners",
    segment: "Partners",
    subscribers: 186,
    growth30d: 9,
    lastCampaign: "KLK commissioning technical briefing",
    status: "Active",
  },
  {
    id: "saec-ml-facilities",
    name: "Facilities managers — Gauteng",
    segment: "Clients",
    subscribers: 428,
    growth30d: 18,
    lastCampaign: "Sandton tower escalator refresh",
    status: "Active",
  },
];

export const SAEC_MARKETING_INDIVIDUAL_CONTACTS = [
  {
    id: "saec-mc-hyprop",
    name: "Lindiwe Maseko",
    email: "lindiwe.maseko@hyprop.demo",
    organisation: "Hyprop Investments",
    segment: "Client",
    role: "Facilities Director",
    city: "Sandton",
  },
  {
    id: "saec-mc-growthpoint",
    name: "Marcus van Niekerk",
    email: "marcus.vanniekerk@growthpoint.demo",
    organisation: "Growthpoint Properties",
    segment: "Client",
    role: "Portfolio Manager",
    city: "Johannesburg",
  },
  {
    id: "saec-mc-pnp",
    name: "Nomsa Dlamini",
    email: "nomsa.dlamini@pnp.demo",
    organisation: "Pick n Pay",
    segment: "Client",
    role: "National Facilities Lead",
    city: "Cape Town",
  },
  {
    id: "saec-mc-netcare",
    name: "Dr Peter Khumalo",
    email: "peter.khumalo@netcare.demo",
    organisation: "Netcare",
    segment: "Healthcare",
    role: "Engineering Services",
    city: "Johannesburg",
  },
  {
    id: "saec-mc-vaw",
    name: "Sarah Botha",
    email: "sarah.botha@vawaterfront.demo",
    organisation: "V&A Waterfront",
    segment: "Client",
    role: "Operations Manager",
    city: "Cape Town",
  },
  {
    id: "saec-mc-attacq",
    name: "Johan Ferreira",
    email: "johan.ferreira@attacq.demo",
    organisation: "Attacq",
    segment: "Client",
    role: "Technical Manager",
    city: "Pretoria",
  },
  {
    id: "saec-mc-discovery",
    name: "Thandi Mokoena",
    email: "thandi.mokoena@discovery.demo",
    organisation: "Discovery",
    segment: "Prospect",
    role: "Campus Facilities",
    city: "Sandton",
  },
  {
    id: "saec-mc-transnet",
    name: "Bongani Cele",
    email: "bongani.cele@transnet.demo",
    organisation: "Transnet",
    segment: "Infrastructure",
    role: "Asset Manager",
    city: "Durban",
  },
];

export const SAEC_MARKETING_CAMPAIGNS = [
  {
    id: "saec-camp-001",
    subject: "Centurion Mall KLK escalator modernisation — tender follow-up",
    body: "Thank you for attending the technical briefing. Attached programme timeline and commissioning approach.",
    status: "sent",
    channel: "Email",
    scheduledAt: "2026-08-05T10:00:00.000Z",
    sentAt: "2026-08-05T10:15:00.000Z",
    opens: 312,
    clicks: 89,
    conversions: 12,
    budgetZar: 0,
  },
  {
    id: "saec-camp-002",
    subject: "Brooklyn Mall lift refresh — site access coordination",
    body: "Night-shift window proposal and mall trading hour coordination for August programme.",
    status: "sent",
    channel: "Email",
    scheduledAt: "2026-07-22T09:00:00.000Z",
    sentAt: "2026-07-22T09:20:00.000Z",
    opens: 248,
    clicks: 72,
    conversions: 8,
    budgetZar: 0,
  },
  {
    id: "saec-camp-003",
    subject: "Hospital lift redundancy assessment — Gauteng",
    body: "Invitation to facilities workshop on backup power and passenger lift segregation.",
    status: "scheduled",
    channel: "Email + LinkedIn",
    scheduledAt: "2026-09-02T08:00:00.000Z",
    sentAt: null,
    opens: null,
    clicks: null,
    conversions: null,
    budgetZar: 45_000,
  },
  {
    id: "saec-camp-004",
    subject: "KLK range commissioning case study",
    body: "Download the Killarney Junction case study — 14-night commissioning window.",
    status: "sent",
    channel: "Email",
    scheduledAt: "2026-06-30T11:00:00.000Z",
    sentAt: "2026-06-30T11:05:00.000Z",
    opens: 410,
    clicks: 156,
    conversions: 22,
    budgetZar: 0,
  },
  {
    id: "saec-camp-005",
    subject: "Facilities Management Expo Cape Town — stand meetings",
    body: "Book a 20-minute slot with our commercial team at the October expo.",
    status: "scheduled",
    channel: "Email",
    scheduledAt: "2026-09-15T09:00:00.000Z",
    sentAt: null,
    opens: null,
    clicks: null,
    conversions: null,
    budgetZar: 125_000,
  },
  {
    id: "saec-camp-006",
    subject: "Service contract renewal — Western Cape portfolio",
    body: "Annual maintenance renewal pack for Western Cape retail clients.",
    status: "sent",
    channel: "Email",
    scheduledAt: "2026-08-01T08:00:00.000Z",
    sentAt: "2026-08-01T08:12:00.000Z",
    opens: 198,
    clicks: 64,
    conversions: 18,
    budgetZar: 0,
  },
];

export const SAEC_EXTERNAL_EVENTS = [
  {
    id: "saec-ev-001",
    name: "SA Elevator & Escalator Summit",
    startDate: "2026-09-18",
    endDate: "2026-09-19",
    city: "Johannesburg",
    country: "South Africa",
    website: "https://elevator-summit.demo",
    owner: "Commercial team",
    status: "confirmed",
    notes: "Hyprop and Growthpoint meetings pre-booked.",
  },
  {
    id: "saec-ev-002",
    name: "Facilities Management Expo Cape Town",
    startDate: "2026-10-02",
    endDate: "2026-10-03",
    city: "Cape Town",
    country: "South Africa",
    website: "https://fm-expo.demo",
    owner: "Marketing",
    status: "planning",
    notes: "V&A Waterfront case study on stand.",
  },
  {
    id: "saec-ev-003",
    name: "SAPOA Property Indaba",
    startDate: "2026-11-06",
    endDate: "2026-11-07",
    city: "Durban",
    country: "South Africa",
    website: "https://sapoa-indaba.demo",
    owner: "Head of Sales",
    status: "confirmed",
    notes: "Retail mall modernisation roundtable hosted.",
  },
  {
    id: "saec-ev-004",
    name: "Healthcare Engineering Forum",
    startDate: "2026-09-25",
    endDate: "2026-09-25",
    city: "Pretoria",
    country: "South Africa",
    website: "https://healthcare-engineering.demo",
    owner: "Engineering",
    status: "planning",
    notes: "Hospital lift redundancy workshop.",
  },
];

export const SAEC_MANAGED_EVENTS = [
  {
    id: "saec-me-001",
    name: "OmniTransit client technical briefing — KLK range",
    venue: "Johannesburg HQ auditorium",
    date: "2026-09-05",
    capacity: 48,
    registered: 36,
    budgetZar: 185_000,
    status: "registration_open",
  },
  {
    id: "saec-me-002",
    name: "Gauteng facilities managers breakfast",
    venue: "Hyprop Sandton",
    date: "2026-08-29",
    capacity: 32,
    registered: 28,
    budgetZar: 95_000,
    status: "confirmed",
  },
  {
    id: "saec-me-003",
    name: "Field safety month — shaft rescue drill",
    venue: "Pretoria training centre",
    date: "2026-09-12",
    capacity: 60,
    registered: 54,
    budgetZar: 42_000,
    status: "registration_open",
  },
];

export const SAEC_MARKETING_STORIES = [
  {
    id: "saec-story-001",
    title: "Killarney Junction — 14-night KLK commissioning",
    summary: "Mall trading hours preserved while replacing three escalator units.",
    body: "Demonstration case study: phased night-shift commissioning at Killarney Junction with mall trading continuity.",
    status: "Published",
    companyName: "Killarney Junction",
    city: "Johannesburg",
    category: "Escalator modernisation",
  },
  {
    id: "saec-story-002",
    title: "Centurion Mall — passenger lift bank upgrade",
    summary: "Four-lift modernisation with smart grouping and energy recovery.",
    body: "Demonstration record: Centurion Mall lift bank programme — energy metrics and passenger flow improvements.",
    status: "Published",
    companyName: "Centurion Mall",
    city: "Centurion",
    category: "Lift modernisation",
  },
  {
    id: "saec-story-003",
    title: "V&A Waterfront — coastal escalator resilience",
    summary: "Salt-air protection and step chain inspection programme.",
    body: "Demonstration record: coastal environment maintenance programme for waterfront retail escalators.",
    status: "Under Review",
    companyName: "V&A Waterfront",
    city: "Cape Town",
    category: "Service programme",
  },
  {
    id: "saec-story-004",
    title: "Netcare hospital — dual lift segregation",
    summary: "Patient and service lift segregation during ward refurbishment.",
    body: "Demonstration record: hospital lift redundancy planning during live clinical operations.",
    status: "Submitted",
    companyName: "Netcare",
    city: "Johannesburg",
    category: "Healthcare",
  },
];

export const SAEC_MARKETING_MEDIA = [
  {
    id: "saec-media-001",
    name: "KLK escalator night commissioning (demo)",
    mediaType: "image",
    caption: "Night-shift commissioning — demonstration photo",
    storyId: "saec-story-001",
    storyTitle: "Killarney Junction commissioning",
    city: "Johannesburg",
    author: "Marketing",
  },
  {
    id: "saec-media-002",
    name: "Centurion lift lobby render (demo)",
    mediaType: "image",
    caption: "Lift lobby visualisation — demonstration asset",
    storyId: "saec-story-002",
    storyTitle: "Centurion Mall upgrade",
    city: "Centurion",
    author: "Marketing",
  },
  {
    id: "saec-media-003",
    name: "Field team safety briefing (demo)",
    mediaType: "image",
    caption: "Shaft access briefing — demonstration photo",
    storyId: null,
    storyTitle: null,
    city: "Pretoria",
    author: "HR & Safety",
  },
  {
    id: "saec-media-004",
    name: "Expo stand layout (demo)",
    mediaType: "document",
    caption: "FM Expo stand plan — demonstration layout",
    storyId: null,
    storyTitle: null,
    city: "Cape Town",
    author: "Events",
  },
  {
    id: "saec-media-005",
    name: "Waterfront escalator inspection (demo)",
    mediaType: "image",
    caption: "Step chain inspection — demonstration photo",
    storyId: "saec-story-003",
    storyTitle: "V&A Waterfront programme",
    city: "Cape Town",
    author: "Service",
  },
  {
    id: "saec-media-006",
    name: "Client briefing presentation (demo)",
    mediaType: "document",
    caption: "KLK technical briefing deck — demonstration PDF",
    storyId: "saec-story-001",
    storyTitle: "Killarney Junction commissioning",
    city: "Johannesburg",
    author: "Commercial",
  },
];

export function getSaecMarketingKpis(): MarketingDashboardKpis {
  const listSubs = SAEC_MARKETING_MAILING_LISTS.reduce((sum, row) => sum + row.subscribers, 0);
  const growth = SAEC_MARKETING_MAILING_LISTS.reduce((sum, row) => sum + row.growth30d, 0);
  const sent = SAEC_MARKETING_NEWSLETTERS.filter((row) => row.status === "sent");
  const openRates = sent
    .map((row) => row.openRate)
    .filter((value): value is number => typeof value === "number");

  return {
    newsletterOpenRate:
      openRates.length > 0 ? openRates.reduce((a, b) => a + b, 0) / openRates.length : null,
    sentNewsletterCount: sent.length,
    mailingSubscribers: listSubs + SAEC_MARKETING_INDIVIDUAL_CONTACTS.length,
    mailingGrowth30d: growth,
    externalEventsConfirmed: SAEC_EXTERNAL_EVENTS.filter((row) => row.status === "confirmed").length,
    externalEventsTotal: SAEC_EXTERNAL_EVENTS.length,
    managedEventRegistered: SAEC_MANAGED_EVENTS.reduce((sum, row) => sum + row.registered, 0),
    managedEventCapacity: SAEC_MANAGED_EVENTS.reduce((sum, row) => sum + row.capacity, 0),
    managedEventCount: SAEC_MANAGED_EVENTS.length,
  };
}
