export type {
  DashboardActionHandler,
  DashboardActivityItem,
  DashboardAiSummaryWidget,
  DashboardAlertItem,
  DashboardAlertsWidget,
  DashboardAnalyticsAnnotation,
  DashboardAnalyticsSeries,
  DashboardAnalyticsWidget,
  DashboardAudience,
  DashboardEmptyWidget,
  DashboardHeaderWidget,
  DashboardKpiItem,
  DashboardKpiPeriodOption,
  DashboardKpiRowWidget,
  DashboardKpiTone,
  DashboardKpiWidget,
  DashboardLoadingWidget,
  DashboardQuickAction,
  DashboardQuickActionsWidget,
  DashboardRecentActivityWidget,
  DashboardRole,
  DashboardSectionConfig,
  DashboardSectionSlot,
  DashboardWidgetConfig,
  DashboardWidgetType,
  DashboardWidgetVisibility,
  DashboardWorkQueueItem,
  DashboardWorkQueueWidget,
  ResolveDashboardOptions,
  WorkspaceDashboardConfig,
} from "./types";

export {
  filterSections,
  filterWidgets,
  isVisibilityAllowed,
  normalizeKpiRow,
  resolveWorkspaceDashboard,
} from "./composition";

export {
  businessCentralDashboardConfig,
  DASHBOARD_CONFIG_REGISTRY,
  financialsDashboardConfig,
} from "./configs";
