import type { FinancialExpense } from "@/lib/expenses-data";

const now = "2026-08-08T09:00:00.000Z";

/** ABHI T&E and operating expense claims — GBP only. August 2026 MTD populated. */
export const ABHI_EXPENSE_FIXTURES: FinancialExpense[] = [
  {
    id: "abhi-exp-whx-deposit",
    submitterUserId: "u-internal-1",
    submitterName: "Sarah Mitchell",
    purposeDescription: "WHX Dubai 2026 — pavilion stand deposit (50%)",
    amount: 12_500,
    currency: "GBP",
    dateSubmitted: "2026-08-04",
    paid: true,
    supplier: "Informa Markets",
    categoryAccountCode: "5080",
    expenseDate: "2026-08-04",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-EVT-0804",
    journalEntryId: "je-abhi-0804",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-regulatory",
    submitterUserId: "u-internal-1",
    submitterName: "James Okonkwo",
    purposeDescription: "MHRA / EU MDR regulatory horizon briefing — external counsel",
    amount: 8_750,
    currency: "GBP",
    dateSubmitted: "2026-08-05",
    paid: false,
    supplier: "Fieldfisher LLP",
    categoryAccountCode: "5090",
    expenseDate: "2026-08-05",
    paymentMethod: null,
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-LEG-0805",
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-member-forum",
    submitterUserId: "u-internal-1",
    submitterName: "Helen Price",
    purposeDescription: "Member policy forum — venue, AV, and catering",
    amount: 4_200,
    currency: "GBP",
    dateSubmitted: "2026-08-06",
    paid: true,
    supplier: "etc.venues",
    categoryAccountCode: "5080",
    expenseDate: "2026-08-06",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-EVT-0806",
    journalEntryId: "je-abhi-0806",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-linkedin",
    submitterUserId: "u-internal-1",
    submitterName: "Tom Bradley",
    purposeDescription: "LinkedIn membership campaign — August flight",
    amount: 3_900,
    currency: "GBP",
    dateSubmitted: "2026-08-01",
    paid: true,
    supplier: "LinkedIn Ads",
    categoryAccountCode: "5070",
    expenseDate: "2026-08-01",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-MKT-0801",
    journalEntryId: "je-abhi-0801",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-manchester-travel",
    submitterUserId: "u-internal-1",
    submitterName: "Priya Shah",
    purposeDescription: "Med-Tech Innovation Expo — rail and hotel (Manchester)",
    amount: 2_340,
    currency: "GBP",
    dateSubmitted: "2026-08-07",
    paid: false,
    supplier: "Trainline / Premier Inn",
    categoryAccountCode: "5090",
    expenseDate: "2026-08-07",
    paymentMethod: null,
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-TRV-0807",
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-it-subs",
    submitterUserId: "u-internal-1",
    submitterName: "David Chen",
    purposeDescription: "Microsoft 365 + Salesforce — August licences",
    amount: 2_180,
    currency: "GBP",
    dateSubmitted: "2026-08-01",
    paid: true,
    supplier: "Microsoft",
    categoryAccountCode: "5040",
    expenseDate: "2026-08-01",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-SW-0801",
    journalEntryId: "je-abhi-sw-0801",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-staff-misc",
    submitterUserId: "u-internal-1",
    submitterName: "Jane Lewis",
    purposeDescription: "Staff expense claims — week ending 7 Aug (aggregated)",
    amount: 2_510,
    currency: "GBP",
    dateSubmitted: "2026-08-07",
    paid: false,
    supplier: "Various",
    categoryAccountCode: "5090",
    expenseDate: "2026-08-07",
    paymentMethod: null,
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-STF-0807",
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-board-dinner",
    submitterUserId: "u-internal-1",
    submitterName: "Peter Ellingworth",
    purposeDescription: "Board working dinner — July meeting follow-up",
    amount: 1_680,
    currency: "GBP",
    dateSubmitted: "2026-08-03",
    paid: true,
    supplier: "The Goring",
    categoryAccountCode: "5090",
    expenseDate: "2026-08-03",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-BRD-0803",
    journalEntryId: "je-abhi-0803",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-utilities",
    submitterUserId: "u-internal-1",
    submitterName: "Operations",
    purposeDescription: "London office — utilities and facilities (August)",
    amount: 1_850,
    currency: "GBP",
    dateSubmitted: "2026-08-02",
    paid: true,
    supplier: "Regus",
    categoryAccountCode: "5030",
    expenseDate: "2026-08-02",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-OFF-0802",
    journalEntryId: "je-abhi-0802",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "abhi-exp-board-packs",
    submitterUserId: "u-internal-1",
    submitterName: "Board Secretariat",
    purposeDescription: "August board pack printing and courier",
    amount: 890,
    currency: "GBP",
    dateSubmitted: "2026-08-05",
    paid: true,
    supplier: "Printroom",
    categoryAccountCode: "5090",
    expenseDate: "2026-08-05",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "ABHI-BRD-0805",
    journalEntryId: "je-abhi-0805",
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
];
