/**
 * ABHI project portfolio fixtures — mirrors seeded internal_projects for EA when Supabase is unavailable.
 */

import type { PortfolioProject } from "@/lib/project-portfolios";

function project(
  partial: Omit<PortfolioProject, "createdAt" | "updatedAt"> & {
    createdAt?: string;
    updatedAt?: string;
  },
): PortfolioProject {
  return {
    createdAt: partial.createdAt ?? "2026-01-15T09:00:00.000Z",
    updatedAt: partial.updatedAt ?? "2026-08-01T14:30:00.000Z",
    ...partial,
  };
}

export const ABHI_PROJECT_PORTFOLIO: PortfolioProject[] = [
  project({
    id: "abhi-proj-int-membership-ops",
    kind: "internal",
    name: "Membership Operations Hub",
    clientId: null,
    clientName: "ABHI Internal",
    department: "Membership",
    site: "London",
    region: "United Kingdom",
    operator: "Jane Lewis",
    projectManager: "Jane Lewis",
    phase: "live",
    startDate: "2026-01-15",
    endDate: "2026-09-30",
    progressPct: 62,
    budgetLabel: "£185,000",
    stakeholders: ["Membership Director", "Operations Lead"],
    notes: "Internal membership operations programme — renewal tooling and SME support workflows.",
    milestones: [
      { id: "m1", name: "CRM workflow v1", dueDate: "2026-04-30", status: "done" },
      { id: "m2", name: "SME renewal playbook", dueDate: "2026-07-15", status: "done" },
      { id: "m3", name: "Hub launch", dueDate: "2026-09-30", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "December renewal window capacity",
        severity: "medium",
        owner: "Jane Lewis",
      },
    ],
    deliveryStatus: "On track",
  }),
  project({
    id: "abhi-proj-int-policy-insight",
    kind: "internal",
    name: "Policy & Market Access Insight",
    clientId: null,
    clientName: "ABHI Internal",
    department: "Policy",
    site: "London",
    region: "United Kingdom",
    operator: "Richard Phillips",
    projectManager: "Richard Phillips",
    phase: "live",
    startDate: "2026-03-01",
    endDate: "2026-10-31",
    progressPct: 48,
    budgetLabel: "£142,000",
    stakeholders: ["Policy Director", "Regulatory Affairs"],
    notes: "Policy insight programme — regulatory horizon scanning and member briefings.",
    milestones: [
      { id: "m1", name: "Insight taxonomy", dueDate: "2026-05-15", status: "done" },
      { id: "m2", name: "Member briefing cadence", dueDate: "2026-08-01", status: "at-risk" },
      { id: "m3", name: "Annual policy digest", dueDate: "2026-10-31", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Regulatory calendar shifts delaying briefings",
        severity: "high",
        owner: "Richard Phillips",
      },
    ],
    deliveryStatus: "At risk",
  }),
  project({
    id: "abhi-proj-ext-market-access",
    kind: "external",
    name: "Meridian Atlas — Market Access Programme",
    clientId: "abhi-client-1",
    clientName: "Meridian Atlas Health",
    site: "United Kingdom",
    region: "United Kingdom",
    operator: "Paul Benton",
    projectManager: "Paul Benton",
    accountManager: "Paul Benton",
    phase: "live",
    startDate: "2025-11-01",
    endDate: "2026-07-15",
    progressPct: 88,
    budgetLabel: "£240,000",
    contractValueLabel: "£240,000",
    notes: "External member programme — OVERDUE end date with hypercare transition pending.",
    milestones: [
      { id: "m1", name: "Stakeholder mapping", dueDate: "2026-02-28", status: "done" },
      { id: "m2", name: "NHS engagement wave 1", dueDate: "2026-06-30", status: "done" },
      { id: "m3", name: "Close-out report", dueDate: "2026-07-15", status: "at-risk" },
    ],
    risks: [
      {
        id: "r1",
        title: "End-date slip without signed extension",
        severity: "high",
        owner: "Paul Benton",
      },
    ],
    deliveryStatus: "At risk",
  }),
  project({
    id: "abhi-proj-ext-regulatory",
    kind: "external",
    name: "Cambrian Digital — Regulatory Readiness",
    clientId: "abhi-client-2",
    clientName: "Cambrian Digital Therapeutics",
    site: "United Kingdom",
    region: "United Kingdom",
    operator: "Phil Brown",
    projectManager: "Phil Brown",
    accountManager: "Phil Brown",
    phase: "live",
    startDate: "2026-02-01",
    endDate: "2026-08-22",
    progressPct: 71,
    budgetLabel: "£195,000",
    contractValueLabel: "£195,000",
    notes: "Regulatory readiness for digital health certification pathway.",
    milestones: [
      { id: "m1", name: "Gap assessment", dueDate: "2026-04-15", status: "done" },
      { id: "m2", name: "Remediation sprint", dueDate: "2026-07-30", status: "upcoming" },
      { id: "m3", name: "Audit pack", dueDate: "2026-08-22", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Vendor evidence pack incomplete",
        severity: "medium",
        owner: "Phil Brown",
      },
    ],
    deliveryStatus: "On track",
  }),
  project({
    id: "abhi-proj-ext-accelerator",
    kind: "external",
    name: "Northgate Bio — International Accelerator",
    clientId: "abhi-client-3",
    clientName: "Northgate BioSystems",
    site: "United Kingdom",
    region: "United Kingdom",
    operator: "Bayode Adisa",
    projectManager: "Bayode Adisa",
    accountManager: "Bayode Adisa",
    phase: "live",
    startDate: "2026-04-01",
    endDate: "2026-09-12",
    progressPct: 55,
    budgetLabel: "£168,000",
    contractValueLabel: "£168,000",
    notes: "International market entry accelerator — blocked on export compliance sign-off.",
    milestones: [
      { id: "m1", name: "Market shortlist", dueDate: "2026-05-30", status: "done" },
      { id: "m2", name: "Partner introductions", dueDate: "2026-08-15", status: "at-risk" },
      { id: "m3", name: "Accelerator showcase", dueDate: "2026-09-12", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Export compliance review stalled",
        severity: "high",
        owner: "Bayode Adisa",
      },
    ],
    deliveryStatus: "At risk",
  }),
  project({
    id: "abhi-proj-ext-digital-health",
    kind: "external",
    name: "Helix Care — Digital Health Adoption",
    clientId: "abhi-client-4",
    clientName: "Helix Care Platforms",
    site: "United Kingdom",
    region: "United Kingdom",
    operator: "Andrew Davies",
    projectManager: "Andrew Davies",
    accountManager: "Andrew Davies",
    phase: "live",
    startDate: "2026-05-01",
    endDate: "2026-09-18",
    progressPct: 40,
    budgetLabel: "£152,000",
    contractValueLabel: "£152,000",
    notes: "Digital health adoption — progress lagging; clinical pilot sites delayed.",
    milestones: [
      { id: "m1", name: "Pilot site selection", dueDate: "2026-06-15", status: "done" },
      { id: "m2", name: "Site onboarding", dueDate: "2026-08-01", status: "at-risk" },
      { id: "m3", name: "Adoption metrics review", dueDate: "2026-09-18", status: "upcoming" },
    ],
    risks: [
      {
        id: "r1",
        title: "Clinical site onboarding delays",
        severity: "high",
        owner: "Andrew Davies",
      },
      {
        id: "r2",
        title: "Integration testing blocked",
        severity: "medium",
        owner: "Andrew Davies",
      },
    ],
    deliveryStatus: "At risk",
  }),
];
