import { listHrEmployees } from "@/lib/hr-employees-service";
import { sendMailboxEmail } from "@/lib/email/smtp";
import { generateEmployeeDirectoryPdf } from "@/lib/ai-operating-assistant/employee-pdf-service";
import { getAssistantArtifact, getLatestArtifactForUser } from "@/lib/ai-operating-assistant/artifact-store";
import {
  asString,
  toolError,
  toolForbidden,
  toolOk,
  type AssistantToolExecutionContext,
  type AssistantToolResult,
} from "@/lib/ai-operating-assistant/tool-result";

function artifactActions(artifactId: string) {
  return [
    {
      id: `download_${artifactId}`,
      label: "Download PDF",
      kind: "download" as const,
      artifactId,
      href: `/api/executive-assistant/artifacts/${artifactId}?disposition=attachment`,
    },
    {
      id: `open_${artifactId}`,
      label: "Open PDF",
      kind: "open" as const,
      artifactId,
      href: `/api/executive-assistant/artifacts/${artifactId}?disposition=inline`,
    },
    {
      id: `email_${artifactId}`,
      label: "Email PDF",
      kind: "email_artifact" as const,
      artifactId,
      actionId: "emailAssistantArtifact",
    },
  ];
}

/**
 * Immediately generate an employee directory PDF (no salary / compensation).
 */
export async function generateEmployeeListPdf(
  _args: Record<string, unknown>,
  ctx: AssistantToolExecutionContext,
): Promise<AssistantToolResult> {
  if (!ctx.business.permissions.canAccessHr) {
    return toolForbidden(
      "generateEmployeeListPdf",
      "Your current role cannot access HR employee data.",
    );
  }

  try {
    const employees = await listHrEmployees();
    const artifact = await generateEmployeeDirectoryPdf({
      employees,
      userId: ctx.business.user.id,
      organisationName: ctx.business.organisation.name,
    });

    return toolOk(
      "generateEmployeeListPdf",
      [
        {
          artifactId: artifact.id,
          title: artifact.title,
          filename: artifact.filename,
          employeeCount: employees.length,
          downloadUrl: `/api/executive-assistant/artifacts/${artifact.id}?disposition=attachment`,
          openUrl: `/api/executive-assistant/artifacts/${artifact.id}?disposition=inline`,
          columns: ["Name", "Department", "Job title", "Status"],
        },
      ],
      {
        source: ["supabase:hr_employees", "assistant:pdf"],
        pageSize: 1,
        summary: {
          executed: true,
          artifactId: artifact.id,
          title: artifact.title,
          filename: artifact.filename,
          employeeCount: employees.length,
          message: `PDF ready: ${artifact.title} (${employees.length} employees).`,
        },
        followUpActions: artifactActions(artifact.id),
      },
    );
  } catch (error) {
    return toolError(
      "generateEmployeeListPdf",
      error instanceof Error ? error.message : "Failed to generate employee PDF",
      ["supabase:hr_employees"],
    );
  }
}

/**
 * Email a previously generated assistant artifact (e.g. employee PDF) to the Board.
 */
export async function emailAssistantArtifact(
  args: Record<string, unknown>,
  ctx: AssistantToolExecutionContext,
): Promise<AssistantToolResult> {
  const artifactId =
    asString(args.artifactId) || getLatestArtifactForUser(ctx.business.user.id)?.id;
  if (!artifactId) {
    return toolError(
      "emailAssistantArtifact",
      "No PDF is attached to this conversation yet. Generate the employee PDF first.",
      [],
    );
  }

  const artifact = getAssistantArtifact(artifactId, ctx.business.user.id);
  if (!artifact) {
    return toolError(
      "emailAssistantArtifact",
      "That file is no longer available. Generate the PDF again.",
      [],
    );
  }

  const to =
    asString(args.to) ||
    process.env.UNIT311_BOARD_EMAIL ||
    process.env.BOARD_EMAIL ||
    "paul@unit311central.com";

  try {
    await sendMailboxEmail({
      account: "paul",
      to,
      subject: `${artifact.title} — Unit311`,
      text: `Please find attached: ${artifact.title}.\n\nGenerated by the Unit311 AI Executive Assistant.`,
      html: `<p>Please find attached: <strong>${artifact.title}</strong>.</p><p>Generated by the Unit311 AI Executive Assistant.</p>`,
      attachments: [
        {
          filename: artifact.filename,
          content: artifact.bytes,
          contentType: artifact.mimeType,
        },
      ],
      workspaceId: ctx.business.workspace.id,
    });

    return toolOk(
      "emailAssistantArtifact",
      [{ artifactId, to, filename: artifact.filename }],
      {
        source: ["assistant:pdf", "smtp:paul"],
        pageSize: 1,
        summary: {
          executed: true,
          artifactId,
          emailedTo: to,
          message: `Emailed ${artifact.filename} to ${to}.`,
        },
        followUpActions: artifactActions(artifactId),
      },
    );
  } catch (error) {
    return toolError(
      "emailAssistantArtifact",
      error instanceof Error ? error.message : "Failed to email the PDF",
      ["smtp"],
    );
  }
}
