import type { CorporateAdvisor } from "@/lib/corporate-data";

/** Northstar demo professional advisors — annual costs, no retainers. */
export const NORTHSTAR_CORPORATE_ADVISORS: CorporateAdvisor[] = [
  {
    id: "nst-adv-law",
    company: "Ashford Lane LLP",
    category: "Lawyers",
    contact: "Priya Shah (Partner)",
    country: "United Kingdom",
    phone: "+44 20 7946 2201",
    email: "priya.shah@ashfordlane.demo",
    retainer: "£5,000 / year",
    status: "active",
    notes: "Corporate & commercial counsel · £25k one-off pre-seed legal fees posted Jun 2023",
  },
  {
    id: "nst-adv-acct",
    company: "Northbridge Advisory",
    category: "Accountants",
    contact: "James Okonkwo",
    country: "United Kingdom",
    phone: "+44 20 7946 2210",
    email: "j.okonkwo@northbridge.demo",
    retainer: "£3,000 / year",
    status: "active",
    notes: "Management accounts, VAT, and statutory filings",
  },
  {
    id: "nst-adv-audit",
    company: "Helix Audit Partners",
    category: "Auditors",
    contact: "Elena Vogt",
    country: "United Kingdom",
    phone: "+44 161 555 0182",
    email: "elena.vogt@helixaudit.demo",
    retainer: "£3,000 / year",
    status: "active",
    notes: "Statutory audit · FY fieldwork Q4",
  },
  {
    id: "nst-adv-tax",
    company: "Summit Tax Group",
    category: "Tax Advisors",
    contact: "Daniel Reeves",
    country: "United Kingdom",
    phone: "+44 20 7946 2233",
    email: "d.reeves@summittax.demo",
    retainer: "£3,000 / year",
    status: "active",
    notes: "R&D tax credits and cross-border structuring",
  },
  {
    id: "nst-adv-ip",
    company: "Cascade IP Counsel",
    category: "IP Lawyers",
    contact: "Marcus Wei",
    country: "United Kingdom",
    phone: "+44 20 7946 2244",
    email: "marcus.wei@cascadeip.demo",
    retainer: "Ad hoc · no annual fee",
    status: "active",
    notes: "Patent & trademark work billed per matter — no ongoing retainer",
  },
];
