/**
 * Northstar Demo — internal & external project history (~3 years).
 */
import type { InternalProject } from "@/lib/projects-data";

const NOW = "2026-08-17T10:00:00.000Z";

function project(
  partial: Omit<InternalProject, "createdAt" | "updatedAt">,
): InternalProject {
  return { ...partial, createdAt: NOW, updatedAt: NOW };
}

/** Internal programmes (no clientId). */
const INTERNAL: InternalProject[] = [
  project({
    id: "nst-int-001",
    name: "Edge Controller v3 — R&D platform",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Bristol, UK",
    region: "UK",
    operator: "Sophie Barker",
    phase: "live",
    startDate: "2025-01-10",
    endDate: "2026-12-15",
    progressPct: 62,
    notes: "Certification testing Q2 2026.",
  }),
  project({
    id: "nst-int-002",
    name: "MES connector framework",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "James Okonkwo",
    phase: "live",
    startDate: "2025-06-01",
    endDate: "2026-09-30",
    progressPct: 74,
    notes: "OPC-UA adapters for Siemens & Rockwell.",
  }),
  project({
    id: "nst-int-003",
    name: "Predictive maintenance ML pipeline",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Bristol, UK",
    region: "UK",
    operator: "Elena Hart",
    phase: "live",
    startDate: "2025-09-15",
    endDate: "2026-11-30",
    progressPct: 48,
    notes: "Feature store + edge inference prototypes.",
  }),
  project({
    id: "nst-int-004",
    name: "Factory digital twin — internal pilot",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "Marcus Reed",
    phase: "upcoming",
    startDate: "2026-10-01",
    endDate: "2027-06-30",
    progressPct: 8,
    notes: "On hold — awaiting Bristol lab space allocation.",
  }),
  project({
    id: "nst-int-005",
    name: "ISO 27001 controls uplift",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "Priya Shah",
    phase: "live",
    startDate: "2024-03-01",
    endDate: "2026-08-31",
    progressPct: 91,
    notes: "Final penetration test scheduled.",
  }),
  project({
    id: "nst-int-006",
    name: "Legacy PLC library — Modbus & Profinet",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Bristol, UK",
    region: "UK",
    operator: "Tom Clarke",
    phase: "completed",
    startDate: "2023-04-01",
    endDate: "2024-11-30",
    progressPct: 100,
    notes: "Delivered — reused across client rollouts.",
  }),
  project({
    id: "nst-int-007",
    name: "Northstar cloud telemetry backbone",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "Elena Hart",
    phase: "completed",
    startDate: "2023-01-15",
    endDate: "2024-06-30",
    progressPct: 100,
    notes: "Finished — now standard for all deployments.",
  }),
  project({
    id: "nst-int-008",
    name: "Apprentice training lab refresh",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "Sophie Barker",
    phase: "upcoming",
    startDate: "2026-11-01",
    endDate: "2027-02-28",
    progressPct: 5,
    notes: "On hold — capex approval deferred to Q4 board.",
  }),
  project({
    id: "nst-int-009",
    name: "Atlas platform core refactor",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "Marcus Reed",
    phase: "completed",
    startDate: "2023-02-01",
    endDate: "2024-03-31",
    progressPct: 100,
    notes: "Finished — foundation for all client Atlas rollouts.",
  }),
  project({
    id: "nst-int-010",
    name: "Bristol R&D lab expansion",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Bristol, UK",
    region: "UK",
    operator: "Elena Hart",
    phase: "upcoming",
    startDate: "2026-05-01",
    endDate: "2027-03-31",
    progressPct: 3,
    notes: "On hold — planning permission review in progress.",
  }),
  project({
    id: "nst-int-011",
    name: "Edge security hardening programme",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Manchester, UK",
    region: "UK",
    operator: "Priya Shah",
    phase: "live",
    startDate: "2025-04-15",
    endDate: "2026-10-31",
    progressPct: 67,
    notes: "Zero-trust rollout to all edge gateways.",
  }),
  project({
    id: "nst-int-012",
    name: "CI/CD pipeline v2",
    clientId: null,
    clientName: "Northstar Industrial Technologies",
    site: "Bristol, UK",
    region: "UK",
    operator: "Rachel Green",
    phase: "completed",
    startDate: "2023-08-01",
    endDate: "2024-12-20",
    progressPct: 100,
    notes: "Finished — cut release cycle from 6 weeks to 10 days.",
  }),
];

/** Client delivery programmes. */
const EXTERNAL: InternalProject[] = [
  project({
    id: "nst-ext-001",
    name: "Atlas Monitoring Platform — Sheffield Precision",
    clientId: "nst-cli-sheffield",
    clientName: "Sheffield Precision Engineering",
    site: "Sheffield, UK",
    region: "UK",
    operator: "Marcus Reed",
    phase: "live",
    startDate: "2025-03-01",
    endDate: "2026-09-30",
    progressPct: 78,
    notes: "Voltex firmware delay; phased go-live Mar 2026.",
  }),
  project({
    id: "nst-ext-002",
    name: "IoT Monitoring — Peak District Breweries",
    clientId: "nst-cli-peak",
    clientName: "Peak District Breweries",
    site: "Bakewell, UK",
    region: "UK",
    operator: "Elena Hart",
    phase: "live",
    startDate: "2025-01-15",
    endDate: "2026-08-31",
    progressPct: 88,
    notes: "UAT sign-off scheduled.",
  }),
  project({
    id: "nst-ext-003",
    name: "Predictive Maintenance Pilot — Bristol Composites",
    clientId: "nst-cli-bristol",
    clientName: "Bristol Composites Ltd",
    site: "Bristol, UK",
    region: "UK",
    operator: "James Okonkwo",
    phase: "upcoming",
    startDate: "2026-09-01",
    endDate: "2026-12-15",
    progressPct: 12,
    notes: "Discovery complete — SOW in legal review.",
  }),
  project({
    id: "nst-ext-004",
    name: "Legacy PLC Integration — Cardiff Port Logistics",
    clientId: "nst-cli-cardiff",
    clientName: "Cardiff Port Logistics",
    site: "Cardiff, UK",
    region: "UK",
    operator: "Priya Shah",
    phase: "live",
    startDate: "2025-05-01",
    endDate: "2026-11-30",
    progressPct: 41,
    notes: "Behind plan — waiting on client OT network access.",
  }),
  project({
    id: "nst-ext-005",
    name: "US Pilot Deployment Kit — Austin Industrial",
    clientId: "nst-cli-austin",
    clientName: "Austin Industrial Partners",
    site: "Austin, TX",
    region: "US",
    operator: "Tom Clarke",
    phase: "live",
    startDate: "2025-08-01",
    endDate: "2026-10-31",
    progressPct: 45,
    notes: "Field engineer capacity constrained.",
  }),
  project({
    id: "nst-ext-006",
    name: "Energy monitoring — Midlands Food Co-op",
    clientId: "nst-cli-midlands",
    clientName: "Midlands Food Co-operative",
    site: "Nottingham, UK",
    region: "UK",
    operator: "Marcus Reed",
    phase: "completed",
    startDate: "2023-06-01",
    endDate: "2024-09-30",
    progressPct: 100,
    notes: "Finished — reference site for food & beverage sector.",
  }),
  project({
    id: "nst-ext-007",
    name: "Harbor Energy SCADA bridge",
    clientId: "nst-cli-harbor",
    clientName: "Harbor Energy Supply",
    site: "Hull, UK",
    region: "UK",
    operator: "James Okonkwo",
    phase: "completed",
    startDate: "2023-09-01",
    endDate: "2025-02-28",
    progressPct: 100,
    notes: "Delivered on time; extended support through 2025.",
  }),
  project({
    id: "nst-ext-008",
    name: "Warehouse automation telemetry — Leeds Distribution",
    clientId: "nst-cli-leeds",
    clientName: "Leeds Distribution Group",
    site: "Leeds, UK",
    region: "UK",
    operator: "Sophie Barker",
    phase: "upcoming",
    startDate: "2026-07-01",
    endDate: "2027-01-31",
    progressPct: 0,
    notes: "On hold — client budget freeze until FY27.",
  }),
  project({
    id: "nst-ext-009",
    name: "Condition monitoring — Glasgow Shipyard",
    clientId: "nst-cli-glasgow",
    clientName: "Clyde Marine Services",
    site: "Glasgow, UK",
    region: "UK",
    operator: "Priya Shah",
    phase: "completed",
    startDate: "2024-01-15",
    endDate: "2025-05-30",
    progressPct: 100,
    notes: "Finished — case study published.",
  }),
  project({
    id: "nst-ext-010",
    name: "Edge gateway rollout — Dublin Pharma",
    clientId: "nst-cli-dublin",
    clientName: "Dublin Pharma Packaging",
    site: "Dublin, IE",
    region: "EU",
    operator: "Elena Hart",
    phase: "live",
    startDate: "2025-11-01",
    endDate: "2026-12-20",
    progressPct: 34,
    notes: "GMP validation documentation in progress.",
  }),
  project({
    id: "nst-ext-011",
    name: "Renewables monitoring — Belfast Wind Co-op",
    clientId: "nst-cli-belfast",
    clientName: "Belfast Wind Co-operative",
    site: "Belfast, UK",
    region: "UK",
    operator: "Tom Clarke",
    phase: "completed",
    startDate: "2023-03-15",
    endDate: "2024-08-30",
    progressPct: 100,
    notes: "Finished — 12 turbine sites instrumented.",
  }),
  project({
    id: "nst-ext-012",
    name: "Auto plant pilot — Munich Precision",
    clientId: "nst-cli-munich",
    clientName: "Munich Precision Auto",
    site: "Munich, DE",
    region: "EU",
    operator: "James Okonkwo",
    phase: "live",
    startDate: "2025-02-01",
    endDate: "2026-11-15",
    progressPct: 56,
    notes: "Line 3 vibration analytics in UAT.",
  }),
  project({
    id: "nst-ext-013",
    name: "Steel works telemetry — Birmingham Metals",
    clientId: "nst-cli-birmingham",
    clientName: "Birmingham Metals Group",
    site: "Birmingham, UK",
    region: "UK",
    operator: "Marcus Reed",
    phase: "upcoming",
    startDate: "2026-04-01",
    endDate: "2027-02-28",
    progressPct: 0,
    notes: "On hold — client restructuring; restart TBD.",
  }),
  project({
    id: "nst-ext-014",
    name: "Agri sensor network — Norfolk Farms",
    clientId: "nst-cli-norfolk",
    clientName: "Norfolk Farms Collective",
    site: "Norwich, UK",
    region: "UK",
    operator: "Sophie Barker",
    phase: "completed",
    startDate: "2024-02-01",
    endDate: "2025-01-31",
    progressPct: 100,
    notes: "Finished — soil moisture + irrigation automation.",
  }),
  project({
    id: "nst-ext-015",
    name: "Packaging line OEE — Chicago Foods",
    clientId: "nst-cli-chicago",
    clientName: "Chicago Foods Packaging",
    site: "Chicago, IL",
    region: "US",
    operator: "Tom Clarke",
    phase: "live",
    startDate: "2025-07-01",
    endDate: "2026-09-30",
    progressPct: 39,
    notes: "US field team mobilised; two lines live.",
  }),
];

export const NORTHSTAR_DEMO_PROJECTS: readonly InternalProject[] = [...INTERNAL, ...EXTERNAL];

export function getNorthstarDemoProjects(): InternalProject[] {
  return NORTHSTAR_DEMO_PROJECTS.map((row) => ({ ...row }));
}
