import type { CorporateContract } from "@/lib/corporate-data";
import { NORTHSTAR_OFFICE_RENT_LABEL } from "@/lib/demo/northstar-office-rent";

const LEASE_PARTIES = "Northstar Industrial Technologies Ltd";

/** Northstar demo leases — aligned with Manchester, Bristol, and Austin offices. */
export const NORTHSTAR_OFFICE_LEASE_CONTRACTS: CorporateContract[] = [
  {
    id: "nst-con-man-lease",
    name: "Manchester Office Lease",
    supplier: "Trafford Park Estates Ltd",
    type: "Lease",
    owner: "COO",
    startDate: "2024-03-01",
    expiryDate: "2027-02-28",
    value: NORTHSTAR_OFFICE_RENT_LABEL,
    status: "active",
    summary: "Unit 4, Trafford Park Industrial Estate · 12 desks",
    parties: `${LEASE_PARTIES} · Trafford Park Estates Ltd`,
    renewalNotes: "Break clause at month 24",
    documents: "NST_Manchester_Lease.pdf",
    notes: "Primary UK engineering hub",
  },
  {
    id: "nst-con-bri-lease",
    name: "Bristol Office Lease",
    supplier: "Temple Quay Developments Ltd",
    type: "Lease",
    owner: "COO",
    startDate: "2024-09-01",
    expiryDate: "2027-08-31",
    value: NORTHSTAR_OFFICE_RENT_LABEL,
    status: "active",
    summary: "14 Temple Quay · 7 desks",
    parties: `${LEASE_PARTIES} · Temple Quay Developments Ltd`,
    renewalNotes: "",
    documents: "NST_Bristol_Lease.pdf",
    notes: "R&D and customer success",
  },
  {
    id: "nst-con-aus-lease",
    name: "Austin Office Lease",
    supplier: "Brazos Street Properties LLC",
    type: "Lease",
    owner: "COO",
    startDate: "2025-06-01",
    expiryDate: "2028-05-31",
    value: NORTHSTAR_OFFICE_RENT_LABEL,
    status: "active",
    summary: "800 Brazos Street, Suite 400 · 6 desks",
    parties: `${LEASE_PARTIES} · Brazos Street Properties LLC`,
    renewalNotes: "US expansion footprint",
    documents: "NST_Austin_Lease.pdf",
    notes: "North America sales & partnerships",
  },
];

/** Non-lease commercial contracts for the Northstar demo workspace. */
const NORTHSTAR_OTHER_CONTRACTS: CorporateContract[] = [
  {
    id: "nst-con-m365",
    name: "Microsoft 365 E5 Enterprise",
    supplier: "Microsoft Ireland",
    type: "Other",
    owner: "CTO",
    startDate: "2026-01-28",
    expiryDate: "2027-01-23",
    value: "£9,800 / month",
    status: "active",
    summary: "Enterprise productivity + security suite",
    parties: `${LEASE_PARTIES} · Microsoft`,
    renewalNotes: "",
    documents: "M365_E5_Order.pdf",
    notes: "Covers all Northstar Industrial Technologies seats",
  },
  {
    id: "nst-con-aws",
    name: "AWS Enterprise Discount Program",
    supplier: "Amazon Web Services",
    type: "Supplier",
    owner: "Cloud Practice Lead",
    startDate: "2025-10-20",
    expiryDate: "2026-09-30",
    value: "Committed spend US$1.2M / year",
    status: "expiring",
    summary: "EDP covering client delivery and internal platforms",
    parties: `${LEASE_PARTIES} · AWS`,
    renewalNotes: "Renegotiate commit before Q4",
    documents: "AWS_EDP.pdf",
    notes: "",
  },
  {
    id: "nst-con-do",
    name: "Directors & Officers Liability",
    supplier: "Aether Risk Brokers",
    type: "Insurance",
    owner: "CFO",
    startDate: "2026-05-18",
    expiryDate: "2027-05-13",
    value: "£18,400 / year",
    status: "active",
    summary: "£5M D&O cover for board and senior leadership",
    parties: `${LEASE_PARTIES} · Aether Risk`,
    renewalNotes: "",
    documents: "DO_Policy_2026.pdf",
    notes: "",
  },
  {
    id: "nst-con-hubspot",
    name: "HubSpot Enterprise CRM",
    supplier: "HubSpot Ireland Ltd",
    type: "Other",
    owner: "CRO",
    startDate: "2026-03-19",
    expiryDate: "2027-03-14",
    value: "£3,400 / month",
    status: "active",
    summary: "CRM + marketing automation for Northstar Industrial Technologies",
    parties: `${LEASE_PARTIES} · HubSpot`,
    renewalNotes: "",
    documents: "",
    notes: "",
  },
];

export const NORTHSTAR_CORPORATE_CONTRACTS: CorporateContract[] = [
  ...NORTHSTAR_OFFICE_LEASE_CONTRACTS,
  ...NORTHSTAR_OTHER_CONTRACTS,
];
