-- SAEC workspace Software & SaaS register — ZAR seed (idempotent).

do $$
declare
  v_saec_id uuid;
begin
  select id into v_saec_id from public.workspaces where slug = 'saec' limit 1;
  if v_saec_id is null then
    raise notice '175_saec_software_assets_zar_seed: saec workspace missing — skipped';
    return;
  end if;

  if exists (
    select 1
    from public.software_assets sa
    where sa.workspace_id = v_saec_id
      and sa.name = 'Microsoft 365 Business Premium'
      and upper(sa.currency) = 'ZAR'
  ) then
    raise notice '175_saec_software_assets_zar_seed: ZAR register already seeded — skipped';
    return;
  end if;

  delete from public.software_asset_credentials where workspace_id = v_saec_id;
  delete from public.software_asset_files where workspace_id = v_saec_id;
  delete from public.software_asset_audit_events where workspace_id = v_saec_id;
  delete from public.software_assets where workspace_id = v_saec_id;

  insert into public.software_assets (
    workspace_id,
    name,
    vendor,
    purpose,
    category,
    website_url,
    status,
    licences_purchased,
    licences_allocated,
    licence_type,
    monthly_cost,
    annual_cost,
    currency,
    last_payment_amount,
    last_payment_date,
    next_renewal_date,
    renewal_frequency,
    contract_length,
    cost_centre,
    budget_owner,
    supplier_name,
    invoice_reference,
    financial_account_code,
    business_owner,
    technical_owner,
    department,
    approver,
    supplier_company,
    integration_connected,
    integration_api_key_set,
    integration_oauth_status,
    integration_sync_status,
    provider_slug
  )
  values
    (
      v_saec_id,
      'Microsoft 365 Business Premium',
      'Microsoft',
      'Email, Teams, and SharePoint for national engineering & commercial teams',
      'Productivity',
      'https://www.microsoft.com/microsoft-365',
      'Active',
      58,
      54,
      'Per user',
      96_800,
      1_161_600,
      'ZAR',
      96_800,
      '2026-08-01',
      '2026-09-01',
      'Monthly',
      'Annual',
      'Corporate',
      'Dewald Lassen',
      'Microsoft',
      'MS-ZAR-AUG-2026',
      '5010',
      'Dewald Lassen',
      'Linda van Wyk',
      'Technology',
      'CFO',
      'Microsoft Corporation',
      true,
      true,
      'connected',
      'healthy',
      'microsoft'
    ),
    (
      v_saec_id,
      'HubSpot CRM',
      'HubSpot',
      'Commercial pipeline, mall portfolio accounts, and tender tracking',
      'CRM',
      'https://www.hubspot.com',
      'Active',
      12,
      10,
      'Named',
      42_500,
      510_000,
      'ZAR',
      42_500,
      '2026-08-01',
      '2026-09-01',
      'Monthly',
      'Annual',
      'Commercial',
      'Michelle Naidoo',
      'HubSpot',
      'HS-ZAR-AUG-2026',
      '5010',
      'Michelle Naidoo',
      'Tshepo Modise',
      'Sales',
      'CFO',
      'HubSpot Inc.',
      true,
      true,
      'connected',
      'healthy',
      'hubspot'
    ),
    (
      v_saec_id,
      'Fleet GPS & dispatch (Netstar)',
      'Netstar',
      'National service fleet routing, engineer dispatch, and SLA compliance',
      'Operations',
      'https://www.netstar.co.za',
      'Active',
      24,
      24,
      'Named',
      68_400,
      820_800,
      'ZAR',
      68_400,
      '2026-08-01',
      '2026-09-01',
      'Monthly',
      'Rolling',
      'Field Ops',
      'Tshepo Modise',
      'Netstar',
      'NET-ZAR-AUG-2026',
      '5030',
      'Tshepo Modise',
      'Riaan Pretorius',
      'Operations',
      'COO',
      'Netstar South Africa',
      true,
      false,
      'connected',
      'healthy',
      'netstar'
    ),
    (
      v_saec_id,
      'Lift maintenance CMMS',
      'ServiceMax',
      'Asset registers, PM schedules, and compliance inspections',
      'Field service',
      'https://www.servicemax.com',
      'Active',
      45,
      42,
      'Per user',
      54_200,
      650_400,
      'ZAR',
      54_200,
      '2026-08-01',
      '2026-09-01',
      'Monthly',
      'Annual',
      'Engineering',
      'Riaan Pretorius',
      'ServiceMax',
      'SMX-ZAR-AUG-2026',
      '5010',
      'Riaan Pretorius',
      'Annelize Fourie',
      'Engineering',
      'CTO',
      'ServiceMax',
      true,
      true,
      'connected',
      'healthy',
      'servicemax'
    ),
    (
      v_saec_id,
      'Adobe Acrobat Sign',
      'Adobe',
      'Client contract signing and mall authority approvals',
      'Collaboration',
      'https://www.adobe.com/sign',
      'Active',
      8,
      6,
      'Named',
      12_800,
      153_600,
      'ZAR',
      12_800,
      '2026-08-01',
      '2026-09-01',
      'Monthly',
      'Annual',
      'Legal',
      'Johan Steyn',
      'Adobe',
      'ADO-ZAR-AUG-2026',
      '5010',
      'Johan Steyn',
      'Linda van Wyk',
      'Legal',
      'CFO',
      'Adobe Inc.',
      true,
      false,
      'connected',
      'healthy',
      'adobe'
    );
end $$;
