import type { FinancialExpense } from "@/lib/expenses-data";
import { expenseFixture } from "@/lib/expenses-data";

const now = "2026-08-01T10:00:00.000Z";

/** Talanton T&E fixtures — USD only (fund management travel & diligence). */
export const TALANTON_EXPENSE_FIXTURES: FinancialExpense[] = [
  expenseFixture({
    id: "ti-exp-nairobi-diligence",
    submitterUserId: "u-internal-1",
    submitterName: "Kenneth Muchina",
    purposeDescription: "Portfolio diligence — Nairobi site visits (Agro Innovations, SunCulture)",
    amount: 4_820,
    currency: "USD",
    dateSubmitted: "2026-07-18",
    paid: true,
    supplier: "Kenya Airways",
    categoryAccountCode: "5090",
    expenseDate: "2026-07-14",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "TI-TRAV-2407",
    recordStatus: "finalized",
    reimbursable: false,
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  }),
  expenseFixture({
    id: "ti-exp-lp-meeting",
    submitterUserId: "u-internal-1",
    submitterName: "Michelle Ochieng",
    purposeDescription: "LP advisory committee dinner — Philadelphia",
    amount: 1_240,
    currency: "USD",
    dateSubmitted: "2026-07-22",
    paid: false,
    supplier: "The Union League",
    categoryAccountCode: "5090",
    expenseDate: "2026-07-20",
    paymentMethod: null,
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "TI-ENT-2407",
    recordStatus: "finalized",
    reimbursable: false,
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  }),
  expenseFixture({
    id: "ti-exp-compliance-software",
    submitterUserId: "u-internal-1",
    submitterName: "Mercy Nelima",
    purposeDescription: "Fund accounting subscription — annual renewal (Carta)",
    amount: 9_600,
    currency: "USD",
    dateSubmitted: "2026-08-02",
    paid: true,
    supplier: "Carta",
    categoryAccountCode: "5040",
    expenseDate: "2026-08-01",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "TI-SW-2408",
    recordStatus: "finalized",
    reimbursable: false,
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  }),
  expenseFixture({
    id: "ti-exp-east-africa-office",
    submitterUserId: "u-internal-1",
    submitterName: "Carol Rubiro",
    purposeDescription: "Nairobi fund operations — co-working & utilities",
    amount: 2_150,
    currency: "USD",
    dateSubmitted: "2026-07-30",
    paid: true,
    supplier: "Nairobi Garage",
    categoryAccountCode: "5030",
    expenseDate: "2026-07-28",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "TI-OFF-2407",
    recordStatus: "finalized",
    reimbursable: false,
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  }),
  expenseFixture({
    id: "ti-exp-impact-measurement",
    submitterUserId: "u-internal-1",
    submitterName: "Linda Kiraithe, CFA",
    purposeDescription: "Impact measurement consultant — Q2 portfolio review",
    amount: 6_500,
    currency: "USD",
    dateSubmitted: "2026-07-12",
    paid: true,
    supplier: "60 Decibels",
    categoryAccountCode: "5080",
    expenseDate: "2026-07-10",
    paymentMethod: "wise",
    wiseBalanceId: null,
    attachmentPath: null,
    reference: "TI-CON-2407",
    recordStatus: "finalized",
    reimbursable: false,
    journalEntryId: null,
    paymentJournalEntryId: null,
    createdAt: now,
    updatedAt: now,
  }),
];
