/**
 * Talanton Impact HR operations fixtures — leave, recruitment, performance, reports.
 * Employee names align with talantonimpact.com OUR TEAM (see hr-team-data.ts).
 */

import { emptyHrReportFilters, type HrSavedReport } from "@/lib/hr-reports-data";
import type { HrLeaveBalance, HrLeaveRequest, HrPublicHoliday } from "@/lib/hr-leave-data";
import {
  emptyOfferDetails,
  type HrCandidate,
  type HrVacancy,
} from "@/lib/hr-recruitment-data";
import {
  blankCompetencyScores,
  blankQuestionResponses,
  type HrPerformanceObjective,
  type HrPerformanceReview,
} from "@/lib/hr-performance-data";

function isoDaysFromNow(offset: number) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

const DAVID = {
  id: "ti-hr-01",
  name: "David Simms",
  role: "Managing Partner and Founder",
  department: "Leadership",
};
const HARRY = {
  id: "ti-hr-02",
  name: "Harry Turner",
  role: "Partner",
  department: "Leadership",
};
const IRIS = {
  id: "ti-hr-04",
  name: "Iris Liang",
  role: "Associate Partner",
  department: "Investments",
};
const ANDY = {
  id: "ti-hr-05",
  name: "Andy Moore",
  role: "Associate Partner & CFO",
  department: "Finance",
};
const MICHELLE = {
  id: "ti-hr-06",
  name: "Michelle Ochieng",
  role: "VP Investor Relations",
  department: "Investor Relations",
};
const KENNETH = {
  id: "ti-hr-07",
  name: "Kenneth Muchina",
  role: "Senior VP East Africa",
  department: "East Africa",
};
const CYNTHIA = {
  id: "ti-hr-09",
  name: "Cynthia Omondi",
  role: "VP Investments",
  department: "Investments",
};
const MERCY = {
  id: "ti-hr-10",
  name: "Mercy Nelima",
  role: "Senior Manager Finance",
  department: "Finance",
};
const LINDA = {
  id: "ti-hr-13",
  name: "Linda Kiraithe, CFA",
  role: "Senior Analyst",
  department: "Investments",
};

function ratedResponses(scores: number[]) {
  return blankQuestionResponses().map((item, index) => ({
    ...item,
    rating: (scores[index] ?? 4) as 1 | 2 | 3 | 4 | 5,
    managerComments: index % 6 === 0 ? "Strong portfolio stewardship contribution." : "",
    employeeComments: index % 8 === 0 ? "Aligned — focus area for next cycle." : "",
  }));
}

function competencies(scores: number[], prefix: string) {
  return blankCompetencyScores().map((item, index) => ({
    ...item,
    id: `${prefix}-${index}`,
    score: (scores[index] ?? 4) as 1 | 2 | 3 | 4 | 5,
    notes: index === 0 ? "Key strength for Talanton fund operations" : "",
  }));
}

/** Two open roles — impact fund hiring priorities. */
export function buildTalantonRecruitmentVacancies(): HrVacancy[] {
  return [
    {
      id: "ti-vac-1",
      title: "Investment Associate — East Africa",
      department: "Investments",
      location: "Nairobi",
      employmentType: "Full time",
      hiringManager: KENNETH.name,
      status: "open",
      openedAt: isoDaysFromNow(-18),
      targetStartDate: isoDaysFromNow(45),
      closingDate: isoDaysFromNow(28),
      headcount: 1,
      salaryBand: "$48–55k",
      description:
        "Support deal sourcing, diligence, and portfolio monitoring across East Africa — field visits, impact measurement, and LP reporting inputs.",
      requirements:
        "2–4 years in impact investing, development finance, or East Africa private equity · fluent English · willingness to travel across Kenya and region",
    },
    {
      id: "ti-vac-2",
      title: "Senior Portfolio Operations Analyst",
      department: "Fund Operations",
      location: "Newtown Square, PA",
      employmentType: "Full time",
      hiringManager: ANDY.name,
      status: "open",
      openedAt: isoDaysFromNow(-10),
      targetStartDate: isoDaysFromNow(40),
      closingDate: isoDaysFromNow(21),
      headcount: 1,
      salaryBand: "$52–60k",
      description:
        "Own quarterly portfolio data collection, compliance attestations, and fund admin workflows across 20+ portfolio company portals.",
      requirements:
        "Fund operations or portfolio company reporting experience · Excel / data hygiene · comfort with multi-currency LP schedules · Philadelphia area preferred",
    },
  ];
}

/** Candidates with interview progress for both open roles. */
export function buildTalantonRecruitmentCandidates(): HrCandidate[] {
  return [
    {
      id: "ti-cand-1",
      name: "Amina Wanjiku",
      email: "amina.wanjiku@example.com",
      phone: "+254 712 555 0142",
      vacancyId: "ti-vac-1",
      role: "Investment Associate — East Africa",
      department: "Investments",
      location: "Nairobi",
      stage: "interview",
      rating: 4,
      interviewer: KENNETH.name,
      recruiter: KENNETH.name,
      expectedSalary: "$52k",
      availability: "2 weeks notice",
      source: "Referral",
      appliedAt: isoDaysFromNow(-14),
      notes: "Former IFC associate — strong agri and fintech diligence background.",
      cvLabel: "Amina_Wanjiku_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "ti-int-1a",
          scheduledAt: `${isoDaysFromNow(-5)}T09:00`,
          type: "video",
          interviewer: KENNETH.name,
          interviewers: KENNETH.name,
          status: "completed",
          outcome: "pass",
          rating: 4,
          strengths: "Clear thesis on underserved counties; fluent on impact metrics.",
          weaknesses: "Limited direct fund LP reporting exposure.",
          feedback: "Advance to panel with Cynthia Omondi.",
          notes: "Recommend panel in Nairobi.",
          recommendation: "yes",
        },
        {
          id: "ti-int-1b",
          scheduledAt: `${isoDaysFromNow(4)}T11:00`,
          type: "panel",
          interviewer: `${KENNETH.name} + ${CYNTHIA.name}`,
          interviewers: `${KENNETH.name}, ${CYNTHIA.name}`,
          status: "scheduled",
          outcome: "pending",
          rating: null,
          strengths: "",
          weaknesses: "",
          feedback: "",
          notes: "Nairobi office panel.",
          recommendation: null,
        },
      ],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "ti-tl-1a", at: isoDaysFromNow(-14), label: "Application received", detail: "Portfolio referral" },
        { id: "ti-tl-1b", at: isoDaysFromNow(-10), label: "Screening complete", detail: "Moved to interview" },
        { id: "ti-tl-1c", at: isoDaysFromNow(-5), label: "First interview", detail: `Video with ${KENNETH.name}` },
        { id: "ti-tl-1d", at: isoDaysFromNow(4), label: "Panel interview scheduled", detail: "Nairobi office" },
      ],
    },
    {
      id: "ti-cand-2",
      name: "Brian Otieno",
      email: "brian.otieno@example.com",
      phone: "+254 733 555 0198",
      vacancyId: "ti-vac-1",
      role: "Investment Associate — East Africa",
      department: "Investments",
      location: "Nairobi",
      stage: "screening",
      rating: 3,
      interviewer: CYNTHIA.name,
      recruiter: KENNETH.name,
      expectedSalary: "$50k",
      availability: "Immediate",
      source: "LinkedIn",
      appliedAt: isoDaysFromNow(-7),
      notes: "Development finance background — KCB Capital rotation.",
      cvLabel: "Brian_Otieno_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "ti-int-2a",
          scheduledAt: `${isoDaysFromNow(2)}T10:00`,
          type: "phone",
          interviewer: KENNETH.name,
          interviewers: KENNETH.name,
          status: "scheduled",
          outcome: "pending",
          rating: null,
          strengths: "",
          weaknesses: "",
          feedback: "",
          notes: "Phone screen.",
          recommendation: null,
        },
      ],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "ti-tl-2a", at: isoDaysFromNow(-7), label: "Application received", detail: "Via LinkedIn" },
        { id: "ti-tl-2b", at: isoDaysFromNow(-3), label: "Moved to screening", detail: "Recruiter triage complete" },
        { id: "ti-tl-2c", at: isoDaysFromNow(2), label: "Phone screen scheduled", detail: KENNETH.name },
      ],
    },
    {
      id: "ti-cand-3",
      name: "Grace Muthoni",
      email: "grace.muthoni@example.com",
      phone: "+254 722 555 0174",
      vacancyId: "ti-vac-1",
      role: "Investment Associate — East Africa",
      department: "Investments",
      location: "Nairobi",
      stage: "applications",
      rating: 0,
      interviewer: "",
      recruiter: KENNETH.name,
      expectedSalary: "$48k",
      availability: "4 weeks notice",
      source: "Careers page",
      appliedAt: isoDaysFromNow(-2),
      notes: "New application — impact measurement MSc.",
      cvLabel: "Grace_Muthoni_CV.pdf",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "ti-tl-3a", at: isoDaysFromNow(-2), label: "Application received", detail: "Via careers page" },
      ],
    },
    {
      id: "ti-cand-4",
      name: "Sarah Mitchell",
      email: "sarah.mitchell@example.com",
      phone: "+1 610 555 0119",
      vacancyId: "ti-vac-2",
      role: "Senior Portfolio Operations Analyst",
      department: "Fund Operations",
      location: "Newtown Square, PA",
      stage: "interview",
      rating: 4,
      interviewer: ANDY.name,
      recruiter: ANDY.name,
      expectedSalary: "$58k",
      availability: "3 weeks notice",
      source: "Referral",
      appliedAt: isoDaysFromNow(-12),
      notes: "Former fund admin at regional PE shop — strong quarterly reporting cadence.",
      cvLabel: "Sarah_Mitchell_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "ti-int-4a",
          scheduledAt: `${isoDaysFromNow(-3)}T14:00`,
          type: "video",
          interviewer: ANDY.name,
          interviewers: ANDY.name,
          status: "completed",
          outcome: "pass",
          rating: 4,
          strengths: "Portfolio data hygiene; calm under LP deadline pressure.",
          weaknesses: "Less East Africa field exposure.",
          feedback: "Strong fit for QPU workflow ownership.",
          notes: "Schedule follow-up with Carol Rubiro.",
          recommendation: "yes",
        },
        {
          id: "ti-int-4b",
          scheduledAt: `${isoDaysFromNow(6)}T15:30`,
          type: "onsite",
          interviewer: `${ANDY.name} + Carol Rubiro`,
          interviewers: `${ANDY.name}, Carol Rubiro`,
          status: "scheduled",
          outcome: "pending",
          rating: null,
          strengths: "",
          weaknesses: "",
          feedback: "",
          notes: "Philadelphia HQ — portfolio ops deep-dive.",
          recommendation: null,
        },
      ],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "ti-tl-4a", at: isoDaysFromNow(-12), label: "Application received", detail: "LP network referral" },
        { id: "ti-tl-4b", at: isoDaysFromNow(-8), label: "Screening complete", detail: "Moved to interview" },
        { id: "ti-tl-4c", at: isoDaysFromNow(-3), label: "First interview", detail: `Video with ${ANDY.name}` },
        { id: "ti-tl-4d", at: isoDaysFromNow(6), label: "Onsite interview scheduled", detail: "Newtown Square HQ" },
      ],
    },
    {
      id: "ti-cand-5",
      name: "James Patterson",
      email: "james.patterson@example.com",
      phone: "+1 215 555 0188",
      vacancyId: "ti-vac-2",
      role: "Senior Portfolio Operations Analyst",
      department: "Fund Operations",
      location: "Philadelphia, PA",
      stage: "offer",
      rating: 5,
      interviewer: ANDY.name,
      recruiter: ANDY.name,
      expectedSalary: "$56k",
      availability: "2 weeks notice",
      source: "Agency",
      appliedAt: isoDaysFromNow(-28),
      notes: "Offer stage — competing with regional asset manager.",
      cvLabel: "James_Patterson_CV.pdf",
      rejected: false,
      interviews: [
        {
          id: "ti-int-5a",
          scheduledAt: `${isoDaysFromNow(-18)}T10:00`,
          type: "video",
          interviewer: ANDY.name,
          interviewers: ANDY.name,
          status: "completed",
          outcome: "pass",
          rating: 5,
          strengths: "Exceptional fund ops discipline; Wise treasury familiarity.",
          weaknesses: "Salary expectations slightly above band.",
          feedback: "Top candidate — move to offer.",
          notes: "",
          recommendation: "strong_yes",
        },
        {
          id: "ti-int-5b",
          scheduledAt: `${isoDaysFromNow(-10)}T13:00`,
          type: "onsite",
          interviewer: `${ANDY.name} + ${MERCY.name}`,
          interviewers: `${ANDY.name}, ${MERCY.name}`,
          status: "completed",
          outcome: "pass",
          rating: 5,
          strengths: "Team fit confirmed; portfolio portal walkthrough strong.",
          weaknesses: "",
          feedback: "Proceed to offer.",
          notes: "",
          recommendation: "strong_yes",
        },
      ],
      offer: {
        status: "sent",
        salary: "$56,000",
        startDate: isoDaysFromNow(21),
        employmentType: "Full time",
        notes: "Offer sent — awaiting response by Friday.",
        sentAt: isoDaysFromNow(-2),
      },
      timeline: [
        { id: "ti-tl-5a", at: isoDaysFromNow(-28), label: "Application received", detail: "Agency shortlist" },
        { id: "ti-tl-5b", at: isoDaysFromNow(-18), label: "First interview", detail: ANDY.name },
        { id: "ti-tl-5c", at: isoDaysFromNow(-10), label: "Onsite interview", detail: "HQ panel" },
        { id: "ti-tl-5d", at: isoDaysFromNow(-2), label: "Offer sent", detail: "$56k — pending response" },
      ],
    },
    {
      id: "ti-cand-6",
      name: "Emily Chen",
      email: "emily.chen@example.com",
      phone: "+1 484 555 0155",
      vacancyId: "ti-vac-2",
      role: "Senior Portfolio Operations Analyst",
      department: "Fund Operations",
      location: "Newtown Square, PA",
      stage: "applications",
      rating: 0,
      interviewer: "",
      recruiter: ANDY.name,
      expectedSalary: "$54k",
      availability: "Immediate",
      source: "Job board",
      appliedAt: isoDaysFromNow(-1),
      notes: "New application — Big Four fund admin background.",
      cvLabel: "Emily_Chen_CV.pdf",
      rejected: false,
      interviews: [],
      offer: emptyOfferDetails(),
      timeline: [
        { id: "ti-tl-6a", at: isoDaysFromNow(-1), label: "Application received", detail: "Via job board" },
      ],
    },
  ];
}

export function buildTalantonLeaveRequests(): HrLeaveRequest[] {
  return [
    {
      id: "ti-leave-1",
      employeeId: KENNETH.id,
      employeeName: KENNETH.name,
      department: KENNETH.department,
      location: "Nairobi",
      role: KENNETH.role,
      managerName: DAVID.name,
      type: "annual",
      startDate: isoDaysFromNow(-2),
      endDate: isoDaysFromNow(3),
      days: 5,
      status: "approved",
      notes: "Family visit — US",
      requestedAt: isoDaysFromNow(-18),
      decidedAt: isoDaysFromNow(-15),
    },
    {
      id: "ti-leave-2",
      employeeId: MICHELLE.id,
      employeeName: MICHELLE.name,
      department: MICHELLE.department,
      location: "Nairobi",
      role: MICHELLE.role,
      managerName: DAVID.name,
      type: "training",
      startDate: isoDaysFromNow(4),
      endDate: isoDaysFromNow(5),
      days: 2,
      status: "approved",
      notes: "LP roadshow prep workshop — Philadelphia",
      requestedAt: isoDaysFromNow(-8),
      decidedAt: isoDaysFromNow(-6),
    },
    {
      id: "ti-leave-3",
      employeeId: MERCY.id,
      employeeName: MERCY.name,
      department: MERCY.department,
      location: "Nairobi",
      role: MERCY.role,
      managerName: ANDY.name,
      type: "annual",
      startDate: isoDaysFromNow(10),
      endDate: isoDaysFromNow(14),
      days: 5,
      status: "approved",
      notes: "Annual leave",
      requestedAt: isoDaysFromNow(-12),
      decidedAt: isoDaysFromNow(-10),
    },
    {
      id: "ti-leave-4",
      employeeId: HARRY.id,
      employeeName: HARRY.name,
      department: HARRY.department,
      location: "Newtown Square, PA",
      role: HARRY.role,
      managerName: DAVID.name,
      type: "annual",
      startDate: isoDaysFromNow(18),
      endDate: isoDaysFromNow(22),
      days: 5,
      status: "pending",
      notes: "Portfolio field visit follow-up travel",
      requestedAt: isoDaysFromNow(-3),
      decidedAt: null,
    },
    {
      id: "ti-leave-5",
      employeeId: LINDA.id,
      employeeName: LINDA.name,
      department: LINDA.department,
      location: "Nairobi",
      role: LINDA.role,
      managerName: CYNTHIA.name,
      type: "sick",
      startDate: isoDaysFromNow(-1),
      endDate: isoDaysFromNow(1),
      days: 2,
      status: "approved",
      notes: "Medical recovery",
      requestedAt: isoDaysFromNow(-1),
      decidedAt: isoDaysFromNow(-1),
    },
    {
      id: "ti-leave-6",
      employeeId: IRIS.id,
      employeeName: IRIS.name,
      department: IRIS.department,
      location: "Newtown Square, PA",
      role: IRIS.role,
      managerName: DAVID.name,
      type: "annual",
      startDate: isoDaysFromNow(25),
      endDate: isoDaysFromNow(29),
      days: 5,
      status: "approved",
      notes: "Summer break",
      requestedAt: isoDaysFromNow(-7),
      decidedAt: isoDaysFromNow(-5),
    },
  ];
}

export function buildTalantonLeaveBalances(): HrLeaveBalance[] {
  return [
    {
      employeeId: KENNETH.id,
      employeeName: KENNETH.name,
      department: KENNETH.department,
      location: "Nairobi",
      annualAllocated: 21,
      annualTaken: 5,
      sickTaken: 0,
      trainingTaken: 0,
    },
    {
      employeeId: MICHELLE.id,
      employeeName: MICHELLE.name,
      department: MICHELLE.department,
      location: "Nairobi",
      annualAllocated: 21,
      annualTaken: 3,
      sickTaken: 1,
      trainingTaken: 2,
    },
    {
      employeeId: MERCY.id,
      employeeName: MERCY.name,
      department: MERCY.department,
      location: "Nairobi",
      annualAllocated: 21,
      annualTaken: 8,
      sickTaken: 0,
      trainingTaken: 0,
    },
    {
      employeeId: HARRY.id,
      employeeName: HARRY.name,
      department: HARRY.department,
      location: "Newtown Square, PA",
      annualAllocated: 20,
      annualTaken: 6,
      sickTaken: 0,
      trainingTaken: 1,
    },
    {
      employeeId: LINDA.id,
      employeeName: LINDA.name,
      department: LINDA.department,
      location: "Nairobi",
      annualAllocated: 21,
      annualTaken: 4,
      sickTaken: 2,
      trainingTaken: 0,
    },
    {
      employeeId: IRIS.id,
      employeeName: IRIS.name,
      department: IRIS.department,
      location: "Newtown Square, PA",
      annualAllocated: 20,
      annualTaken: 5,
      sickTaken: 0,
      trainingTaken: 0,
    },
    {
      employeeId: ANDY.id,
      employeeName: ANDY.name,
      department: ANDY.department,
      location: "Newtown Square, PA",
      annualAllocated: 20,
      annualTaken: 3,
      sickTaken: 0,
      trainingTaken: 0,
    },
    {
      employeeId: CYNTHIA.id,
      employeeName: CYNTHIA.name,
      department: CYNTHIA.department,
      location: "Nairobi",
      annualAllocated: 21,
      annualTaken: 7,
      sickTaken: 0,
      trainingTaken: 1,
    },
  ];
}

export function buildTalantonPublicHolidays(): HrPublicHoliday[] {
  return [
    {
      id: "ti-hol-1",
      name: "Labor Day",
      date: "2026-09-07",
      calendar: "United States (Federal)",
    },
    {
      id: "ti-hol-2",
      name: "Thanksgiving Day",
      date: "2026-11-26",
      calendar: "United States (Federal)",
    },
    {
      id: "ti-hol-3",
      name: "Jamhuri Day",
      date: "2026-12-12",
      calendar: "Kenya",
    },
    {
      id: "ti-hol-4",
      name: "Christmas Day",
      date: "2026-12-25",
      calendar: "United States (Federal)",
    },
  ];
}

export function buildTalantonPerformanceReviews(): HrPerformanceReview[] {
  return [
    {
      id: "ti-rev-harry",
      employeeId: HARRY.id,
      employeeName: HARRY.name,
      department: HARRY.department,
      role: HARRY.role,
      managerName: DAVID.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 5,
      strengths: "Portfolio stewardship across Momentum and East Africa holdings; credible LP relationships.",
      areasForImprovement: "Delegate more operational follow-through to Nairobi team.",
      trainingRecommendations: "Advanced impact measurement workshop",
      promotionRecommendation: "no",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "retain",
      employeeGoals: "Close two follow-on investments and refresh impact thesis for top five holdings.",
      nextReviewDate: isoDaysFromNow(120),
      summary: "Exceptional half — trusted partner across fund and portfolio.",
      responses: ratedResponses([5, 5, 4, 5, 5, 4, 4, 5, 5, 4, 5, 5, 4, 5, 4, 5, 4, 5, 4, 5]),
      objectives: [
        {
          id: "ti-obj-harry-1",
          title: "Momentum Fund pipeline",
          description: "Advance two qualified deals into IC-ready memos by Q4.",
          progressPercent: 72,
          dueDate: isoDaysFromNow(45),
          status: "on_track",
          weight: 45,
          owner: HARRY.name,
          scope: "employee",
          employeeId: HARRY.id,
          employeeName: HARRY.name,
          department: HARRY.department,
        },
      ],
      competencies: competencies([5, 5, 4, 5, 5, 4, 4, 5, 5, 4], "ti-comp-harry"),
      developmentPlan: [],
      createdAt: isoDaysFromNow(-35),
      updatedAt: isoDaysFromNow(-4),
      submittedAt: isoDaysFromNow(-4),
      approvedAt: null,
      completedAt: null,
      reviewType: "annual",
      priority: "high",
      dueDate: isoDaysFromNow(7),
      challenges: "Travel load across US and East Africa.",
      achievements: "Led successful Arc Ride field visit and LP update.",
      employeeSelfAssessment: "Strong cycle — prioritising delegation next half.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: true,
      careerAspirations: "Broader fund leadership as platform scales.",
      managerCareerComments: "Key succession candidate for expanded mandate.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "ti-rev-cynthia",
      employeeId: CYNTHIA.id,
      employeeName: CYNTHIA.name,
      department: CYNTHIA.department,
      role: CYNTHIA.role,
      managerName: IRIS.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 4,
      strengths: "Deal diligence rigour; strong Nairobi investment team leadership.",
      areasForImprovement: "Tighten written IC memos for US-based committee members.",
      trainingRecommendations: "Executive writing for investment committees",
      promotionRecommendation: "later",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "develop",
      employeeGoals: "Own East Africa sourcing calendar and two sector deep-dives.",
      nextReviewDate: isoDaysFromNow(90),
      summary: "Solid contributor — growing into broader investment leadership.",
      responses: ratedResponses([4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
      objectives: [
        {
          id: "ti-obj-cynthia-1",
          title: "East Africa deal flow",
          description: "Maintain 12 qualified opportunities in active pipeline.",
          progressPercent: 68,
          dueDate: isoDaysFromNow(30),
          status: "on_track",
          weight: 40,
          owner: CYNTHIA.name,
          scope: "employee",
          employeeId: CYNTHIA.id,
          employeeName: CYNTHIA.name,
          department: CYNTHIA.department,
        },
      ],
      competencies: competencies([4, 5, 4, 4, 5, 4, 4, 4, 5, 4], "ti-comp-cynthia"),
      developmentPlan: [],
      createdAt: isoDaysFromNow(-30),
      updatedAt: isoDaysFromNow(-6),
      submittedAt: isoDaysFromNow(-6),
      approvedAt: null,
      completedAt: null,
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(14),
      challenges: "Balancing field travel with memo quality.",
      achievements: "Closed diligence on two portfolio follow-ons.",
      employeeSelfAssessment: "Improving IC narrative discipline.",
      careerPotential: "high",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Lead Nairobi investment pod.",
      managerCareerComments: "Continue mentoring associate pipeline.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
    {
      id: "ti-rev-mercy",
      employeeId: MERCY.id,
      employeeName: MERCY.name,
      department: MERCY.department,
      role: MERCY.role,
      managerName: ANDY.name,
      reviewPeriod: "H1 2026",
      status: "draft",
      overallRating: null,
      strengths: "Fund finance accuracy; calm under audit and LP deadline pressure.",
      areasForImprovement: "Cross-train on US payroll close workflow.",
      trainingRecommendations: "US GAAP fund accounting refresher",
      promotionRecommendation: null,
      salaryReviewRecommendation: "hold",
      managerRecommendation: "retain",
      employeeGoals: "Own Nairobi finance close and KPMG audit fieldwork pack.",
      nextReviewDate: isoDaysFromNow(60),
      summary: "Review in progress — finance backbone for East Africa office.",
      responses: blankQuestionResponses(),
      objectives: [
        {
          id: "ti-obj-mercy-1",
          title: "Audit readiness",
          description: "Complete FY2025 audit fieldwork with zero material adjustments.",
          progressPercent: 55,
          dueDate: isoDaysFromNow(40),
          status: "on_track",
          weight: 50,
          owner: MERCY.name,
          scope: "employee",
          employeeId: MERCY.id,
          employeeName: MERCY.name,
          department: MERCY.department,
        },
      ],
      competencies: blankCompetencyScores(),
      developmentPlan: [],
      createdAt: isoDaysFromNow(-12),
      updatedAt: isoDaysFromNow(-1),
      submittedAt: null,
      approvedAt: null,
      completedAt: null,
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(21),
      challenges: "Currency reconciliation across Nairobi and Philadelphia.",
      achievements: "Q2 management accounts delivered ahead of board pack.",
      employeeSelfAssessment: "",
      careerPotential: "medium",
      promotionReady: "24_months",
      successionCandidate: false,
      careerAspirations: "Senior finance leadership in fund operations.",
      managerCareerComments: "",
      signedOffManager: false,
      signedOffEmployee: false,
    },
    {
      id: "ti-rev-michelle",
      employeeId: MICHELLE.id,
      employeeName: MICHELLE.name,
      department: MICHELLE.department,
      role: MICHELLE.role,
      managerName: DAVID.name,
      reviewPeriod: "H1 2026",
      status: "submitted",
      overallRating: 4,
      strengths: "LP communication and East Africa investor narrative.",
      areasForImprovement: "Standardise quarterly LP update templates.",
      trainingRecommendations: "Investor relations best practices",
      promotionRecommendation: "no",
      salaryReviewRecommendation: "hold",
      managerRecommendation: "retain",
      employeeGoals: "Deliver two successful LP roadshow cycles in H2.",
      nextReviewDate: isoDaysFromNow(100),
      summary: "Strong IR execution — key voice for faith-aligned LPs.",
      responses: ratedResponses([4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4]),
      objectives: [
        {
          id: "ti-obj-michelle-1",
          title: "LP engagement score",
          description: "Maintain ≥ 4.5 average LP satisfaction on quarterly updates.",
          progressPercent: 80,
          dueDate: isoDaysFromNow(50),
          status: "on_track",
          weight: 35,
          owner: MICHELLE.name,
          scope: "employee",
          employeeId: MICHELLE.id,
          employeeName: MICHELLE.name,
          department: MICHELLE.department,
        },
      ],
      competencies: competencies([4, 4, 5, 4, 4, 4, 4, 4, 5, 4], "ti-comp-michelle"),
      developmentPlan: [],
      createdAt: isoDaysFromNow(-28),
      updatedAt: isoDaysFromNow(-5),
      submittedAt: isoDaysFromNow(-5),
      approvedAt: null,
      completedAt: null,
      reviewType: "annual",
      priority: "medium",
      dueDate: isoDaysFromNow(10),
      challenges: "Coordinating US and Kenya LP calendars.",
      achievements: "Q2 LP webinar exceeded attendance targets.",
      employeeSelfAssessment: "Focused on template standardisation.",
      careerPotential: "high",
      promotionReady: "12_months",
      successionCandidate: false,
      careerAspirations: "Head of investor relations as fund II scales.",
      managerCareerComments: "Trusted external voice for Talanton.",
      signedOffManager: false,
      signedOffEmployee: true,
    },
  ];
}

export function buildTalantonPerformanceGoals(): HrPerformanceObjective[] {
  return [
    {
      id: "ti-goal-org-1",
      title: "Fund I deployment pace",
      description: "Maintain disciplined deployment across remaining Fund I capital.",
      progressPercent: 62,
      dueDate: isoDaysFromNow(120),
      status: "on_track",
      weight: 30,
      owner: DAVID.name,
      scope: "organisation",
      employeeId: undefined,
      employeeName: undefined,
      department: "Leadership",
    },
    {
      id: "ti-goal-org-2",
      title: "Portfolio impact measurement",
      description: "All holdings report jobs created and people served on monthly cadence.",
      progressPercent: 78,
      dueDate: isoDaysFromNow(60),
      status: "on_track",
      weight: 35,
      owner: HARRY.name,
      scope: "organisation",
      employeeId: undefined,
      employeeName: undefined,
      department: "Leadership",
    },
    {
      id: "ti-goal-org-3",
      title: "Quarterly portfolio update quality",
      description: "Ship Q3 publication with board-ready impact narrative.",
      progressPercent: 45,
      dueDate: isoDaysFromNow(35),
      status: "on_track",
      weight: 35,
      owner: MICHELLE.name,
      scope: "organisation",
      employeeId: undefined,
      employeeName: undefined,
      department: "Investor Relations",
    },
    {
      id: "ti-goal-dept-1",
      title: "Nairobi office compliance",
      description: "Complete all portfolio company portal attestations by month-end.",
      progressPercent: 71,
      dueDate: isoDaysFromNow(20),
      status: "on_track",
      weight: 25,
      owner: KENNETH.name,
      scope: "department",
      department: "East Africa",
      employeeId: null,
    },
    {
      id: "ti-goal-dept-2",
      title: "Fund finance close",
      description: "Philadelphia and Nairobi closes within 5 business days of quarter-end.",
      progressPercent: 85,
      dueDate: isoDaysFromNow(25),
      status: "on_track",
      weight: 30,
      owner: ANDY.name,
      scope: "department",
      department: "Finance",
      employeeId: null,
    },
  ];
}

export function buildTalantonHrReports(): HrSavedReport[] {
  return [
    {
      id: "ti-rep-1",
      name: "Talanton Headcount — Aug 2026",
      kind: "headcount",
      output: "excel",
      filters: emptyHrReportFilters(),
      createdAt: isoDaysFromNow(-3),
      updatedAt: isoDaysFromNow(-3),
      createdBy: ANDY.name,
      rowCount: 23,
      previewLines: [
        "Headcount",
        "Department: All",
        "Location: All offices",
        "",
        "Segment,Count,Share",
        "Leadership,3,13%",
        "Investments,6,26%",
        "Finance,3,13%",
        "Fund Operations,2,9%",
        "Investor Relations,1,4%",
        "East Africa,1,4%",
        "Marketing,2,9%",
        "Board,8,35%",
      ],
    },
    {
      id: "ti-rep-2",
      name: "Talanton Leave Summary — H1 2026",
      kind: "leave_summary",
      output: "pdf",
      filters: {
        ...emptyHrReportFilters(),
        dateFrom: "2026-01-01",
        dateTo: "2026-08-07",
      },
      createdAt: isoDaysFromNow(-5),
      updatedAt: isoDaysFromNow(-5),
      createdBy: MERCY.name,
      rowCount: 6,
      previewLines: [
        "Leave Summary",
        "Location: Philadelphia + Nairobi",
        "Period: 2026-01-01 to 2026-08-07",
        "",
        "Type,Approved days,Pending requests",
        "Annual Leave,28,1",
        "Sick Leave,2,0",
        "Training,2,0",
        "Remote,0,0",
      ],
    },
    {
      id: "ti-rep-3",
      name: "Talanton Recruitment Pipeline — Aug 2026",
      kind: "recruitment",
      output: "excel",
      filters: emptyHrReportFilters(),
      createdAt: isoDaysFromNow(-1),
      updatedAt: isoDaysFromNow(-1),
      createdBy: KENNETH.name,
      rowCount: 2,
      previewLines: [
        "Recruitment Report",
        "Department: All",
        "",
        "Role,Open,Interview,Offer,Time to hire (avg)",
        "Investment Associate — East Africa,1,2,0,—",
        "Senior Portfolio Operations Analyst,1,2,1,28 days",
        "",
        "Active candidates: 6",
        "Offers pending: 1",
      ],
    },
  ];
}

export function buildTalantonHrActivity(): Array<{
  id: string;
  at: string;
  label: string;
  detail: string;
}> {
  return [
    {
      id: "ti-act-1",
      at: isoDaysFromNow(0),
      label: "Performance review submitted",
      detail: `${HARRY.name} — H1 2026`,
    },
    {
      id: "ti-act-2",
      at: isoDaysFromNow(-1),
      label: "Offer sent",
      detail: "Senior Portfolio Operations Analyst — James Patterson",
    },
    {
      id: "ti-act-3",
      at: isoDaysFromNow(-2),
      label: "Panel interview scheduled",
      detail: "Investment Associate — Amina Wanjiku",
    },
    {
      id: "ti-act-4",
      at: isoDaysFromNow(-4),
      label: "Leave approved",
      detail: `${KENNETH.name} — annual (5 days)`,
    },
    {
      id: "ti-act-5",
      at: isoDaysFromNow(-6),
      label: "Recruitment role opened",
      detail: "Senior Portfolio Operations Analyst — Philadelphia",
    },
    {
      id: "ti-act-6",
      at: isoDaysFromNow(-14),
      label: "Recruitment role opened",
      detail: "Investment Associate — East Africa — Nairobi",
    },
  ];
}
